import { captureEvent } from '@/lib/analytics';
import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
import type { PMFInterviewLog } from '@/hooks/usePMFLab';
import type { PMFSurveyAggregate } from '@/hooks/usePMFSurvey';


export default function PMFConnectedEvidence({ productId, contextId, onAdded, onReview, interviews = [], surveyAggregate }: { productId: string; contextId: string | null; onAdded: () => Promise<void>; onReview?: () => void; interviews?: PMFInterviewLog[]; surveyAggregate?: PMFSurveyAggregate }) {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('all');
  const [rows,setRows]=useState<any[]>([]); const [selected,setSelected]=useState(''); const [screening,setScreening]=useState('');
  const [target,setTarget]=useState(false); const [busy,setBusy]=useState(false); const [rounds,setRounds]=useState<any[]>([]);
  useEffect(()=>{ let active=true; setRows([]);setSelected('');setRounds([]);
    if(contextId) void Promise.all([
      productId ? (supabase as any).from('ct_evidence').select('*').eq('product_id',productId).in('kind',['interview','survey','session']).order('captured_at',{ascending:false}).limit(100) : Promise.resolve({data:[],error:null}),
      (supabase as any).from('pmf_analysis_results').select('id,created_at,analysis_data').eq('validation_context_id',contextId).order('created_at',{ascending:false}).limit(2),
    ]).then(([e,r])=>{if(active){if(e.error)toast.error('Could not load imported evidence.');setRows(e.data??[]);setRounds(r.data??[]);}}).catch(()=>{if(active)toast.error('Could not load customer evidence. Reopen this context to retry.');});
    return()=>{active=false;};
  },[productId,contextId]);
  if(!contextId)return null;
  const row=rows.find(r=>r.id===selected);
  const matches = (value: string) => value.toLowerCase().includes(query.toLowerCase());
  const pending = rows.filter(item => !interviews.some(interview => interview.sourceEvidenceId === item.id));
  const feedback = [...(surveyAggregate?.verbatims ?? []), ...(surveyAggregate?.conceptFeedback ?? [])];
  return <section className="space-y-4 rounded-xl border p-4 sm:p-5"><h3 className="text-lg font-semibold">Customer evidence inbox</h3>{productId && import.meta.env.VITE_VALIDATION_SESSIONS_ENABLED === 'true' && <Button asChild variant="outline"><Link to={`/validation-sessions?context=${contextId}&product=${productId}`}>Book a validation session</Link></Button>}
    <div className="flex flex-col gap-3 sm:flex-row"><Input aria-label="Search customer feedback" placeholder="Search feedback, names or segments" value={query} onChange={event => setQuery(event.target.value)} /><label className="shrink-0 text-sm"><span className="sr-only">Evidence type</span><select className="min-h-10 rounded-md border bg-background p-2" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All evidence</option><option value="review">Needs review ({pending.length})</option><option value="interviews">Saved conversations ({interviews.length})</option><option value="survey">Recent survey feedback ({feedback.length})</option></select></label></div>
    <div className="max-h-96 space-y-3 overflow-y-auto" aria-label="Customer feedback records">
      {['all','review'].includes(filter) && pending.filter(item => matches(`${item.summary.respondent ?? ''} ${item.summary.feedback ?? ''} ${item.segment ?? ''}`)).map(item => <article key={item.id} className="rounded-lg border border-primary/25 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="font-medium">{item.summary.respondent || 'Imported respondent'}</h4><Button size="sm" variant="outline" onClick={() => {setSelected(item.id);setTarget(false);setScreening('');}}>Review customer fit</Button></div><p className="mt-1 text-sm whitespace-pre-wrap">{item.summary.feedback || 'Feedback column needs mapping.'}</p><p className="mt-2 text-xs text-muted-foreground">Needs review · {item.kind === 'session' ? 'Validation session' : item.kind} · {item.incentivized ? 'Incentivized' : 'No incentive recorded'}</p></article>)}
      {['all','interviews'].includes(filter) && interviews.filter(item => matches(`${item.intervieweeName} ${item.mainFeedback} ${item.segment}`)).map(item => <article key={item.id} className="rounded-lg border p-3"><h4 className="font-medium">{item.intervieweeName || 'Customer conversation'}</h4><p className="mt-1 whitespace-pre-wrap text-sm">{item.mainFeedback}</p><p className="mt-2 text-xs text-muted-foreground">{item.targetCustomer === true ? 'Target-customer evidence' : item.targetCustomer === false ? 'General feedback - clarity and usability' : 'Customer fit not recorded'} · {item.segment || 'Segment unspecified'}{item.incentivized ? ' · Incentivized' : ''}</p></article>)}
      {['all','survey'].includes(filter) && feedback.filter(item => matches(`${item.feedback ?? ''} ${item.mainBenefit ?? ''} ${item.role ?? ''}`)).map((item,index) => <article key={item.createdAt+index} className="rounded-lg border p-3"><h4 className="font-medium">Survey feedback</h4><p className="mt-1 whitespace-pre-wrap text-sm">{item.feedback || item.mainBenefit || 'No written feedback provided.'}</p><p className="mt-2 text-xs text-muted-foreground">{item.seanEllis === 'ineligible' ? 'Concept or unknown use — excluded from Sean Ellis percentage' : 'Self-reported product user'} · {item.role || 'Role unspecified'}</p></article>)}
    </div>
    {!interviews.length && !pending.length && !feedback.length && <div className="rounded-lg bg-muted p-4"><p className="font-medium">Start with one customer conversation</p><p className="mt-1 text-sm text-muted-foreground">Ask about a recent problem and the workaround they used. Save their own words, then look for repeated objections.</p><div className="mt-3 flex flex-wrap gap-2">{onReview && <Button onClick={onReview}>Add your first conversation</Button>}{productId && <Button asChild variant="outline"><Link to="/connections">Import existing feedback</Link></Button>}</div></div>}
    {query && <p className="text-xs text-muted-foreground">Showing matches for “{query}”. Clear the search to see all records.</p>}
    <p className="text-sm text-muted-foreground">Review original feedback and confirm customer fit. General reviewer feedback helps clarity; only screened target customers enter demand assessment. Repeated respondents count once per context.</p>
    {rows.length > 0 && <select aria-label="Imported feedback" className="w-full rounded border bg-background p-2" value={selected} onChange={e=>{setSelected(e.target.value);setTarget(false);setScreening('');}}><option value="">Choose feedback ({rows.length} recent records)</option>{rows.map(r=><option key={r.id} value={r.id}>{r.summary.respondent||r.summary.source} · {new Date(r.captured_at).toLocaleDateString()} · {r.incentivized?'Incentivized':'No incentive recorded'}</option>)}</select>}
    {row&&<><p className="text-sm whitespace-pre-wrap">{row.summary.feedback||'No feedback mapped. Update the import mapping in Connections.'}</p><p className="text-xs">Segment: {row.segment||'Unknown'} · Product use: {row.product_usage} · Source: {row.provenance}</p>
      <details><summary className="cursor-pointer text-sm">Original feedback</summary><pre className="max-h-64 overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify(row.original,null,2)}</pre></details>
      <label className="flex gap-2 text-sm"><input type="checkbox" checked={target} onChange={e=>setTarget(e.target.checked)}/>This person fits the target customer</label>
      {target&&<Input aria-label="Customer fit evidence" placeholder="Their role, problem experienced, and why they are a potential buyer or user" value={screening} onChange={e=>setScreening(e.target.value)}/>}
      <Button disabled={busy||!row.summary.feedback||(target&&screening.trim().length<20)} onClick={async()=>{setBusy(true);try{const {error}=await(supabase as any).rpc('ct_accept_pmf_evidence',{p_context:contextId,p_evidence:row.id,p_target_customer:target,p_screening:screening});if(error)throw error;await onAdded();captureEvent('ct_pmf_import_added',{product_id:productId,context_id:contextId,target_customer:target,incentivized:row.incentivized});toast.success('Evidence added. Re-score this validation context to review what changed.');}catch(e){toast.error(e instanceof Error?e.message:'Could not add evidence.');}finally{setBusy(false);}}}>Add to this validation context</Button></>}
    {onReview&&<Button variant="outline" onClick={onReview}>Review updated evidence and re-score</Button>}
    {rounds.length>0&&<details><summary className="cursor-pointer text-sm">Compare latest validation rounds</summary><div className="grid gap-3 md:grid-cols-2">{rounds.map((r,i)=><article key={r.id} className="space-y-2 rounded border p-3 text-sm"><h4 className="font-medium">{i===0?'Latest':'Previous'} - {new Date(r.created_at).toLocaleDateString()}</h4><p>{r.analysis_data?.summaryInsight||'Open the saved assessment for the full decision.'}</p><p><strong>Decision:</strong> {r.analysis_data?.decision||'Not recorded'} - Score {r.analysis_data?.overallScore??'Unknown'}</p><p><strong>Objections:</strong> {(r.analysis_data?.commonObjections||[]).join('; ')||'None recorded'}</p><p><strong>Demand behaviors:</strong> {(r.analysis_data?.buyingSignals||[]).join('; ')||'None recorded'}</p><p><strong>Segments represented:</strong> {[...new Set((r.analysis_data?.evidenceAnswers?.interviews||[]).map((interview:any)=>interview.segment).filter(Boolean))].join(', ')||'Unknown'}</p><p><strong>Next test:</strong> {r.analysis_data?.nextExperiment||'Not recorded'}</p>{r.analysis_data?.decisionChange?.explanation&&<p>{r.analysis_data.decisionChange.explanation}</p>}</article>)}</div></details>}
  </section>;
}
