import {useState} from 'react';
import {supabase} from '@/integrations/supabase/client';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {toast} from 'sonner';
export default function ValidationReviewQueue(){
 const [rows,setRows]=useState<any[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[seconds,setSeconds]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false);
 async function call(body:any){const {data,error}=await supabase.functions.invoke('validation-sessions',{body});if(error||data?.error)throw new Error(data?.error||error?.message);return data;}
 async function load(){setBusy(true);try{setRows((await call({action:'review_queue'})).sessions);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 return <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Administrator: validation pilot review</summary><Button className="my-3" variant="outline" disabled={busy} onClick={()=>void load()}>Load cases</Button>{rows.map(row=><article key={row.id} className="space-y-2 border-t py-3 text-sm"><p>{row.id} · {new Date(row.starts_at).toLocaleString()}</p><p>{row.review_reason||'Attendance requires review'} · Reward {row.reward_status}</p><p>Founder {row.founder_id} · Reviewer {row.reviewer_id||'External invitee'}</p><details><summary>Attendance evidence and feedback</summary><pre className="overflow-auto whitespace-pre-wrap text-xs">{JSON.stringify({attendance:row.attendance_evidence,before:row.pre_feedback,feedback:row.feedback},null,2)}</pre></details><label className="block">Independent identity and attendance evidence, or rejection reason<Textarea value={notes[row.id]||''} onChange={e=>setNotes({...notes,[row.id]:e.target.value})}/></label><label className="block">Verified overlap in seconds<Input type="number" min="900" max="1500" value={seconds[row.id]||''} onChange={e=>setSeconds({...seconds,[row.id]:e.target.value})}/></label><div className="flex gap-2">{[true,false].map(approve=><Button key={String(approve)} variant="outline" disabled={busy||(notes[row.id]?.trim().length||0)<20} onClick={async()=>{setBusy(true);try{await call({action:'resolve_review',sessionId:row.id,approve,reason:notes[row.id],overlapSeconds:Number(seconds[row.id])});await load();toast.success('Review recorded. All reward limits still apply.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}>{approve?'Confirm attendance':'Decline reward'}</Button>)}</div></article>)}</details>;
}
