import {
  WAITLIST_FONT_PRESETS,
  WAITLIST_SECTION_ORDER,
  WAITLIST_THEME_PRESETS,
  type WaitlistContent,
  type WaitlistTemplateId,
} from '@/lib/waitlist';

export interface WaitlistTemplateDefinition {
  id: WaitlistTemplateId;
  name: string;
  productType: string;
  description: string;
  bestFor: string;
  previewLabel: string;
  content: Partial<WaitlistContent>;
}

const dark = WAITLIST_THEME_PRESETS.dark;
const light = WAITLIST_THEME_PRESETS.light;

export const WAITLIST_TEMPLATE_LIBRARY: WaitlistTemplateDefinition[] = [
  {
    id: 'saas',
    name: 'SaaS Signal',
    productType: 'SaaS',
    description: 'A crisp B2B landing page for showing the workflow pain, product outcome, and early access CTA.',
    bestFor: 'Dashboards, workflow tools, productivity SaaS',
    previewLabel: 'Operational clarity',
    content: {
      templateId: 'saas',
      sectionOrder: ['problemSolution', 'benefits', 'howItWorks', 'testimonials', 'faq'],
      headline: 'Validate demand before you build the full platform',
      headlineVariantB: 'Launch the waitlist for your SaaS before writing production code',
      subheadline: 'Show teams the painful workflow you solve, collect qualified emails, and learn which features deserve the first sprint.',
      problemStatement: 'Teams are stitching together spreadsheets, docs, and status calls because the existing tools are too broad or too heavy for the job.',
      solutionSummary: 'Your SaaS gives early users one focused place to manage the workflow, understand progress, and reduce manual follow-up.',
      benefits: [
        'Explain the exact workflow pain your product removes',
        'Capture early teams who feel the problem now',
        'Use signup intent to prioritize the first feature set',
      ],
      howItWorks: ['Name the workflow', 'Invite the first teams', 'Shape the beta around real demand'],
      trustItems: ['B2B ready', 'Beta access', 'Founder-led'],
      socialProof: 'Built for founders testing a workflow product with real teams before a full SaaS build.',
      ctaText: 'Request early access',
      emailPlaceholder: 'Work email',
      theme: 'dark',
      accentColor: 'indigo',
      layout: 'split',
      textAlign: 'left',
      typography: {
        headingFamily: WAITLIST_FONT_PRESETS[1].value,
        bodyFamily: WAITLIST_FONT_PRESETS[3].value,
        headingWeight: 800,
        bodyWeight: 500,
        headingSize: 54,
        subheadingSize: 21,
        bodySize: 16,
        letterSpacing: 0,
      },
      colors: {
        ...dark,
        pageBackground: '#08111f',
        sectionBackground: '#101827',
        buttonBackground: '#f8fafc',
        buttonText: '#0f172a',
      },
      spacing: { sectionPaddingY: 76, contentMaxWidth: 1160, cardRadius: 18 },
    },
  },
  {
    id: 'ai-tool',
    name: 'AI Preview Lab',
    productType: 'AI Tool',
    description: 'A high-contrast template for demonstrating a sharp AI outcome and inviting hands-on beta users.',
    bestFor: 'AI copilots, automation tools, generated-output products',
    previewLabel: 'Outcome demo',
    content: {
      templateId: 'ai-tool',
      sectionOrder: ['benefits', 'problemSolution', 'howItWorks', 'testimonials', 'faq'],
      headline: 'Turn one messy task into an AI-powered workflow',
      headlineVariantB: 'Be first to test the AI workflow built for this exact job',
      subheadline: 'Pitch the transformation clearly, show what the AI produces, and collect early users who want to try it first.',
      problemStatement: 'People do not need another generic AI chat box. They need a tool that understands one high-friction job and gets it done faster.',
      solutionSummary: 'Your AI tool turns inputs into useful outputs through a focused workflow that early users can understand immediately.',
      benefits: ['Show the before-and-after clearly', 'Collect users with a specific AI use case', 'Learn what output quality buyers expect'],
      howItWorks: ['Upload or describe the task', 'Review the generated result', 'Join the beta and shape the workflow'],
      trustItems: ['AI workflow', 'Early beta', 'No generic prompts'],
      socialProof: 'Designed for founders validating an AI product around one repeatable, valuable task.',
      ctaText: 'Join the AI beta',
      emailPlaceholder: 'Email for beta access',
      theme: 'dark',
      accentColor: 'sky',
      layout: 'split',
      textAlign: 'left',
      typography: {
        headingFamily: WAITLIST_FONT_PRESETS[0].value,
        bodyFamily: WAITLIST_FONT_PRESETS[4].value,
        headingWeight: 900,
        bodyWeight: 500,
        headingSize: 58,
        subheadingSize: 22,
        bodySize: 16,
        letterSpacing: 0,
      },
      colors: {
        ...dark,
        pageBackground: '#020617',
        sectionBackground: '#0f172a',
        buttonBackground: '#38bdf8',
        buttonText: '#03151f',
      },
      spacing: { sectionPaddingY: 82, contentMaxWidth: 1180, cardRadius: 24 },
    },
  },
  {
    id: 'mobile-app',
    name: 'App Launch',
    productType: 'Mobile App',
    description: 'A clean consumer app page built around the daily moment, the emotional payoff, and invite requests.',
    bestFor: 'Consumer apps, wellness apps, utility apps',
    previewLabel: 'Daily habit',
    content: {
      templateId: 'mobile-app',
      sectionOrder: ['howItWorks', 'benefits', 'problemSolution', 'testimonials', 'faq'],
      headline: 'A simpler app for the moment your users keep struggling with',
      headlineVariantB: 'Join the first users shaping this mobile experience',
      subheadline: 'Describe the recurring moment, promise one clear improvement, and invite users into the first release.',
      problemStatement: 'Your audience already has the problem on their phone, but the current options feel too complicated, too noisy, or too generic.',
      solutionSummary: 'Your app gives them a focused experience that fits into the moment when they need help most.',
      benefits: ['Make the daily use case easy to picture', 'Invite high-intent early users', 'Test which habit loop is worth building'],
      howItWorks: ['Spot the moment', 'Join the first release', 'Give feedback as the app takes shape'],
      trustItems: ['Mobile-first', 'Invite access', 'Built around one habit'],
      socialProof: 'For founders validating a mobile product before investing in the full app build.',
      ctaText: 'Get app invite',
      emailPlaceholder: 'Where should we send your invite?',
      theme: 'light',
      accentColor: 'rose',
      layout: 'split',
      textAlign: 'left',
      typography: {
        headingFamily: WAITLIST_FONT_PRESETS[2].value,
        bodyFamily: WAITLIST_FONT_PRESETS[4].value,
        headingWeight: 800,
        bodyWeight: 500,
        headingSize: 52,
        subheadingSize: 20,
        bodySize: 16,
        letterSpacing: 0,
      },
      colors: {
        ...light,
        pageBackground: '#fff7fb',
        sectionBackground: '#ffffff',
        buttonBackground: '#be123c',
        buttonText: '#ffffff',
        borderColor: '#fecdd3',
      },
      spacing: { sectionPaddingY: 72, contentMaxWidth: 1080, cardRadius: 28 },
    },
  },
  {
    id: 'marketplace',
    name: 'Marketplace Match',
    productType: 'Marketplace',
    description: 'A two-sided launch page that makes the supply and demand wedge obvious from the first screen.',
    bestFor: 'Marketplaces, matching platforms, service networks',
    previewLabel: 'Two-sided wedge',
    content: {
      templateId: 'marketplace',
      sectionOrder: ['problemSolution', 'howItWorks', 'benefits', 'faq', 'testimonials'],
      headline: 'Bring the right buyers and providers into one focused market',
      headlineVariantB: 'Join the first network built around this underserved match',
      subheadline: 'Explain who you connect, why the current market is broken, and collect early demand from both sides.',
      problemStatement: 'The people who need the solution and the people who can provide it are scattered across channels that create friction and low trust.',
      solutionSummary: 'Your marketplace creates a focused place to discover, evaluate, and start the right relationship faster.',
      benefits: ['Clarify both sides of the market', 'Collect qualified early demand', 'Validate the matching wedge before building liquidity'],
      howItWorks: ['Tell us which side you are on', 'Join the first curated group', 'Help shape the matching experience'],
      trustItems: ['Curated network', 'Founder-screened', 'Early market signal'],
      socialProof: 'Built for marketplace founders who need demand proof before building a full platform.',
      ctaText: 'Join the first market',
      emailPlaceholder: 'Email for early access',
      collectFirstName: true,
      theme: 'light',
      accentColor: 'emerald',
      layout: 'centered',
      textAlign: 'center',
      typography: {
        headingFamily: WAITLIST_FONT_PRESETS[1].value,
        bodyFamily: WAITLIST_FONT_PRESETS[3].value,
        headingWeight: 800,
        bodyWeight: 500,
        headingSize: 50,
        subheadingSize: 21,
        bodySize: 16,
        letterSpacing: 0,
      },
      colors: {
        ...light,
        pageBackground: '#f6fbf8',
        sectionBackground: '#ffffff',
        buttonBackground: '#047857',
        buttonText: '#ffffff',
        borderColor: '#bbf7d0',
      },
      spacing: { sectionPaddingY: 78, contentMaxWidth: 1120, cardRadius: 14 },
    },
  },
  {
    id: 'community',
    name: 'Community Circle',
    productType: 'Community',
    description: 'A warm credibility-first page for gathering founding members around a shared problem or identity.',
    bestFor: 'Founder communities, memberships, private groups',
    previewLabel: 'Founding members',
    content: {
      templateId: 'community',
      sectionOrder: ['testimonials', 'problemSolution', 'benefits', 'howItWorks', 'faq'],
      headline: 'Join the founding group solving this together',
      headlineVariantB: 'Become one of the first members shaping this community',
      subheadline: 'Frame the shared challenge, the promise of the group, and why early members should raise their hand now.',
      problemStatement: 'Your audience is trying to solve the problem alone, piecing together advice from scattered threads, calls, and generic content.',
      solutionSummary: 'Your community gives them a focused place to learn, compare notes, and move faster with people facing the same challenge.',
      benefits: ['Position the community around a real shared pain', 'Collect founding members with strong fit', 'Show why the group matters before the platform exists'],
      howItWorks: ['Join the founding list', 'Tell us what you need most', 'Get invited into the first cohort'],
      trustItems: ['Founder-led', 'Curated members', 'Early cohort'],
      socialProof: 'For community founders validating whether a clear group deserves to exist.',
      ctaText: 'Join founding members',
      emailPlaceholder: 'Email for cohort invite',
      collectFirstName: true,
      theme: 'light',
      accentColor: 'orange',
      layout: 'centered',
      textAlign: 'center',
      typography: {
        headingFamily: WAITLIST_FONT_PRESETS[3].value,
        bodyFamily: WAITLIST_FONT_PRESETS[4].value,
        headingWeight: 800,
        bodyWeight: 500,
        headingSize: 49,
        subheadingSize: 20,
        bodySize: 16,
        letterSpacing: 0,
      },
      colors: {
        ...light,
        pageBackground: '#fffaf4',
        sectionBackground: '#ffffff',
        buttonBackground: '#c2410c',
        buttonText: '#ffffff',
        borderColor: '#fed7aa',
      },
      spacing: { sectionPaddingY: 74, contentMaxWidth: 1040, cardRadius: 22 },
    },
  },
  {
    id: 'creator-tool',
    name: 'Creator Stack',
    productType: 'Creator Tool',
    description: 'A sharp product-led page for creator workflows, content tools, and monetization utilities.',
    bestFor: 'Creator SaaS, media tools, audience products',
    previewLabel: 'Creator workflow',
    content: {
      templateId: 'creator-tool',
      sectionOrder: ['benefits', 'howItWorks', 'problemSolution', 'testimonials', 'faq'],
      headline: 'Give creators one sharper way to produce, publish, or monetize',
      headlineVariantB: 'Be first to try the tool built for modern creators',
      subheadline: 'Show the workflow you improve, the output creators get, and the reason they should join before launch.',
      problemStatement: 'Creators are juggling too many tools while trying to stay consistent, grow an audience, and turn attention into revenue.',
      solutionSummary: 'Your creator tool simplifies one high-value workflow so creators can move from idea to published output faster.',
      benefits: ['Make the creator outcome tangible', 'Capture early users with real audience pain', 'Learn what workflow saves the most time'],
      howItWorks: ['Bring your current workflow', 'Try the focused beta', 'Shape the creator toolkit before launch'],
      trustItems: ['Creator-first', 'Workflow beta', 'Built for output'],
      socialProof: 'For founders testing a tool that helps creators produce better work with less friction.',
      ctaText: 'Join creator beta',
      emailPlaceholder: 'Creator email',
      theme: 'dark',
      accentColor: 'rose',
      layout: 'split',
      textAlign: 'left',
      typography: {
        headingFamily: WAITLIST_FONT_PRESETS[2].value,
        bodyFamily: WAITLIST_FONT_PRESETS[4].value,
        headingWeight: 900,
        bodyWeight: 500,
        headingSize: 56,
        subheadingSize: 21,
        bodySize: 16,
        letterSpacing: 0,
      },
      colors: {
        ...dark,
        pageBackground: '#160815',
        sectionBackground: '#241224',
        buttonBackground: '#fb7185',
        buttonText: '#2a0712',
        borderColor: '#4c1d3f',
      },
      spacing: { sectionPaddingY: 80, contentMaxWidth: 1140, cardRadius: 12 },
    },
  },
  {
    id: 'ecommerce',
    name: 'Commerce Drop',
    productType: 'Ecommerce',
    description: 'A polished pre-order style page for product drops, new brands, and early buyer interest.',
    bestFor: 'Consumer products, ecommerce brands, physical product drops',
    previewLabel: 'Product drop',
    content: {
      templateId: 'ecommerce',
      sectionOrder: ['benefits', 'problemSolution', 'testimonials', 'howItWorks', 'faq'],
      headline: 'Reserve early access to the product drop',
      headlineVariantB: 'Get first access before the product goes public',
      subheadline: 'Make the product feel real, explain why it matters, and collect early buyers before committing to inventory.',
      problemStatement: 'Customers want a better option, but founders need proof of real demand before ordering stock, building packaging, or scaling production.',
      solutionSummary: 'Your waitlist turns product interest into a measurable launch signal before the first full production run.',
      benefits: ['Test product positioning before inventory risk', 'Collect early buyers and launch advocates', 'Learn which benefits drive purchase intent'],
      howItWorks: ['Join the early list', 'Get launch updates first', 'Receive the first drop invitation'],
      trustItems: ['Limited first drop', 'Early access', 'Founder-built'],
      socialProof: 'For ecommerce founders validating a product drop before investing heavily in production.',
      ctaText: 'Reserve early access',
      emailPlaceholder: 'Email for drop access',
      collectFirstName: true,
      theme: 'light',
      accentColor: 'sky',
      layout: 'split',
      textAlign: 'left',
      typography: {
        headingFamily: WAITLIST_FONT_PRESETS[0].value,
        bodyFamily: WAITLIST_FONT_PRESETS[3].value,
        headingWeight: 800,
        bodyWeight: 500,
        headingSize: 53,
        subheadingSize: 20,
        bodySize: 16,
        letterSpacing: 0,
      },
      colors: {
        ...light,
        pageBackground: '#f7fbff',
        sectionBackground: '#ffffff',
        buttonBackground: '#0369a1',
        buttonText: '#ffffff',
        borderColor: '#bae6fd',
      },
      spacing: { sectionPaddingY: 70, contentMaxWidth: 1120, cardRadius: 8 },
    },
  },
  {
    id: 'b2b-service',
    name: 'Service Proof',
    productType: 'B2B Service',
    description: 'A credibility-heavy page for validating a productized service or advisory offer before scaling delivery.',
    bestFor: 'Agencies, productized services, expert-led offers',
    previewLabel: 'Expert offer',
    content: {
      templateId: 'b2b-service',
      sectionOrder: ['problemSolution', 'testimonials', 'benefits', 'howItWorks', 'faq'],
      headline: 'Validate the service offer before building the full operation',
      headlineVariantB: 'Get first access to the productized service built for this outcome',
      subheadline: 'Explain the business problem, show the concrete outcome, and collect leads who want the first delivery slots.',
      problemStatement: 'Companies know the problem matters, but broad agencies and generic consultants make the first step feel expensive and unclear.',
      solutionSummary: 'Your productized service gives buyers a specific outcome, clear scope, and a lower-risk way to get help.',
      benefits: ['Position the service around one measurable result', 'Collect qualified leads before building delivery capacity', 'Learn which promise buyers trust enough to book'],
      howItWorks: ['Join the early list', 'Share the problem you want solved', 'Get invited into first delivery slots'],
      trustItems: ['Founder-led', 'Productized scope', 'Limited first slots'],
      socialProof: 'For founders turning expertise into a focused service offer before building a larger operation.',
      ctaText: 'Request first slot',
      emailPlaceholder: 'Business email',
      collectFirstName: true,
      theme: 'dark',
      accentColor: 'emerald',
      layout: 'centered',
      textAlign: 'center',
      typography: {
        headingFamily: WAITLIST_FONT_PRESETS[3].value,
        bodyFamily: WAITLIST_FONT_PRESETS[4].value,
        headingWeight: 800,
        bodyWeight: 500,
        headingSize: 51,
        subheadingSize: 20,
        bodySize: 16,
        letterSpacing: 0,
      },
      colors: {
        ...dark,
        pageBackground: '#071411',
        sectionBackground: '#10201b',
        buttonBackground: '#34d399',
        buttonText: '#052e22',
        borderColor: '#1f5f4d',
      },
      spacing: { sectionPaddingY: 76, contentMaxWidth: 1060, cardRadius: 16 },
    },
  },
];

export function getWaitlistTemplate(templateId?: WaitlistTemplateId): WaitlistTemplateDefinition {
  return WAITLIST_TEMPLATE_LIBRARY.find((template) => template.id === templateId) ?? WAITLIST_TEMPLATE_LIBRARY[0];
}

export function createWaitlistContentFromTemplate(templateId: WaitlistTemplateId, productName?: string): Partial<WaitlistContent> {
  const template = getWaitlistTemplate(templateId);
  const name = productName?.trim();
  return {
    ...template.content,
    templateId,
    sectionOrder: template.content.sectionOrder ?? WAITLIST_SECTION_ORDER,
    ...(name ? { headline: template.content.headline?.replace('your', name) } : {}),
  };
}
