#!/bin/bash
# Quick Setup Guide for Comment Box Storage

echo "======================================"
echo "Comment Box Storage Setup Guide"
echo "======================================"
echo ""
echo "Follow these steps to complete the setup:"
echo ""
echo "1. Go to your Supabase Dashboard"
echo "   URL: https://supabase.com/dashboard"
echo ""
echo "2. Select your project: creatives-takeover"
echo ""
echo "3. Navigate to: Storage (in left sidebar)"
echo ""
echo "4. Option A - Automatic (Recommended):"
echo "   - Go to SQL Editor"
echo "   - Click 'New Query'"
echo "   - Copy and paste contents of: setup-storage-buckets.sql"
echo "   - Click 'Run' button"
echo "   - Verify no errors appear"
echo ""
echo "5. Option B - Manual:"
echo "   - Click 'New Bucket'"
echo "   - Create bucket: comment-images (Public: YES)"
echo "   - Create bucket: comment-videos (Public: YES)"
echo "   - Create bucket: comment-audio (Public: YES)"
echo ""
echo "6. Verify buckets exist:"
echo "   - You should see three buckets in Storage"
echo "   - Each should show 'Public' badge"
echo ""
echo "7. Test the comment box:"
echo "   - Go to Community tab in your app"
echo "   - Try uploading an image"
echo "   - Try uploading a video"
echo "   - Try uploading an audio file"
echo ""
echo "======================================"
echo "If you encounter any issues:"
echo "- Check COMMENT_BOX_IMPLEMENTATION.md"
echo "- Look at Troubleshooting section"
echo "======================================"
