import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { Sparkles, TrendingUp, Target, DollarSign, Lightbulb } from 'lucide-react';

interface ChatbotReportCardProps {
  reportType: string;
  reportData: any;
  feedbackCategories?: string[];
}

const REPORT_TYPE_ICONS = {
  business_plan: Target,
  market_analysis: TrendingUp,
  financial_plan: DollarSign,
  conversation: Lightbulb,
  full_report: Sparkles,
};

const REPORT_TYPE_LABELS = {
  business_plan: 'Business Plan',
  market_analysis: 'Market Analysis',
  financial_plan: 'Financial Plan',
  conversation: 'AI Conversation',
  full_report: 'Complete Report',
};

const CATEGORY_LABELS: Record<string, string> = {
  market_validation: '🎯 Market Validation',
  strategy: '🚀 Strategy',
  financial: '💰 Financial',
  improvement: '💡 Improvements',
  partnerships: '🤝 Partners',
  general: '💬 General',
};

export const ChatbotReportCard = ({ reportType, reportData, feedbackCategories = [] }: ChatbotReportCardProps) => {
  const Icon = REPORT_TYPE_ICONS[reportType as keyof typeof REPORT_TYPE_ICONS] || Sparkles;
  const label = REPORT_TYPE_LABELS[reportType as keyof typeof REPORT_TYPE_LABELS] || 'AI Report';

  return (
    <Card className="p-4 space-y-4 bg-gradient-to-br from-primary/5 to-transparent border-primary/20">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="p-2 rounded-lg bg-primary/10">
            <Icon className="h-5 w-5 text-primary" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              <span className="text-sm font-medium">AI-Generated {label}</span>
            </div>
            <p className="text-xs text-muted-foreground">
              Generated by BizMap AI
            </p>
          </div>
        </div>
      </div>

      {/* Feedback Categories */}
      {feedbackCategories.length > 0 && (
        <div className="space-y-2">
          <p className="text-sm font-medium">Feedback Requested:</p>
          <div className="flex flex-wrap gap-2">
            {feedbackCategories.map((category) => (
              <Badge key={category} variant="secondary" className="text-xs">
                {CATEGORY_LABELS[category] || category}
              </Badge>
            ))}
          </div>
        </div>
      )}

      {/* Report Highlights */}
      {reportData && (
        <div className="space-y-3 pt-2 border-t">
          {reportData.industry && (
            <div className="flex items-center gap-2 text-sm">
              <span className="font-medium">Industry:</span>
              <Badge variant="outline">{reportData.industry}</Badge>
            </div>
          )}
          
          {reportData.business_stage && (
            <div className="flex items-center gap-2 text-sm">
              <span className="font-medium">Stage:</span>
              <Badge variant="outline">{reportData.business_stage}</Badge>
            </div>
          )}
          
          {reportData.key_points && Array.isArray(reportData.key_points) && (
            <div className="space-y-1">
              <p className="text-sm font-medium">Key Points:</p>
              <ul className="text-sm text-muted-foreground space-y-1 ml-4">
                {reportData.key_points.slice(0, 3).map((point: string, idx: number) => (
                  <li key={idx}>• {point}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      {/* Call to Action */}
      <div className="pt-2 border-t">
        <p className="text-sm text-muted-foreground italic">
          💬 Share your thoughts and feedback below to help improve this business plan
        </p>
      </div>
    </Card>
  );
};
