import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, ArrowRight, Check, Loader2, Save, ShieldCheck, Wallet } from 'lucide-react';
import Navigation from '@/components/Navigation';
import { AccountWallpaper } from '@/components/AccountWallpaper';
import { CofounderListingCard } from '@/components/cofounder-marketplace/CofounderListingCard';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useAuth } from '@/contexts/AuthContext';
import { useCredits } from '@/hooks/useCredits';
import { cofounderKeys, getMyCofounderListing, publishCofounderListing, saveCofounderListingDraft, updateCofounderListing } from '@/lib/cofounderMarketplace';
import { trackCofounderMarketplaceEvent } from '@/lib/cofounderMarketplaceAnalytics';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { COFOUNDER_SKILLS, COFOUNDER_STAGES, COFOUNDER_VALUES, createEmptyCofounderListing, validateCofounderListing, type CofounderListingInput, type CofounderWorkMode } from '@/types/cofounderMarketplace';

const STEPS = ['Intent', 'Compatibility', 'Logistics', 'Preview'];

function ChoiceChips({ values, selected, onChange }: { values: readonly string[]; selected: string[]; onChange: (next: string[]) => void }) {
  const toggle = (value: string) => onChange(selected.includes(value) ? selected.filter((item) => item !== value) : [...selected, value]);
  return <div className="flex flex-wrap gap-2">{values.map((value)=><Button key={value} type="button" size="sm" variant={selected.includes(value)?'default':'outline'} className="h-10" onClick={()=>toggle(value)} aria-pressed={selected.includes(value)}>{selected.includes(value)&&<Check className="mr-1 h-3.5 w-3.5" />}{value}</Button>)}</div>;
}

export default function CofounderListingEditorPage() {
  const { user } = useAuth();
  const { postId } = useParams();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { totalAvailable, refreshBalance } = useCredits();
  const timezone = useMemo(() => Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC', []);
  const [step, setStep] = useState(0);
  const [form, setForm] = useState<CofounderListingInput>(() => createEmptyCofounderListing(timezone));
  const [profile, setProfile] = useState<{ completion: number; emailVerified: boolean; startupName: string; stage: string; location: string } | null>(null);
  const storageKey = user ? `cofounder-listing-draft-v2:${user.id}` : '';
  const existingQuery = useQuery({ queryKey: [...cofounderKeys.mine(user?.id), postId], queryFn: () => getMyCofounderListing(user!.id, postId), enabled: Boolean(user && postId) });

  useEffect(() => {
    if (!user) return;
    void Promise.all([(supabase as any).from('profiles').select('profile_completion_percentage,startup_name,startup_stage,location').eq('id',user.id).single(), supabase.auth.getUser()]).then(([profileResult, authResult]) => {
      const row = profileResult.data;
      setProfile({ completion: row?.profile_completion_percentage ?? 0, emailVerified: Boolean(authResult.data.user?.email_confirmed_at), startupName: row?.startup_name ?? '', stage: row?.startup_stage ?? 'idea', location: row?.location ?? '' });
      setForm((current)=>({...current,startupName:current.startupName||row?.startup_name||'',startupStage:current.startupStage||row?.startup_stage||'idea',location:current.location||row?.location||''}));
    });
  }, [user]);
  useEffect(() => {
    if (existingQuery.data) {
      const item=existingQuery.data; setForm({ id:item.id,listingType:item.listingType,headline:item.headline,summary:item.summary,startupName:item.startupName??'',startupStage:item.startupStage??'idea',industries:item.industries,skillsOffered:item.skillsOffered,skillsSought:item.skillsSought,commitment:item.commitment??'',timezone:item.timezone,workMode:item.workMode,location:item.location??'',experienceLevel:item.experienceLevel??'',values:item.values,equityRange:item.equityRange??'' });
    } else if (!postId && storageKey) { const saved=localStorage.getItem(storageKey); if(saved){try{setForm({...createEmptyCofounderListing(timezone),...JSON.parse(saved)});}catch{localStorage.removeItem(storageKey);}} }
  }, [existingQuery.data,postId,storageKey,timezone]);
  useEffect(()=>{if(storageKey)localStorage.setItem(storageKey,JSON.stringify(form));},[form,storageKey]);
  useEffect(()=>{trackCofounderMarketplaceEvent('cofounder_listing_started',{mode:postId?'edit':'create'});},[postId]);

  const draftMutation=useMutation({mutationFn:()=>saveCofounderListingDraft(form),onSuccess:()=>toast.success('Draft saved.'),onError:(error:Error)=>toast.error(error.message)});
  const publishMutation=useMutation({mutationFn:async()=>{if(postId&&existingQuery.data?.status==='active')return updateCofounderListing(postId,form);return publishCofounderListing({...form,id:undefined},`cofounder-publish:${user!.id}:${crypto.randomUUID()}`);},onSuccess:async(listing)=>{localStorage.removeItem(storageKey);await refreshBalance();await queryClient.invalidateQueries({queryKey:cofounderKeys.all});trackCofounderMarketplaceEvent('cofounder_listing_published',{listing_id:listing.id,listing_type:listing.listingType});toast.success(postId?'Listing updated.':'Listing published.');navigate('/co-founder?tab=mine');},onError:(error:Error)=>toast.error(error.message)});
  const update=<K extends keyof CofounderListingInput>(key:K,value:CofounderListingInput[K])=>setForm((current)=>({...current,[key]:value}));
  const errors=validateCofounderListing(form); const trusted=Boolean(profile?.emailVerified&&profile.completion>=60); const isEdit=Boolean(postId&&existingQuery.data?.status==='active');
  const next=async()=>{if(user&&!postId)await draftMutation.mutateAsync();setStep((value)=>Math.min(3,value+1));};
  if(!user)return <div className="min-h-screen bg-background"><Navigation/><main className="container mx-auto px-6 pt-40 text-center"><h1 className="text-3xl font-bold">Sign in to create a listing</h1><Button className="mt-6" onClick={()=>navigate(`/login?return=${encodeURIComponent('/co-founder/create')}`)}>Sign in</Button></main></div>;
  return <div className="relative min-h-screen overflow-hidden"><AccountWallpaper/><div className="relative z-10"><Navigation/><main className="container mx-auto max-w-4xl px-4 pb-16 pt-header-offset sm:px-6"><header className="py-8"><Badge variant="secondary" className="mb-3">Co-founder marketplace</Badge><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">{isEdit?'Update your listing':'Create a listing people can act on'}</h1><p className="mt-2 text-muted-foreground">One clear listing, explainable matches, and qualified introductions.</p></header><div className="mb-6 grid grid-cols-4 gap-2" aria-label={`Step ${step+1} of ${STEPS.length}`}>{STEPS.map((label,index)=><div key={label}><div className={`h-1.5 rounded-full ${index<=step?'bg-primary':'bg-muted'}`}/><p className="mt-2 text-xs text-muted-foreground">{index+1}. {label}</p></div>)}</div>
    {!trusted&&profile&&<Alert className="mb-6 border-amber-500/40 bg-amber-500/5"><ShieldCheck className="h-4 w-4"/><AlertTitle>Complete trust requirements before publishing</AlertTitle><AlertDescription>{!profile.emailVerified?'Verify your email. ':''}{profile.completion<60?`Your profile is ${profile.completion}% complete; reach 60%.`:''} You can continue and save a draft now.</AlertDescription></Alert>}
    <Card><CardHeader><CardTitle>{STEPS[step]}</CardTitle><CardDescription>Step {step+1} of {STEPS.length}</CardDescription></CardHeader><CardContent className="space-y-6">
      {step===0&&<><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>update('listingType','building')} className={`min-h-28 rounded-xl border-2 p-4 text-left ${form.listingType==='building'?'border-primary bg-primary/5':'border-border'}`}><strong>I’m building and seeking</strong><p className="mt-2 text-sm text-muted-foreground">Present your startup and the co-founder capabilities you need.</p></button><button type="button" onClick={()=>update('listingType','joining')} className={`min-h-28 rounded-xl border-2 p-4 text-left ${form.listingType==='joining'?'border-primary bg-primary/5':'border-border'}`}><strong>I’m open to joining</strong><p className="mt-2 text-sm text-muted-foreground">Show what you bring and the opportunity you want to join.</p></button></div><div className="space-y-2"><Label htmlFor="headline">Headline</Label><Input id="headline" maxLength={100} value={form.headline} onChange={(e)=>update('headline',e.target.value)} placeholder={form.listingType==='building'?'Seeking a technical co-founder for climate SaaS':'Product leader open to joining an ambitious B2B startup'}/><p className="text-xs text-muted-foreground">{form.headline.length}/100</p></div><div className="space-y-2"><Label htmlFor="summary">Summary</Label><Textarea id="summary" maxLength={1200} className="min-h-40" value={form.summary} onChange={(e)=>update('summary',e.target.value)} placeholder="Describe the problem, progress, your contribution, and what a strong partnership looks like."/><p className="text-xs text-muted-foreground">{form.summary.length}/1,200 · minimum 80</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="startup-name">Startup name (optional)</Label><Input id="startup-name" value={form.startupName} onChange={(e)=>update('startupName',e.target.value)}/></div><div className="space-y-2"><Label htmlFor="stage">Startup stage</Label><select id="stage" className="h-11 w-full rounded-md border bg-background px-3" value={form.startupStage} onChange={(e)=>update('startupStage',e.target.value)}>{COFOUNDER_STAGES.map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</select></div></div></>}
      {step===1&&<><div><Label className="mb-3 block">Skills you offer</Label><ChoiceChips values={COFOUNDER_SKILLS} selected={form.skillsOffered} onChange={(value)=>update('skillsOffered',value)}/></div><div><Label className="mb-3 block">Skills you want in a co-founder</Label><ChoiceChips values={COFOUNDER_SKILLS} selected={form.skillsSought} onChange={(value)=>update('skillsSought',value)}/></div><div><Label className="mb-3 block">Founder values</Label><ChoiceChips values={COFOUNDER_VALUES} selected={form.values} onChange={(value)=>update('values',value)}/></div><div className="space-y-2"><Label htmlFor="industries">Industries</Label><Input id="industries" value={form.industries.join(', ')} onChange={(e)=>update('industries',e.target.value.split(',').map((value)=>value.trim()).filter(Boolean).slice(0,8))} placeholder="FinTech, B2B SaaS"/><p className="text-xs text-muted-foreground">Separate industries with commas.</p></div></>}
      {step===2&&<><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="commitment">Commitment</Label><select id="commitment" className="h-11 w-full rounded-md border bg-background px-3" value={form.commitment} onChange={(e)=>update('commitment',e.target.value)}><option value="">Select commitment</option><option value="Full-time">Full-time</option><option value="Part-time">Part-time</option><option value="Evenings/weekends">Evenings/weekends</option><option value="Flexible">Flexible</option></select></div><div className="space-y-2"><Label htmlFor="mode">Work mode</Label><select id="mode" className="h-11 w-full rounded-md border bg-background px-3" value={form.workMode} onChange={(e)=>update('workMode',e.target.value as CofounderWorkMode)}><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="in_person">In person</option><option value="flexible">Flexible</option></select></div><div className="space-y-2"><Label htmlFor="timezone">Timezone</Label><Input id="timezone" value={form.timezone} onChange={(e)=>update('timezone',e.target.value)} placeholder="America/Bogota"/></div><div className="space-y-2"><Label htmlFor="location">Location</Label><Input id="location" value={form.location} onChange={(e)=>update('location',e.target.value)} placeholder="Bogotá, Colombia"/></div><div className="space-y-2"><Label htmlFor="experience">Experience level</Label><select id="experience" className="h-11 w-full rounded-md border bg-background px-3" value={form.experienceLevel} onChange={(e)=>update('experienceLevel',e.target.value)}><option value="">Not specified</option><option value="First-time founder">First-time founder</option><option value="Experienced operator">Experienced operator</option><option value="Repeat founder">Repeat founder</option></select></div><div className="space-y-2"><Label htmlFor="equity">Equity range (optional)</Label><Input id="equity" value={form.equityRange} onChange={(e)=>update('equityRange',e.target.value)} placeholder="Negotiable"/></div></div></>}
      {step===3&&<><CofounderListingCard listing={{...form,id:'preview',userId:user.id,status:'active',publishedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+30*86400000).toISOString(),lastActiveAt:new Date().toISOString(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),author:{fullName:user.user_metadata?.full_name??'You',username:null,avatarUrl:user.user_metadata?.avatar_url??null,emailVerified:profile?.emailVerified,profileComplete:(profile?.completion??0)>=60},isOwner:true}} authenticated/><Card className="bg-muted/30"><CardContent className="flex items-start gap-3 p-4"><Wallet className="mt-0.5 h-5 w-5 text-primary"/><div><p className="font-semibold">{isEdit?'Editing is free':'Publishing costs 5 credits'}</p><p className="text-sm text-muted-foreground">Available balance: {totalAvailable} credits. {isEdit?'Your expiry date will not reset.':'Your listing stays active for 30 days; renewal costs 5 credits.'}</p></div></CardContent></Card>{errors.length>0&&<Alert variant="destructive"><AlertTitle>Complete the listing</AlertTitle><AlertDescription><ul className="mt-2 list-disc pl-5">{errors.map((error)=><li key={error}>{error}</li>)}</ul></AlertDescription></Alert>}</>}
      <div className="flex flex-wrap items-center justify-between gap-3 border-t pt-5"><Button type="button" variant="outline" disabled={step===0||draftMutation.isPending||publishMutation.isPending} onClick={()=>setStep((value)=>value-1)}><ArrowLeft className="mr-2 h-4 w-4"/>Back</Button><div className="flex gap-2">{!postId&&<Button type="button" variant="ghost" disabled={draftMutation.isPending} onClick={()=>draftMutation.mutate()}><Save className="mr-2 h-4 w-4"/>Save draft</Button>}{step<3?<Button type="button" disabled={draftMutation.isPending} onClick={()=>void next()}>Continue<ArrowRight className="ml-2 h-4 w-4"/></Button>:<Button type="button" disabled={errors.length>0||!trusted||publishMutation.isPending||(!isEdit&&totalAvailable<5)} onClick={()=>publishMutation.mutate()}>{publishMutation.isPending&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}{isEdit?'Save changes':'Publish · 5 credits'}</Button>}</div></div>
    </CardContent></Card></main></div></div>;
}
