import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {pgcrypto} from '@electric-sql/pglite/contrib/pgcrypto';
const owner='10000000-0000-0000-0000-000000000001',other='10000000-0000-0000-0000-000000000002',project='20000000-0000-0000-0000-000000000001';
test('workflow SQL enforces ownership, revisions, leases, immutable publishing and atomic charging',async t=>{
 const db=new PGlite({extensions:{pgcrypto}});
 try{
 await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;CREATE SCHEMA auth;CREATE SCHEMA extensions;CREATE EXTENSION pgcrypto WITH SCHEMA extensions;
 CREATE TABLE auth.users(id uuid PRIMARY KEY);INSERT INTO auth.users VALUES('${owner}'),('${other}');
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 CREATE FUNCTION auth.role() RETURNS text LANGUAGE sql AS $$ SELECT current_setting('request.jwt.claim.role',true) $$;
 GRANT USAGE ON SCHEMA auth TO authenticated;GRANT EXECUTE ON FUNCTION auth.uid(),auth.role() TO authenticated;
 CREATE TABLE mvp_projects(id uuid PRIMARY KEY,user_id uuid,title text,project_files jsonb,generated_code text,versions jsonb DEFAULT '[]',metadata jsonb,project_type text DEFAULT 'html_single',supabase_connection_id uuid,subdomain_slug text UNIQUE,deployment_url text,deployment_status text,updated_at timestamptz,search_indexing_requested boolean DEFAULT false,search_indexing_review_status text,seo_title text,seo_description text,seo_image_url text);
 CREATE TABLE mvp_builder_credit_reservations(id uuid PRIMARY KEY,user_id uuid,action_feature text,idempotency_key text,status text DEFAULT 'pending',metadata jsonb DEFAULT '{}');
 CREATE TABLE charges(id uuid PRIMARY KEY);
 CREATE FUNCTION finalize_mvp_builder_credit_reservation(p_reservation_id uuid,p_metadata jsonb) RETURNS jsonb LANGUAGE plpgsql AS $$ BEGIN INSERT INTO charges VALUES(p_reservation_id) ON CONFLICT DO NOTHING; RETURN '{"success":true}'::jsonb; END $$;
 INSERT INTO mvp_projects(id,user_id,title,project_files,metadata,supabase_connection_id,subdomain_slug,deployment_status) VALUES('${project}','${owner}','Example','[{"filename":"index.html","content":"legacy"}]','{"setupInput":{"workflow":{"version":1,"starter":"lead_capture","customer":"Buyers","task":"Subscribe","outcome":"Saved","features":["Form"]}}}','30000000-0000-0000-0000-000000000001','example','deployed');
 SELECT set_config('request.jwt.claim.sub','${owner}',false);
 `);
 await db.exec(readFileSync('supabase/migrations/20261001120000_mvp_workflow_tests.sql','utf8'));
 const call=async(sql,params=[])=> (await db.query(sql,params)).rows;
 await t.test('product briefs invalidate revisions without changing legacy project hashes',async()=>{
  const revision=(await call('SELECT mvp_workflow_revision(p) revision FROM mvp_projects p WHERE id=$1',[project]))[0].revision;
  await db.exec(readFileSync('supabase/migrations/20261001130000_mvp_build_brief_revision.sql','utf8'));
  assert.equal((await call('SELECT mvp_workflow_revision(p) revision FROM mvp_projects p WHERE id=$1',[project]))[0].revision,revision);
  await call("UPDATE mvp_projects SET metadata=jsonb_set(metadata,'{setupInput,buildBrief}',$2) WHERE id=$1",[project,{version:1,kind:'landing',delivery:'preview'}]);
  assert.notEqual((await call('SELECT mvp_workflow_revision(p) revision FROM mvp_projects p WHERE id=$1',[project]))[0].revision,revision);
  await call("UPDATE mvp_projects SET metadata=metadata #- '{setupInput,buildBrief}' WHERE id=$1",[project]);
 });
 await db.exec(readFileSync('supabase/migrations/20261001140000_mvp_managed_control.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/20261001141000_mvp_static_acceptance.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/20261001150000_mvp_saved_test_review.sql','utf8'));
 await db.exec(readFileSync('supabase/migrations/20261001160000_mvp_recovery_jobs.sql','utf8'));
 await t.test('included repairs bind paid source, cap attempts, checkpoint atomically and reject stale writes',async()=>{
  const pid='20000000-0000-0000-0000-000000000077',rid='40000000-0000-0000-0000-000000000077';
  const files=[{filename:'index.html',content:'broken'}];
  await call('INSERT INTO mvp_projects(id,user_id,project_files,metadata) VALUES($1,$2,$3,$4)',[pid,owner,files,{}]);
  await call("INSERT INTO mvp_builder_credit_reservations(id,user_id,action_feature,status,metadata) VALUES($1,$2,'APP_BUILDER_GENERATE','finalized',$3)",[rid,owner,{projectId:pid}]);
  await call('SELECT register_mvp_repair_budget($1,$2)',[rid,files]);
  const fail=async()=> (await call("INSERT INTO mvp_build_tests(project_id,user_id,revision,snapshot,status,assertions) SELECT id,user_id,mvp_workflow_revision(p),mvp_workflow_snapshot(p),'failed','{\"cleanup\":true,\"customer_task\":false}' FROM mvp_projects p WHERE id=$1 RETURNING id",[pid]))[0].id;
  let tid=await fail();
  await assert.rejects(call('SELECT claim_mvp_outcome_repair($1,$2)',[tid,other]),/test service/);
  let job=(await call('SELECT claim_mvp_outcome_repair($1,$2) job',[tid,owner]))[0].job;
  await assert.rejects(call('SELECT claim_mvp_outcome_repair($1,$2)',[tid,owner]),/already attempted/);
  const fixed=[{filename:'index.html',content:'fixed once'}];
  await call('SELECT apply_mvp_outcome_repair($1,$2)',[job.id,fixed]);
  assert.equal((await call('SELECT snapshot FROM mvp_edit_checkpoints WHERE project_id=$1',[pid]))[0].snapshot.project_files[0].content,'broken');
  assert.equal((await call('SELECT count(*)::int n FROM charges'))[0].n,0);
  tid=await fail();job=(await call('SELECT claim_mvp_outcome_repair($1,$2) job',[tid,owner]))[0].job;
  await call('UPDATE mvp_projects SET project_files=$2 WHERE id=$1',[pid,[{filename:'index.html',content:'concurrent user edit'}]]);
  await assert.rejects(call('SELECT apply_mvp_outcome_repair($1,$2)',[job.id,fixed]),/changed during repair/);
  await call("UPDATE mvp_outcome_repairs SET status='failed' WHERE id=$1",[job.id]);
  await call('UPDATE mvp_projects SET project_files=$2 WHERE id=$1',[pid,fixed]);
  tid=await fail();await assert.rejects(call('SELECT claim_mvp_outcome_repair($1,$2)',[tid,owner]),/No included repairs/);
  await db.exec('SET ROLE authenticated');
  await assert.rejects(call('SELECT register_mvp_repair_budget($1,$2)',[rid,files]),/permission denied/);
  await assert.rejects(call('SELECT apply_mvp_outcome_repair($1,$2)',[job.id,fixed]),/permission denied/);
  await db.exec('RESET ROLE');
 });
 await t.test('managed admission is owner-scoped, idempotent, budget-limited and private',async()=>{
  const managedId='20000000-0000-0000-0000-000000000088';
  await call('INSERT INTO mvp_projects(id,user_id) VALUES($1,$2)',[managedId,owner]);
  const manifest={version:1,persistence:true,profile:'private_records',schemaVersion:'1.0.0'};
  await assert.rejects(call('SELECT admit_mvp_managed_app($1,$2,$3,$4)',[managedId,other,'managed-org',manifest]),/not found/);
  await assert.rejects(call('SELECT admit_mvp_managed_app($1,$2,$3,$4)',[managedId,owner,'managed-org',manifest]),/invited/);
  await call('INSERT INTO mvp_managed_invites VALUES($1)',[owner]);
  await db.exec("UPDATE mvp_managed_pilot SET enabled=true,cost_observed_at=now()-interval '2 days'");
  await assert.rejects(call('SELECT admit_mvp_managed_app($1,$2,$3,$4)',[managedId,owner,'managed-org',manifest]),/forecast/);
  await db.exec('UPDATE mvp_managed_pilot SET cost_observed_at=now(),base_monthly_cents=19000');
  await assert.rejects(call('SELECT admit_mvp_managed_app($1,$2,$3,$4)',[managedId,owner,'managed-org',manifest]),/paused/);
  await db.exec('UPDATE mvp_managed_pilot SET base_monthly_cents=9000');
  for(let i=0;i<2;i++)await call('SELECT admit_mvp_managed_app($1,$2,$3,$4)',[managedId,owner,'managed-org',manifest]);
  assert.equal((await call('SELECT count(*)::int n FROM mvp_managed_apps'))[0].n,1);
  await call("UPDATE mvp_managed_apps SET status='ready',public_runtime=$2 WHERE project_id=$1",[managedId,{url:'https://managedexample.supabase.co',publicKey:'server-owned-public-key'}]);
  await call('UPDATE mvp_projects SET project_files=$2,metadata=$3 WHERE id=$1',[managedId,[{filename:'index.html',content:'Managed notes'}],{setupInput:{managedApp:true,workflowPublicKey:'forged-browser-key',workflow:{version:1,starter:'customer_portal',customer:'Writers',task:'Save a note',outcome:'Reload it',features:['Notes']},buildBrief:{version:1,kind:'app',delivery:'connected',idea:'Private notes'}}}]);
  const managedTest=(await call('SELECT request_mvp_workflow_test($1) id',[managedId]))[0].id;
  const snapshot=(await call('SELECT snapshot FROM mvp_build_tests WHERE id=$1',[managedTest]))[0].snapshot;
  assert.equal(snapshot.publicKey,'server-owned-public-key');
  assert.equal(snapshot.backend.projectUrl,'https://managedexample.supabase.co');
  await call("UPDATE mvp_build_tests SET status='failed' WHERE id=$1",[managedTest]);
  await call("UPDATE mvp_managed_apps SET status='schema' WHERE project_id=$1",[managedId]);
  await assert.rejects(call('SELECT request_mvp_workflow_test($1)',[managedId]),/Finish managed/);
  assert.equal((await call('SELECT * FROM claim_mvp_managed_app($1)',[managedId])).length,1);
  assert.equal((await call('SELECT * FROM claim_mvp_managed_app($1)',[managedId])).length,0);
  await call('UPDATE mvp_managed_apps SET lease=NULL,lease_until=NULL WHERE project_id=$1',[managedId]);
  assert.equal((await call('SELECT * FROM claim_mvp_managed_app($1)',[managedId])).length,0);
  await call("UPDATE mvp_managed_apps SET next_attempt_at=now()-interval '1 minute',attempts=40 WHERE project_id=$1",[managedId]);
  assert.equal((await call('SELECT * FROM claim_mvp_managed_app($1)',[managedId])).length,0);
  assert.equal((await call('SELECT status FROM mvp_managed_apps WHERE project_id=$1',[managedId]))[0].status,'review');
  await call("UPDATE mvp_managed_apps SET status='ready' WHERE project_id=$1",[managedId]);
  await db.exec('SET ROLE authenticated');
  await assert.rejects(call('SELECT * FROM mvp_managed_secrets'),/permission denied/);
  await assert.rejects(call('SELECT admit_mvp_managed_app($1,$2,$3,$4)',[managedId,owner,'managed-org',manifest]),/permission denied/);
  await db.exec('RESET ROLE');
 });
 await t.test('static CTA pages queue and pass without a database; missing outcome still fails',async()=>{
  const staticId='20000000-0000-0000-0000-000000000099';
  await call('INSERT INTO mvp_projects(id,user_id,project_files,metadata) VALUES($1,$2,$3,$4)',[staticId,owner,[{filename:'index.html',content:'<a href="https://example.com" data-testid="ct-cta">Buy</a>'}],{setupInput:{buildBrief:{version:1,kind:'landing',idea:'A portfolio website',task:'View my work',features:['Gallery','Call to action'],ctaUrl:'https://example.com',delivery:'preview'}}}]);
  const testId=(await call('SELECT request_mvp_workflow_test($1) id',[staticId]))[0].id;
  assert.equal((await call('SELECT * FROM claim_mvp_workflow_test()')).length,0);
  const claimed=(await call("SELECT * FROM claim_mvp_workflow_test(ARRAY['static_landing'])"))[0];
  await call('SELECT finish_mvp_workflow_test($1,$2,$3,$4,null)',[testId,claimed.lease,{customer_task:true,cta_navigation:true,no_runtime_errors:true,responsive_ui:true,cleanup:true},[{filename:'index.html',content:'Built portfolio'}]]);
  assert.equal((await call('SELECT status FROM mvp_build_tests WHERE id=$1',[testId]))[0].status,'passed');
  assert.equal((await call('SELECT * FROM current_mvp_workflow_test($1)',[staticId]))[0].id,testId);
  assert.equal((await call('SELECT review_mvp_test_artifact($1) artifact',[testId]))[0].artifact[0].content,'Built portfolio');
  await db.exec(`SELECT set_config('request.jwt.claim.sub','${other}',false);`);
  await assert.rejects(call('SELECT * FROM current_mvp_workflow_test($1)',[staticId]),/not found/);
  await assert.rejects(call('SELECT review_mvp_test_artifact($1)',[testId]),/current saved app/);
  await db.exec(`SELECT set_config('request.jwt.claim.sub','${owner}',false);`);
  await call("UPDATE mvp_projects SET metadata=jsonb_set(metadata,'{setupInput,buildBrief,idea}','\"An email waitlist\"') WHERE id=$1",[staticId]);
  await assert.rejects(call('SELECT request_mvp_workflow_test($1)',[staticId]),/workflow/);
  assert.equal((await call('SELECT * FROM current_mvp_workflow_test($1)',[staticId])).length,0);
  await assert.rejects(call('SELECT review_mvp_test_artifact($1)',[testId]),/current saved app/);
 });
 let id,lease;
 await t.test('backfill freezes existing URLs while drafts change',async()=>{
  await db.exec(`UPDATE mvp_projects SET project_files='[{"filename":"index.html","content":"draft"}]' WHERE id='${project}';`);
  assert.equal((await call("SELECT content FROM get_published_mvp_file('example','/')"))[0].content,'legacy');
 });
 await t.test('owner queues one test per revision; another user cannot queue it',async()=>{
  id=(await call('SELECT request_mvp_workflow_test($1) id',[project]))[0].id;
  assert.equal((await call('SELECT request_mvp_workflow_test($1) id',[project]))[0].id,id);
  await db.exec(`SELECT set_config('request.jwt.claim.sub','${other}',false);`);
  await assert.rejects(call('SELECT request_mvp_workflow_test($1)',[project]),/Project not found/);
  await db.exec(`SELECT set_config('request.jwt.claim.sub','${owner}',false);`);
 });
 await t.test('the worker must own a current lease and supply all outcome assertions',async()=>{
  lease=(await call('SELECT * FROM claim_mvp_workflow_test()'))[0].lease;
  await assert.rejects(call("SELECT finish_mvp_workflow_test($1,$2,'{}',null,null)",[id,other]),/lease/);
  await call("SELECT finish_mvp_workflow_test($1,$2,'{\"customer_task\":true}',null,'No database write')",[id,lease]);
  assert.equal((await call('SELECT status FROM mvp_build_tests WHERE id=$1',[id]))[0].status,'failed');
  id=(await call('SELECT request_mvp_workflow_test($1) id',[project]))[0].id;lease=(await call('SELECT * FROM claim_mvp_workflow_test()'))[0].lease;
  await call("SELECT finish_mvp_workflow_test($1,$2,$3,$4,null)",[id,lease,{customer_task:true,database_write:true,persisted_after_reload:true,access_control:true,no_runtime_errors:true,responsive_ui:true,cleanup:true},[{filename:'index.html',content:'tested build'}]]);
 });
 await t.test('stale results and wrong-owner tests cannot publish or charge',async()=>{
  assert.equal((await call('SELECT inspect_mvp_workflow_test($1,$2,$3) value',[project,other,id]))[0].value,null);
  await db.exec(`UPDATE mvp_projects SET project_files='[{"filename":"index.html","content":"edited"}]' WHERE id='${project}';`);
  await assert.rejects(call('SELECT publish_tested_mvp($1,$2,$3,$4,$5,$6)',[project,owner,id,'example','https://example.test',other]),/current saved revision/);
  assert.equal((await call('SELECT count(*)::int n FROM charges'))[0].n,0);
  await db.exec(`UPDATE mvp_projects SET project_files='[{"filename":"index.html","content":"draft"}]' WHERE id='${project}';`);
 });
 await t.test('publish and retry charge once and serve the tested artifact',async()=>{
  await call('INSERT INTO mvp_builder_credit_reservations(id,user_id,action_feature,idempotency_key) VALUES($1,$2,$3,$4)',[other,owner,'APP_BUILDER_DEPLOY','workflow-publish:'+project+':'+id]);
  for(let i=0;i<2;i++)await call('SELECT publish_tested_mvp($1,$2,$3,$4,$5,$6)',[project,owner,id,'example','https://example.test',other]);
  assert.equal((await call('SELECT count(*)::int n FROM charges'))[0].n,1);
  assert.equal((await call("SELECT content FROM get_published_mvp_file('example','index.html')"))[0].content,'tested build');
 });
 await t.test('owner cannot forge test results or a published URL',async()=>{
  await db.exec(`SELECT set_config('request.jwt.claim.role','authenticated',false);`);
  await assert.rejects(db.exec(`UPDATE mvp_projects SET deployment_url='https://forged.test' WHERE id='${project}';`),/tested publication/);
  await db.exec('SET ROLE authenticated;');
  await assert.rejects(db.exec("UPDATE mvp_build_tests SET status='passed'"),/permission denied/);
  await assert.rejects(call('SELECT finish_mvp_workflow_test($1,$2,null,null,null)',[id,lease]),/permission denied/);
  await db.exec('RESET ROLE;');
 });
 await t.test('a recovery checkpoint restores source but keeps the published artifact',async()=>{
  await call('SELECT mvp_edit_checkpoint($1,false)',[project]);await db.exec(`UPDATE mvp_projects SET project_files='[]' WHERE id='${project}';`);await call('SELECT mvp_edit_checkpoint($1,true)',[project]);
  assert.equal((await call('SELECT project_files FROM mvp_projects WHERE id=$1',[project]))[0].project_files[0].content,'draft');
  assert.equal((await call("SELECT content FROM get_published_mvp_file('example','index.html')"))[0].content,'tested build');
 });
 await t.test('demo undo restores removed screens atomically and rejects cross-owner snapshots',async()=>{
  await db.exec(`CREATE TABLE demo_studio_demos(id uuid PRIMARY KEY,owner_id uuid,title text,theme jsonb,updated_at timestamptz);
   CREATE TABLE demo_studio_demo_steps(id uuid PRIMARY KEY,demo_id uuid REFERENCES demo_studio_demos(id),position integer,asset_type text,asset_url text,asset_width integer,asset_height integer,asset_captured_at timestamptz,title text,caption text,speaker_notes text);
   CREATE TABLE demo_studio_demo_hotspots(id uuid PRIMARY KEY,step_id uuid REFERENCES demo_studio_demo_steps(id) ON DELETE CASCADE,x numeric,y numeric,w numeric,h numeric,type text,label text,action text,action_target text);
   INSERT INTO demo_studio_demos VALUES('${project}','${owner}','Demo','{}',now()),('${other}','${other}','Private','{}',now());
   INSERT INTO demo_studio_demo_steps(id,demo_id,position) VALUES('${other}','${other}',0);
  `);
  await db.exec(readFileSync('supabase/migrations/20261001121000_demo_editor_recovery.sql','utf8'));
  const steps=[{id:owner,position:0,asset_type:'image',asset_url:'https://example.com/image.png',caption:'First screen',hotspots:[]}];
  await call('SELECT restore_demo_edit($1,$2,$3,$4)',[project,'Demo',{},steps]);
  await call('SELECT restore_demo_edit($1,$2,$3,$4)',[project,'Demo',{},[]]);
  await call('SELECT restore_demo_edit($1,$2,$3,$4)',[project,'Demo',{},steps]);
  assert.equal((await call('SELECT count(*)::int n FROM demo_studio_demo_steps WHERE demo_id=$1',[project]))[0].n,1);
  await assert.rejects(call('SELECT restore_demo_edit($1,$2,$3,$4)',[project,'Demo',{},[{...steps[0],id:other}]]),/another demo/);
  assert.equal((await call('SELECT caption FROM demo_studio_demo_steps WHERE id=$1',[owner]))[0].caption,'First screen');
  await assert.rejects(call('SELECT reorder_demo_screens($1)',[[owner,owner]]),/Screen list changed/);
  await call('SELECT reorder_demo_screens($1)',[[owner]]);
 });
 await t.test('workflow database policies protect saved customer records and owner-only leads',async()=>{
  await db.exec('GRANT USAGE ON SCHEMA auth TO anon;');
  await db.exec(readFileSync('workers/mvp-workflow/schema.sql','utf8'));
  await call('INSERT INTO ct_mvp_workflow_owners VALUES($1,$2)',[project,owner]);
  await db.exec('SET ROLE anon;');
  await call("INSERT INTO ct_mvp_records(project_key,email) VALUES($1,'lead@example.invalid')",[project]);
  await assert.rejects(call('SELECT * FROM ct_mvp_records'),/permission denied/);
  await db.exec(`RESET ROLE;SELECT set_config('request.jwt.claim.sub','${owner}',false);SET ROLE authenticated;`);
  assert.equal((await call('SELECT * FROM ct_mvp_records')).length,1);
  await db.exec(`RESET ROLE;SELECT set_config('request.jwt.claim.sub','${other}',false);SET ROLE authenticated;`);
  assert.equal((await call('SELECT * FROM ct_mvp_records')).length,0);
  await call("INSERT INTO ct_mvp_records(project_key,user_id,body) VALUES($1,$2,'My task')",[project,other]);
  assert.equal((await call('SELECT * FROM ct_mvp_records')).length,1);
  await assert.rejects(call("INSERT INTO ct_mvp_records(project_key,user_id,body) VALUES($1,$2,'Forged')",[project,owner]),/row-level security/);
  await db.exec('RESET ROLE;');
 });
 }finally{await db.close();}
});
