import {test,expect} from '@playwright/test';
const id='77777777-7777-4777-8777-777777777777';
for(const viewport of [{width:1440,height:1000},{width:390,height:844}])test('builder retains workspace and reviews managed scope '+viewport.width,async({page})=>{
 let rejectSaves=false,setupRequests=0,buildRequests=0;
 await page.setViewportSize(viewport);
 const user={id,aud:'authenticated',role:'authenticated',email:'builder@example.invalid',app_metadata:{provider:'email'},user_metadata:{full_name:'Builder'},identities:[],created_at:'2026-01-01T00:00:00Z'};
 await page.addInitScript(({user})=>localStorage.setItem('sb-dummy-auth-token',JSON.stringify({access_token:'test',refresh_token:'test-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user})),{user});
 await page.route('**/auth/v1/user',r=>r.fulfill({json:user}));
 await page.route('**/rest/v1/**',async r=>{const table=new URL(r.request().url()).pathname.split('/').pop();const object=(r.request().headers().accept||'').includes('vnd.pgrst.object');
 if(table==='get_credit_wallet_v1')return r.fulfill({json:{balance:500,monthly_quota:500,held_credits:0,total_available:1000,subscription_tier:'pro'}});
 if(table==='account_context')return r.fulfill({json:{userType:'founder',approvalStatus:'approved',hasCategoryAccess:true,requiresProject:false,hasProject:true}});
 if(table==='save_mvp_project'){if(rejectSaves)return r.fulfill({status:503,json:{message:'Save unavailable'}});const p=r.request().postDataJSON().p_project;return r.fulfill({json:{...p,updated_at:new Date().toISOString(),created_at:new Date().toISOString()}});}
 return r.fulfill({json:object?null:[]});});
 await page.route('**/functions/v1/**',r=>{const name=new URL(r.request().url()).pathname.split('/').pop();const action=r.request().postDataJSON();if(name==='mvp-managed-app'&&action?.action==='setup')setupRequests++;if(name==='mvp-builder-generate'&&action?.mode!=='classify')buildRequests++;return r.fulfill({json:name==='mvp-workflow-tests'?{available:true,profiles:['lead_capture','request_management','customer_portal']}:name==='check-subscription'?{subscribed:true,subscription_tier:'pro'}:{success:true,ok:true,granted:false}});});
 await page.goto('/mvp-builder');
 await expect(page.getByText('Ready to build',{exact:true})).toBeVisible();
 await page.getByPlaceholder('Describe your MVP idea, core flow, and visual style...').fill('Build a request tracker for my customers to submit requests and see their status');
 await page.getByRole('button',{name:'Build',exact:true}).first().click();
 await expect(page.getByText('Your build plan',{exact:true})).toBeVisible();
 await expect(page.getByText('Connected app',{exact:true})).toBeVisible();
 await page.getByText('App details and recovery',{exact:true}).click();
 await expect(page.getByLabel('Build mode')).toHaveValue('managed');
 await expect(page.getByRole('button',{name:'Review price and build'})).toBeEnabled();
 await page.getByLabel('Who uses it?').fill('');
 await expect(page.getByText('Tell us who will use this app.',{exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Review price and build'})).toBeDisabled();
 await page.getByLabel('Who uses it?').fill('Studio customers');
 await expect(page.getByRole('button',{name:'Review price and build'})).toBeEnabled();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Review price and build'}).click();
 await expect(page.getByRole('dialog').getByText('Review this build',{exact:true})).toBeVisible();
 await expect(page.getByRole('dialog')).toContainText('two automatic outcome repair attempts');
 rejectSaves=true;
 await page.getByRole('button',{name:'Confirm and build'}).click();
 await expect(page.getByText('Your latest changes have not been saved.',{exact:true})).toBeVisible();
 await page.getByText('Failure details',{exact:true}).click();
 await expect(page.getByText('Save failed. Your draft is still open. Retry saving before leaving.',{exact:true})).toBeVisible();
 expect(setupRequests).toBe(0);expect(buildRequests).toBe(0);
 await expect(page.getByRole('button',{name:'Retry save',exact:true}).first()).toBeVisible();
 rejectSaves=false;
 await page.getByRole('button',{name:'Retry save',exact:true}).first().click();
 await expect(page.getByRole('button',{name:'Review price and build'})).toBeEnabled();
 await expect(page.getByText('Your latest changes have not been saved.',{exact:true})).toHaveCount(0);
 expect(setupRequests).toBe(0);expect(buildRequests).toBe(0);
 if(viewport.width<768){await page.getByRole('button',{name:'Preview',exact:true}).first().click();await page.getByRole('button',{name:'Chat',exact:true}).first().click();await expect(page.getByText('Your build plan',{exact:true})).toBeVisible();}
});
