import { suggestImportMapping } from '@/lib/coreToolsExperience';
import { useState, useEffect } from 'react';
import Navigation from '@/components/Navigation';
import SEO from '@/components/SEO';
import ProductDataPanel from '@/components/core-tools/ProductDataPanel';
import { connectedToolsEnabled } from '@/hooks/useCoreProduct';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { CONNECTORS, parseCsv, sourceFreshness, type ConnectorProvider } from '@/lib/coreTools';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';

const MAPPING_FIELDS = ['id','date','respondent','email','feedback','objections','segment','incentivized','product_usage','metric','value','unit','period_start','period_end'];
const enabledProviders = String(import.meta.env.VITE_CORE_TOOLS_PROVIDERS || 'sheets,tally').split(',').map(value => value.trim()).filter(value => CONNECTORS.some(item => item.id === value));
export default function ConnectionsPage() {
  const { user } = useAuth();
  const [productId, setProductId] = useState(''); const [provider, setProvider] = useState<ConnectorProvider>((enabledProviders[0] || 'sheets') as ConnectorProvider);
  const [config, setConfig] = useState<Record<string, string>>({}); const [token, setToken] = useState('');
  const [eventSecrets,setEventSecrets] = useState<Record<string,string>>({});
  const [eventUrls,setEventUrls] = useState<Record<string,string>>({});
  const [connections, setConnections] = useState<any[]>([]); const [busy, setBusy] = useState(false);
  const [batch, setBatch] = useState<{ batchId: string; rows: Record<string, unknown>[] } | null>(null);
  const [mapping, setMapping] = useState<Record<string, string>>({}); const [preview, setPreview] = useState<any>(null);
  const definition = CONNECTORS.find(item => item.id === provider)!;
  const call = async (body: Record<string, unknown>) => { const { data, error } = await supabase.functions.invoke('core-connections', { body }); if (error || !data?.success) throw new Error(data?.error || error?.message || 'Connection action failed.'); return data; };
  const reload = async () => { if (!user || !productId) return; const { data, error } = await (supabase as any).from('ct_connections').select('id,label,provider,status,last_synced_at,last_error').eq('product_id', productId).eq('user_id', user.id).order('created_at'); if (error) throw error; setConnections(data ?? []); };
  useEffect(() => { setConnections([]); setBatch(null); setPreview(null); void reload().catch(() => toast.error('Could not load connections.')); }, [productId, user?.id]);
  const perform = async (action: () => Promise<void>) => { setBusy(true); try { await action(); } catch(error) { toast.error(error instanceof Error ? error.message : 'Could not complete this action.'); } finally { setBusy(false); } };
  const startPreview = (data: any) => { setBatch(data); setMapping(suggestImportMapping(Object.keys(data.rows?.[0] ?? {}).filter(key => !key.startsWith('_')))); setPreview(null); };
  return <><SEO title="Connections" description="Bring customer evidence and business results into your CT workspace." url="/connections" noindex /><Navigation /><main className="mx-auto max-w-5xl space-y-6 px-4 pb-16 pt-28">
    <h1 className="text-3xl font-semibold">Connections</h1><ol aria-label="Import steps" className="grid gap-2 text-sm sm:grid-cols-4">{['1. Choose your product','2. Connect or upload','3. Check a sample','4. Confirm import'].map(step => <li key={step} className="rounded-lg border bg-muted/30 p-3">{step}</li>)}</ol><p className="text-muted-foreground">Connect the tools you use, check what will be imported, and keep your weekly decisions current.</p>
    {!user ? <p>Sign in to manage your data.</p> : !connectedToolsEnabled() ? <p>Connected data is being prepared for the pilot.</p> : <>
      <ProductDataPanel onProductChange={setProductId} />
      {productId && <>
        <section className="space-y-4 rounded-xl border p-5"><h2 className="text-lg font-semibold">Add a connection</h2><p className="text-sm text-muted-foreground">Choose the account or project to read. CT imports selected data; it does not edit your source records. You will review a sample before accepting the first import.</p>
          <label className="block space-y-1 text-sm"><span>Data source</span><select className="w-full rounded-md border bg-background p-2" value={provider} onChange={e => { setProvider(e.target.value as ConnectorProvider); setConfig({}); setToken(''); }}>{CONNECTORS.filter(item => enabledProviders.includes(item.id)).map(item => <option key={item.id} value={item.id}>{item.name} — {item.purpose}</option>)}</select></label>
          {definition.fields.map(field => <label key={field} className="block space-y-1 text-sm"><span>{field === 'productKey' ? 'Product identifier (optional; matches Stripe ct_product_key metadata)' : field.replace(/([A-Z])/g, ' $1')}{definition.optionalFields?.includes(field) && field !== 'productKey' ? ' (optional)' : ''}</span><Input value={config[field] ?? ''} onChange={e => setConfig(current => ({ ...current, [field]: e.target.value }))} placeholder={field === 'region' ? 'us or eu' : field === 'range' ? 'Sheet1!A1:Z1001' : undefined} /></label>)}
          <label className="block space-y-1 text-sm"><span>Import from (optional; defaults to the last 90 days)</span><Input type="date" value={config.since ?? ''} onChange={e => setConfig(current => ({ ...current, since: e.target.value }))} /></label>
          {!['sheets','ga4'].includes(provider) && <label className="block space-y-1 text-sm"><span>Read-only API credential</span><Input type="password" autoComplete="off" value={token} onChange={e => setToken(e.target.value)} /><span className="text-xs text-muted-foreground">Stored encrypted on the server. Use the provider's read-only permissions.</span></label>}
<label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={config.productScopeConfirmed === 'true'} onChange={e => setConfig({...config,productScopeConfirmed:String(e.target.checked)})}/>The selected account, form, project or filtered records belong to this product. For a shared Stripe account, supply a product identifier.</label>
          <Button disabled={busy || (!['sheets','ga4'].includes(provider) && !token.trim()) || definition.fields.some(field => !definition.optionalFields?.includes(field) && !config[field]?.trim()) || config.productScopeConfirmed !== 'true'} onClick={() => void perform(async () => { const google = ['sheets','ga4'].includes(provider); const data = await call({ action: google ? 'oauth_start' : 'connect', productId, provider, config, token, label: definition.name }); setToken(''); if (data.url) window.location.assign(data.url); else { await reload(); toast.success('Connected. Preview your first import below.'); } })}>Connect {definition.name}</Button>
        </section>
        <section className="space-y-3"><h2 className="text-lg font-semibold">Your connections</h2>{!connections.length && <p className="text-sm text-muted-foreground">No sources connected for this product.</p>}{connections.map(connection => <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4" key={connection.id}><div><p className="font-medium">{connection.label}</p><p className="text-xs text-muted-foreground">{connection.status} · {sourceFreshness(connection.last_synced_at)}</p>{connection.last_error && <p role="alert" className="mt-1 text-sm text-destructive">{connection.last_error} {connection.status === 'expired' ? 'Reconnect this provider above with a current credential.' : 'Check source permissions and your selected account, then preview again.'}</p>}</div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy || connection.status === 'disconnected'} onClick={() => void perform(async () => { startPreview(await call({ action: 'sync', connectionId: connection.id })); await reload(); })}>Preview sync</Button><Button variant="ghost" disabled={busy || connection.status === 'disconnected'} onClick={() => void perform(async () => { await call({ action: 'disconnect', connectionId: connection.id }); await reload(); })}>Disconnect</Button></div>{['stripe','tally','typeform','shopify'].includes(connection.provider)&&connection.status!=='disconnected'&&<details className="w-full text-sm"><summary className="cursor-pointer">Optional: refresh when this provider sends an update</summary><p className="my-2 text-xs text-muted-foreground">Create a webhook in your provider account with this URL. Save its signing secret here; verified updates will queue a refresh after your first accepted import.</p><Input readOnly aria-label="Provider event URL" value={eventUrls[connection.id]||`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/core-connections?connection=${connection.id}`}  onFocus={e=>e.target.select()}/><Input className="mt-2" type="password" autoComplete="off" aria-label="Provider webhook signing secret" value={eventSecrets[connection.id]||''} onChange={e=>setEventSecrets({...eventSecrets,[connection.id]:e.target.value})}/><Button className="mt-2" variant="outline" disabled={busy||(eventSecrets[connection.id]?.length||0)<16} onClick={()=>void perform(async()=>{const r=await call({action:'configure_events',connectionId:connection.id,secret:eventSecrets[connection.id]});setEventUrls({...eventUrls,[connection.id]:r.url});setEventSecrets({...eventSecrets,[connection.id]:''});toast.success('Event verification configured. Complete webhook setup in your provider account.');})}>Save event verification</Button></details>}</div>)}</section>
        <section className="space-y-2 rounded-xl border p-4"><h2 className="font-semibold">Import a spreadsheet file</h2><a className="inline-block py-2 text-sm font-medium text-primary underline" download="ct-feedback-template.csv" href={'data:text/csv;charset=utf-8,'+encodeURIComponent('id,date,respondent,email,feedback,objections,segment\n')}>Download an empty feedback template</a><p className="text-xs text-muted-foreground">CSV, up to 1 MB and 1,000 rows. Include a date column. Spreadsheet data is labelled user supplied.</p><Input type="file" accept=".csv,text/csv" aria-label="Import CSV" disabled={busy} onChange={event => { const file = event.target.files?.[0]; if (!file) return; void perform(async () => { if (file.size > 1000000) throw new Error('Choose a file smaller than 1 MB.'); const rows = parseCsv(await file.text()); startPreview(await call({ action: 'upload', productId, sourceName: file.name, rows })); }); event.target.value = ''; }} /></section>
        {batch && <section className="space-y-4 rounded-xl border p-5"><h2 className="text-lg font-semibold">Review {batch.rows.length} incoming records</h2><p className="text-sm text-muted-foreground">Recognized column names are suggested below. Confirm the choices, check a sample and resolve any errors before importing. Existing source records are updated rather than counted twice.</p>{[MAPPING_FIELDS.slice(0,7),MAPPING_FIELDS.slice(7)].map((fields,index) => {const controls=<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map(field => <label key={field} className="space-y-1 text-sm"><span>{field.replace(/_/g,' ')}{mapping[field] ? ' - matched' : ''}</span><select className="min-h-11 w-full rounded-md border bg-background p-2" value={mapping[field] ?? ''} onChange={e => { setMapping(current => ({ ...current, [field]: e.target.value })); setPreview(null); }}><option value="">Use column named {field}</option>{Object.keys(batch.rows[0] ?? {}).filter(key => !key.startsWith('_')).map(key => <option key={key}>{key}</option>)}</select>{mapping[field] && <span className="block truncate text-xs text-muted-foreground">Example: {String(batch.rows[0]?.[mapping[field]] ?? 'Empty in the first row')}</span>}</label>)}</div>;return index===0?<div key={index}>{controls}</div>:<details key={index}><summary className="cursor-pointer py-2 text-sm font-medium">Optional: incentives, product use and business metrics</summary>{controls}</details>;})}
          <p className="text-xs text-muted-foreground">Dates should include the year, month and day. A stable response ID or email helps avoid counting the same person repeatedly.</p>
          <Button variant="outline" disabled={busy} onClick={() => void perform(async () => { setPreview(await call({ action: 'preview', batchId: batch.batchId, mapping })); })}>Check mapping and duplicates</Button>
          {preview && <><p className="text-sm">{preview.evidence.length} evidence records · {preview.metrics.length} metrics · {preview.duplicates} repeated source records</p><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr>{['Respondent','Date','Segment','Incentive','Source','Feedback'].map(label => <th className="p-2" key={label}>{label}</th>)}</tr></thead><tbody>{preview.evidence.slice(0, 10).map((row: any) => <tr key={row.source_key} className="border-t"><td className="p-2">{row.summary.respondent || 'Unknown'}</td><td className="p-2">{row.captured_at.slice(0, 10)}</td><td className="p-2">{row.segment || 'Unassigned'}</td><td className="p-2">{row.incentivized ? 'Incentivized' : 'None reported'}</td><td className="p-2">{row.provenance}</td><td className="max-w-xs p-2">{row.summary.feedback || row.kind}</td></tr>)}</tbody></table></div><Button disabled={busy} onClick={() => void perform(async () => { const result = await call({ action: 'accept', batchId: batch.batchId, mapping }); toast.success(`${result.count} records imported. Return to PMF or your weekly workspace to review them.`); setBatch(null); setPreview(null); await reload(); })}>Confirm and import</Button></>}
        </section>}
      </>}
    </>}
  </main></>;
}
