import ValidationReviewQueue from '@/components/pmf/ValidationReviewQueue';
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { toast } from 'sonner';

const db=supabase as any;
const sessionColumns='id,founder_id,reviewer_id,context_id,starts_at,status,guest_name,meet_url,calendar_state,calendar_error,attendance_status,overlap_seconds,pre_feedback,feedback,reward_status,reward_eligible_at,review_reason';
async function request(body:any){const {data,error}=await supabase.functions.invoke('validation-sessions',{body});if(error||data?.error)throw new Error(data?.error||error?.message||'Session request failed.');return data;}
const labels:Record<string,string>={recentBehavior:'What have you done recently to address this problem?',currentWorkaround:'What do you use or do today?',problemRelevance:'How does this problem affect you?',clarity:'What was clear or unclear?',objections:'What would prevent you from using this?',willingnessToTry:'Would you try it? What would need to happen first?',willingnessToPay:'Would you pay? Under what conditions?',suggestedChange:'What is one change you suggest?'};
function Feedback({session,guestToken,onDone}:{session:any;guestToken?:string;onDone:()=>void}){
 const before=!session.pre_feedback;const keys=before?['recentBehavior','currentWorkaround','problemRelevance']:['clarity','objections','willingnessToTry','willingnessToPay','suggestedChange'];const [form,setForm]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);
 if(session.feedback)return <p className="text-sm">Feedback submitted. Critical and positive feedback receive the same reward consideration.</p>;
 return <form className="space-y-3" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await request({action:'feedback',sessionId:session.id,guestToken,before,feedback:form});setForm({});onDone();toast.success('Feedback recorded.');}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}}><h3 className="font-medium">{before?'Before the pitch':'After the session'}</h3>{keys.map(key=><label key={key} className="block text-sm">{labels[key]}<Textarea required minLength={5} maxLength={3000} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<Button disabled={busy}>Submit feedback</Button></form>;
}
function calendarDownload(session:any){const stamp=(date:Date)=>date.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z/,'Z');const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//CT//Validation//EN','BEGIN:VEVENT',`UID:${session.id}@creatives-takeover.com`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(new Date(session.starts_at))}`,`DTEND:${stamp(new Date(Date.parse(session.starts_at)+25*60000))}`,'SUMMARY:CT validation session',`URL:${session.meet_url||window.location.origin+'/validation-sessions'}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download='ct-validation.ics';a.click();URL.revokeObjectURL(url);}
export default function ValidationSessionsPage(){
 const {user}=useAuth();const [params]=useSearchParams();const guestToken=params.get('invite')||undefined,contextId=params.get('context'),productId=params.get('product');
 const [sessions,setSessions]=useState<any[]>([]),[guest,setGuest]=useState<any>(null),[matches,setMatches]=useState<any[]>([]),[searched,setSearched]=useState(false),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false);
 const [profile,setProfile]=useState({display_name:'',role:'',industry:'',problems:'',languages:'en',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,opted_in:false});
 const [slot,setSlot]=useState(''),[inviteSlots,setInviteSlots]=useState<string[]>([]),[inviteLink,setInviteLink]=useState(''),[name,setName]=useState(''),[email,setEmail]=useState(''),[chosen,setChosen]=useState('');
 const [filter,setFilter]=useState({language:'en',role:'',industry:'',problems:'',from:new Date().toISOString().slice(0,10),to:new Date(Date.now()+30*86400000).toISOString().slice(0,10)});
 const [changeTimes,setChangeTimes]=useState<Record<string,string>>({}),[disputes,setDisputes]=useState<Record<string,string>>({}),[excludeId,setExcludeId]=useState('');
 const [isAdmin,setIsAdmin]=useState(false);
 const enabled=import.meta.env.VITE_VALIDATION_SESSIONS_ENABLED==='true';
 async function reload(){if(!enabled)return;if(guestToken){const data=await request({action:'guest_view',guestToken});setGuest(data.session);return;}if(!user)return;const {data,error}=await db.from('ct_validation_sessions').select(sessionColumns).or(`founder_id.eq.${user.id},reviewer_id.eq.${user.id}`).order('starts_at',{ascending:false}).limit(50);if(error)throw error;setSessions(data||[]);}
 async function run(task:()=>Promise<void>){setBusy(true);try{await task();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{void run(reload);},[user?.id,guestToken,enabled]);
 useEffect(()=>{if(!user||!enabled||guestToken)return;let active=true;void Promise.all([db.from('ct_reviewer_profiles').select('*').eq('user_id',user.id).maybeSingle(),request({action:'google_status'})]).then(([p,g])=>{if(!active)return;if(p.data)setProfile({...p.data,problems:p.data.problems.join(', '),languages:p.data.languages.join(', ')});setConnected(g.connected);setIsAdmin(g.isAdmin);}).catch(e=>toast.error(e.message));return()=>{active=false;};},[user?.id,enabled,guestToken]);
 if(!enabled)return <main className="mx-auto max-w-3xl p-8"><h1 className="text-2xl font-semibold">Validation sessions</h1><p>This pilot is not enabled yet.</p><Link to="/pmf-lab" className="underline">Return to PMF Lab</Link></main>;
 if(guestToken)return <main className="mx-auto max-w-2xl space-y-5 p-6"><h1 className="text-2xl font-semibold">Your validation session</h1><p>Help a founder test their product in a 25-minute session. No CT account is needed. Keep this private invitation link to submit feedback.</p>{guest?.status==='invited'?<form className="space-y-3" onSubmit={e=>{e.preventDefault();void run(async()=>{await request({action:'guest_book',guestToken,name,email,startsAt:chosen});await reload();});}}><label className="block">Name<Input required value={name} onChange={e=>setName(e.target.value)}/></label><label className="block">Email for your calendar invitation<Input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block">Time ({Intl.DateTimeFormat().resolvedOptions().timeZone})<select required className="w-full rounded border bg-background p-2" value={chosen} onChange={e=>setChosen(e.target.value)}><option value="">Choose a time</option>{guest.offered_slots.map((s:string)=><option key={s} value={s}>{new Date(s).toLocaleString()}</option>)}</select></label><Button disabled={busy}>Book session</Button></form>:guest&&<><p>{new Date(guest.starts_at).toLocaleString()} · {guest.status}</p>{guest.meet_url&&<a className="underline" href={guest.meet_url} target="_blank" rel="noreferrer">Join Google Meet</a>}<Button variant="outline" onClick={()=>calendarDownload(guest)}>Download calendar event</Button>{guest.status!=='cancelled'&&<Feedback key={guest.id} session={guest} guestToken={guestToken} onDone={()=>void run(reload)}/>}</>}</main>;
 if(!user)return <main className="p-8"><h1 className="text-2xl">Validation sessions</h1><Link to="/auth" className="underline">Sign in to book or review</Link></main>;
 return <main className="mx-auto max-w-5xl space-y-6 p-6"><div><Link to="/pmf-lab" className="text-sm underline">PMF Lab</Link><h1 className="text-3xl font-semibold">Validation sessions</h1><p className="mt-2 text-muted-foreground">One founder, one reviewer, 25 minutes. Discover the problem, pitch, ask questions, and record useful feedback.</p></div>
 <section className="space-y-3 rounded-xl border p-4"><h2 className="font-semibold">Calendar and attendance</h2><p className="text-sm">{connected?'Google Calendar connected. Join using this same Google identity for attendance verification.':'Connect Google to create meetings and verify your signed-in attendance.'}</p><Button disabled={busy} onClick={()=>void run(async()=>{if(connected){await request({action:'google_disconnect'});setConnected(false);}else{const r=await request({action:'google_connect'});window.location.assign(r.url);}})}>{connected?'Disconnect Google':'Connect Google Calendar and Meet'}</Button><p className="text-xs text-muted-foreground">Reviewers may receive 20 credits after 15 verified minutes together, complete feedback, and a 24-hour hold. Verified CT accounts must be seven days old. Limits: two per week, four per month, one pairing in either direction per 30 days. Pilot: 100 rewarded sessions.</p></section>
 <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Your reviewer profile and availability</summary><form className="mt-4 space-y-3" onSubmit={e=>{e.preventDefault();void run(async()=>{const {error}=await db.from('ct_reviewer_profiles').upsert({...profile,user_id:user.id,problems:profile.problems.split(',').map(s=>s.trim()).filter(Boolean),languages:profile.languages.split(',').map(s=>s.trim()).filter(Boolean)});if(error)throw error;toast.success('Reviewer profile saved.');});}}>{(['display_name','role','industry','problems','languages','timezone'] as const).map(key=><label key={key} className="block text-sm">{key.replace(/_/g,' ')}{['problems','languages'].includes(key)?' (comma separated)':''}<Input required value={profile[key]} onChange={e=>setProfile({...profile,[key]:e.target.value})}/></label>)}<label className="flex gap-2 text-sm"><input type="checkbox" checked={profile.opted_in} onChange={e=>setProfile({...profile,opted_in:e.target.checked})}/>Make my profile and available slots discoverable to CT founders</label><Button disabled={busy}>Save profile</Button></form><label className="mt-4 block text-sm">Available time ({profile.timezone})<Input type="datetime-local" value={slot} onChange={e=>setSlot(e.target.value)}/></label><Button className="mt-2" variant="outline" disabled={!slot||busy} onClick={()=>void run(async()=>{const {error}=await db.rpc('ct_offer_reviewer_slot',{p_start:new Date(slot).toISOString()});if(error)throw error;toast.success('25-minute slot added.');})}>Add available slot</Button><label className="mt-4 block text-sm">Exclude a collaborator or blocked account (CT account ID)<Input value={excludeId} onChange={e=>setExcludeId(e.target.value)}/></label><div className="flex gap-2">{['collaborator','blocked'].map(reason=><Button key={reason} variant="outline" disabled={!excludeId||busy} onClick={()=>void run(async()=>{const {error}=await db.from('ct_reviewer_exclusions').upsert({user_id:user.id,other_user_id:excludeId,reason});if(error)throw error;toast.success('Account excluded from matching.');})}>{reason==='blocked'?'Block account':'Declare collaborator'}</Button>)}</div></details>
 <section className="space-y-3 rounded-xl border p-4"><h2 className="font-semibold">Find reviewers</h2>{!contextId||!productId?<p className="text-sm">Open sessions from a product-linked PMF validation context to book a reviewer.</p>:<><div className="grid gap-3 sm:grid-cols-2">{Object.keys(filter).map(key=><label className="text-sm" key={key}>{key}<Input type={['from','to'].includes(key)?'date':'text'} value={(filter as any)[key]} onChange={e=>setFilter({...filter,[key]:e.target.value})}/></label>)}</div><Button disabled={busy} onClick={()=>void run(async()=>{const {data,error}=await db.rpc('ct_find_reviewers',{p_language:filter.language,p_role:filter.role,p_industry:filter.industry,p_problems:filter.problems.split(',').map(s=>s.trim()),p_from:new Date(filter.from).toISOString(),p_to:new Date(filter.to+'T23:59:59Z').toISOString()});if(error)throw error;setMatches(data||[]);setSearched(true);})}>Find available reviewers</Button>{searched&&!matches.length&&<p className="text-sm">No matching slots are available. Invite a target customer below, or use Find interviewees in PMF Lab.</p>}{matches.map(m=><article key={m.slot_id} className="rounded border p-3 text-sm"><h3 className="font-medium">{m.display_name} · {m.role} · {m.industry}</h3><p>{new Date(m.starts_at).toLocaleString()} · {m.timezone}</p><p>{m.match_reasons.join(' · ')||'Available in your language; customer fit needs screening.'}</p><p className="text-xs text-muted-foreground">Account: {m.user_id}</p><Button size="sm" disabled={busy||!connected} onClick={()=>void run(async()=>{const {error}=await db.rpc('ct_book_validation',{p_slot:m.slot_id,p_context:contextId,p_product:productId});if(error)throw error;await reload();toast.success('Booked. Calendar details will arrive shortly.');setMatches(matches.filter(row=>row.slot_id!==m.slot_id));})}>Book 25 minutes</Button></article>)}</>}</section>
 {contextId&&productId&&<section className="space-y-3 rounded-xl border p-4"><h2 className="font-semibold">Invite a target customer</h2><p className="text-sm">Choose up to ten proposed times and share a private booking link. External reviewers do not receive CT credit rewards.</p><Input aria-label="Proposed invitation time" type="datetime-local" value={slot} onChange={e=>setSlot(e.target.value)}/><Button variant="outline" disabled={!slot||inviteSlots.length>=10} onClick={()=>setInviteSlots([...new Set([...inviteSlots,new Date(slot).toISOString()])])}>Add proposed time</Button><ul className="text-sm">{inviteSlots.map(s=><li key={s}>{new Date(s).toLocaleString()} <button className="underline" onClick={()=>setInviteSlots(inviteSlots.filter(x=>x!==s))}>Remove</button></li>)}</ul><Button disabled={busy||!connected||!inviteSlots.length} onClick={()=>void run(async()=>{const r=await request({action:'invite',contextId,productId,slots:inviteSlots});setInviteLink(r.url);await reload();})}>Create private booking link</Button>{inviteLink&&<Input readOnly aria-label="Private booking link" value={inviteLink} onFocus={e=>e.target.select()}/>}</section>}
 {isAdmin&&<ValidationReviewQueue/>}
 <section className="space-y-4"><div className="flex justify-between"><h2 className="text-xl font-semibold">Your sessions</h2><Button variant="outline" disabled={busy} onClick={()=>void run(reload)}>Refresh</Button></div>{!sessions.length&&<p className="text-sm text-muted-foreground">Your bookings will appear here.</p>}{sessions.map(s=><article key={s.id} className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">{new Date(s.starts_at).toLocaleString()} · {s.status}</h3><p className="text-sm">Attendance: {s.attendance_status} · Reward: {s.reward_status}</p>{s.review_reason&&<p className="text-sm">Review: {s.review_reason}</p>}{s.calendar_error&&<p role="alert" className="text-sm">{s.calendar_error}</p>}<div className="flex flex-wrap gap-2">{s.meet_url&&<Button asChild><a href={s.meet_url} target="_blank" rel="noreferrer">Join session</a></Button>}<Button variant="outline" onClick={()=>calendarDownload(s)}>Calendar download</Button>{s.calendar_state!=='synced'&&s.status!=='invited'&&<Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{await request({action:'retry_calendar',sessionId:s.id});await reload();})}>Refresh calendar details</Button>}</div>
 {s.reviewer_id===user.id&&s.status!=='cancelled'&&<Feedback session={s} onDone={()=>void run(reload)}/>} {s.founder_id===user.id&&s.feedback&&<details><summary className="cursor-pointer text-sm">Reviewer feedback</summary>{Object.entries({...s.pre_feedback,...s.feedback}).map(([k,v])=><p key={k} className="mt-2 text-sm"><strong>{labels[k]||k}</strong><br/>{String(v)}</p>)}<Link className="text-sm underline" to={`/pmf-lab?context=${s.context_id}`}>Review customer fit and add to PMF evidence</Link></details>}
 {['booked','invited'].includes(s.status)&&Date.parse(s.starts_at)>Date.now()&&<details><summary className="cursor-pointer text-sm">Change booking</summary><p className="text-xs">For CT reviewers, choose another slot they have made available. For invited customers, agree a new time with them first.</p><Input aria-label="New session time" type="datetime-local" value={changeTimes[s.id]||''} onChange={e=>setChangeTimes({...changeTimes,[s.id]:e.target.value})}/><div className="mt-2 flex gap-2"><Button variant="outline" disabled={busy||!changeTimes[s.id]} onClick={()=>void run(async()=>{await request({action:'reschedule',sessionId:s.id,startsAt:new Date(changeTimes[s.id]).toISOString()});await reload();})}>Reschedule</Button><Button variant="outline" disabled={busy} onClick={()=>void run(async()=>{await request({action:'cancel',sessionId:s.id});await reload();})}>Cancel session</Button></div></details>}
 <details><summary className="cursor-pointer text-sm">Report an issue</summary><Textarea aria-label="Session issue" value={disputes[s.id]||''} onChange={e=>setDisputes({...disputes,[s.id]:e.target.value})}/><Button disabled={busy||(disputes[s.id]?.trim().length||0)<10} onClick={()=>void run(async()=>{await request({action:'dispute',sessionId:s.id,reason:disputes[s.id]});await reload();toast.success('Issue recorded for review.');})}>Submit issue</Button></details></article>)}</section>
 </main>;
}
