import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Eye, Download } from "lucide-react";
import { useState } from "react";

const sampleReports = [
  {
    id: 1,
    title: "Local Coffee Shop",
    industry: "Food & Beverage",
    stage: "Explore",
    region: "US",
    description: "Neighborhood coffee shop with community focus",
    highlights: [
      "Validation through local surveys",
      "Instagram + community events strategy", 
      "Break-even in 8 months with $45K investment"
    ],
    preview: `# Launch Report: Roasted Dreams Coffee

## Executive Summary
Your neighborhood coffee shop concept shows strong potential with the growing demand for local, community-focused businesses. Success will depend on location validation, community building, and creating a unique experience beyond just coffee.

## Key Recommendations
• **Validation**: Survey 50 neighbors about coffee preferences and community space needs
• **Location**: Target areas with foot traffic but limited coffee options
• **Pricing**: $3-5 per drink, competitive with local market
• **Marketing**: Focus on Instagram stories, local partnerships, and community events

## 90-Day Launch Plan
Month 1: Location scouting and community surveys
Month 2: Permits, equipment, and supplier relationships  
Month 3: Soft launch with friends/family, then grand opening`
  },
  {
    id: 2,
    title: "SaaS Project Management Tool",
    industry: "Software",
    stage: "Build",
    region: "Global",
    description: "Team collaboration tool for remote teams",
    highlights: [
      "Freemium model with $19/user pricing",
      "LinkedIn + content marketing strategy",
      "Focus on remote team pain points"
    ],
    preview: `# Launch Report: TeamSync Pro

## Executive Summary
Your SaaS tool for remote team management addresses a critical need in the post-pandemic workplace. With proper positioning and execution, you can capture a share of the $4.8B project management software market.

## Key Recommendations  
• **MVP Features**: Focus on real-time collaboration, time tracking, and simple reporting
• **Pricing**: Freemium with $19/user/month premium tier
• **Target Market**: 10-50 person remote teams in tech and marketing agencies
• **Go-to-Market**: LinkedIn thought leadership + free tool content marketing

## Next Actions
1. Interview 20 remote team managers this week
2. Build landing page with email capture
3. Create free "Remote Team Health Check" tool for lead generation`
  },
  {
    id: 3,
    title: "Handmade Jewelry Business",
    industry: "E-commerce",
    stage: "Validate", 
    region: "Latin America",
    description: "Artisan jewelry with cultural designs",
    highlights: [
      "Instagram + WhatsApp sales strategy",
      "Focus on cultural storytelling",
      "Pre-orders to validate demand"
    ],
    preview: `# Launch Report: Luna Artesanal

## Executive Summary
Tu negocio de joyería artesanal tiene potencial fuerte en el mercado latino, especialmente con el crecimiento del e-commerce y la valoración de productos únicos y culturales.

## Recomendaciones Clave
• **Validación**: Crear 5 diseños únicos y hacer pre-ventas por WhatsApp
• **Precio**: $25-150 por pieza, dependiendo de materiales y complejidad  
• **Marketing**: Instagram con storytelling cultural + colaboraciones con influencers locales
• **Canales**: WhatsApp Business + Instagram Shopping + mercados locales

## Plan de 90 Días
Mes 1: Crear portafolio de 10 piezas y hacer 20 pre-ventas
Mes 2: Establecer proceso de producción y proveedores
Mes 3: Lanzamiento oficial con estrategia de redes sociales`
  }
];

const SampleReportGallery = () => {
  const [selectedReport, setSelectedReport] = useState<number | null>(null);

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h2 className="text-2xl font-bold mb-2">See What You'll Get</h2>
        <p className="text-muted-foreground">Real Launch Reports generated by BizMap AI</p>
      </div>

      <div className="grid md:grid-cols-3 gap-4">
        {sampleReports.map((report) => (
          <Card key={report.id} className="hover:shadow-lg transition-shadow cursor-pointer">
            <CardHeader className="pb-3">
              <div className="flex justify-between items-start mb-2">
                <Badge variant="secondary" className="text-xs">
                  {report.industry}
                </Badge>
                <Badge variant="outline" className="text-xs">
                  {report.stage}
                </Badge>
              </div>
              <CardTitle className="text-lg">{report.title}</CardTitle>
              <p className="text-sm text-muted-foreground">{report.description}</p>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <h4 className="text-sm font-medium">Key Highlights:</h4>
                <ul className="text-xs text-muted-foreground space-y-1">
                  {report.highlights.map((highlight, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <span className="w-1 h-1 rounded-full bg-primary mt-2 flex-shrink-0"></span>
                      {highlight}
                    </li>
                  ))}
                </ul>
              </div>
              
              <div className="pt-2 border-t">
                <Button
                  variant="outline"
                  size="sm"
                  className="w-full"
                  onClick={() => setSelectedReport(selectedReport === report.id ? null : report.id)}
                >
                  <Eye className="w-4 h-4 mr-2" />
                  {selectedReport === report.id ? "Hide Preview" : "View Preview"}
                </Button>
              </div>
            </CardContent>
            
            {selectedReport === report.id && (
              <CardContent className="pt-0">
                <div className="bg-muted/50 rounded-lg p-4 text-sm">
                  <div className="flex items-center gap-2 mb-3 text-muted-foreground">
                    <FileText className="w-4 h-4" />
                    <span className="text-xs">Sample Launch Report Preview</span>
                  </div>
                  <pre className="whitespace-pre-wrap text-xs leading-relaxed overflow-x-auto">
                    {report.preview}
                  </pre>
                  <div className="mt-3 pt-3 border-t border-border/50">
                    <p className="text-xs text-muted-foreground italic">
                      This is just a preview. Full reports include pricing analysis, marketing scripts, 
                      customer personas, and 90-day action plans.
                    </p>
                  </div>
                </div>
              </CardContent>
            )}
          </Card>
        ))}
      </div>

      <div className="text-center bg-muted/50 rounded-lg p-4">
        <p className="text-sm text-muted-foreground mb-2">
          <strong>2,847 business plans generated this month</strong>
        </p>
        <p className="text-xs text-muted-foreground">
          "This got me my first paying customer in 3 weeks" - Mike, SaaS founder
        </p>
      </div>
    </div>
  );
};

export default SampleReportGallery;