import { suggestDealStage } from '@/lib/coreToolsExperience';
import { captureEvent } from '@/lib/analytics';
import { useEffect, useMemo, useState, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { toast } from 'sonner';
import { campaignUrl,sourceFreshness } from '@/lib/coreTools';
import { summarizeConnectedResults,acquisitionCost,connectedFunnel,displayMoney,type Observation } from '@/lib/connectedResults';
import type { GTMPlanV2,GTMPipelineEntry } from '@/lib/gtmV2';

export default function ConnectedResults({productId,plan,onUpdatePlan,onUseMetric}:{productId:string;plan?:GTMPlanV2;onUpdatePlan?:(plan:GTMPlanV2)=>Promise<void>;onUseMetric?:(metric:string,value:number,sourceId:string,period?:{start:string;end:string})=>void}){
 const requestVersion=useRef(0);
 const [loading,setLoading]=useState(false);
 const [rows,setRows]=useState<Observation[]>([]),[evidence,setEvidence]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [from,setFrom]=useState(new Date(Date.now()-7*86400000).toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[campaign,setCampaign]=useState(''),[url,setUrl]=useState(''),[tracking,setTracking]=useState('');
 const [spend,setSpend]=useState(''),[hours,setHours]=useState(''),[newCustomers,setNewCustomers]=useState(''),[costComplete,setCostComplete]=useState(false),[attributed,setAttributed]=useState(false);
 const [assignedPlay,setAssignedPlay]=useState(''),[stages,setStages]=useState<Record<string,string>>({});
 async function reload(){const request=++requestVersion.current;if(!productId)return;setLoading(true);setError('');try{const [m,e]=await Promise.all([(supabase as any).from('ct_metric_observations').select('*').eq('product_id',productId).gte('period_end',from+'T00:00:00Z').lte('period_end',to+'T23:59:59.999Z').order('period_start',{ascending:false}).limit(1001),(supabase as any).from('ct_evidence').select('*').eq('product_id',productId).in('kind',['deal','contact','subscription','payment']).order('captured_at',{ascending:false}).limit(1001)]);if(request!==requestVersion.current)return;setLoading(false);if(m.error||e.error){setError('Could not load connected results. Retry after checking your connections.');return;}if(m.data.length>1000||e.data.length>1000){setError('More than 1,000 records match. Narrow the period or source before reviewing totals.');setRows([]);setEvidence([]);return;}setRows(m.data);setEvidence(e.data);}catch{if(request===requestVersion.current){setRows([]);setEvidence([]);setError('Could not load results. Check your connection and retry.');}}finally{if(request===requestVersion.current)setLoading(false);}}
 useEffect(()=>{setRows([]);setEvidence([]);setLoading(false);void reload();return()=>{requestVersion.current++;};},[productId,from,to]);
 const summary=useMemo(()=>summarizeConnectedResults(rows,from+'T00:00:00Z',to+'T23:59:59.999Z',campaign||undefined),[rows,from,to,campaign]);
 const funnel=connectedFunnel(evidence,campaign,from+'T00:00:00Z',to+'T23:59:59.999Z');
 const cac=acquisitionCost(spend===''?null:Number(spend),newCustomers===''?null:Number(newCustomers),costComplete,attributed);
 const subscriptions=evidence.filter(e=>e.kind==='subscription');
 const deals=evidence.filter(e=>e.kind==='deal'),contacts=evidence.filter(e=>e.kind==='contact');
 if(!productId)return null;
 const download=()=>{captureEvent('ct_connected_review_exported',{product_id:productId,observation_count:summary.observations.length});const blob=new Blob([JSON.stringify({productId,period:{from,to,timezone:'UTC'},summary,definitions:{net_payments:'Successful charges less refunds, grouped by charge date; not recognized revenue or MRR.',net_order_value:'Paid order value less refunds, grouped by order date.',attribution:'Only recorded campaign identifiers; no inferred joins.'},founderInputs:{spend,hours,newCustomers,costComplete,attributed,cac}},null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='ct-connected-weekly-review.json';link.click();URL.revokeObjectURL(link.href);};
 return <section className="space-y-4 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-semibold">Connected weekly results</h2><Button variant="outline" disabled={loading} onClick={()=>void reload()}>{loading ? 'Loading...' : 'Refresh'}</Button></div><div className="flex flex-wrap gap-3"><label className="text-sm">From (UTC)<Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-sm">Through (UTC)<Input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label>{plan&&<label className="text-sm">Campaign<select className="block rounded border bg-background p-2" value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">All campaigns and unknown sources</option>{plan.plays.map(p=><option key={p.id} value={p.id}>{p.channelName}</option>)}</select></label>}</div>
 {!loading&&!error&&!rows.length&&!evidence.length&&<p className="rounded-lg bg-muted p-3 text-sm">No connected results in this period. Accept an import in Connections, then refresh here. You can also record your experiment manually.</p>}{loading&&<p role="status" className="text-sm">Loading results for this product...</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="grid gap-3 sm:grid-cols-4">{[['Visits',summary.visits],['Key events',summary.keyEvents],['CRM contacts',campaign?null:contacts.length||null],['Paying customer IDs',summary.paidCustomers]].map(([label,value])=><div key={String(label)} className="rounded bg-muted p-3"><p className="text-xs">{label}</p><p className="text-xl font-semibold">{value??'Unknown'}</p></div>)}</div><p className="text-xs text-muted-foreground">Key events may include several actions by one person. CRM contacts are the current selected-source snapshot. Paying IDs are unique within each source and may overlap between providers. These totals do not establish a joined conversion funnel.</p>
 <div className="text-sm"><h3 className="font-medium">Net payments and order value</h3>{summary.revenue.length?summary.revenue.map(r=><p key={r.currency+r.unit}>{displayMoney(r.value,r.currency,r.unit)}</p>):<p>Unknown — connect billing or order data.</p>}<p className="text-xs text-muted-foreground">Successful payments less refunds, grouped by original payment/order date. Currencies and units stay separate. {summary.unattributed} payment records have unknown campaign attribution.</p></div>
 {subscriptions.length>0&&<div className="rounded border p-3 text-sm"><h3 className="font-medium">Subscription snapshot</h3><p>{subscriptions.filter(s=>s.original.status==='active').length} active ? {subscriptions.filter(s=>s.original.status==='trialing').length} trialing ? {subscriptions.filter(s=>s.original.canceled_at&&s.original.canceled_at*1000>=Date.parse(from)&&s.original.canceled_at*1000<=Date.parse(to+'T23:59:59Z')).length} canceled during this period</p><p className="text-xs text-muted-foreground">Latest imported subscription states. Cancellation counts do not establish a churn rate without a starting customer cohort.</p></div>}
 <div className="rounded border p-3 text-sm"><h3 className="font-medium">CRM to paid-customer funnel</h3><p>{funnel.leads} new contacts ? {funnel.qualified} currently qualified ? {funnel.matchedPaidCustomers} matched paying customer IDs</p><p className="text-xs text-muted-foreground">Matches require the same email in billing and exactly one CRM contact. Campaigns require a recorded tracking identifier. {funnel.unmatchedPayments} payments could not be joined. These are observed stages; a payment may come from a contact acquired before this period.</p></div>
 <details><summary className="cursor-pointer text-sm font-medium">Source observations, cohort charts and dates</summary><div className="mt-3 space-y-3">{rows.filter(r=>!campaign||r.definition.campaign===campaign).map(r=><article key={r.id} className="rounded border p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{r.metric.replace(/_/g,' ')}</strong><span>{r.value??'Unknown'}{r.denominator!=null?` / ${r.denominator}`:''}</span></div><p className="text-xs">{r.period_start.slice(0,10)}–{r.period_end.slice(0,10)} · {r.provenance} · {sourceFreshness(r.captured_at)} · Source checked {new Date(r.captured_at).toLocaleString()}</p>{r.status==='complete'&&(r.metric.startsWith('retention_')||r.metric.startsWith('activation_'))&&Number(r.denominator)>0&&<><progress className="w-full" max={Number(r.denominator)} value={Number(r.value)}/><p className="text-xs">{r.definition.startEvent} → {r.definition.returnEvent}, day {r.definition.windowDays}; {r.definition.returningWindow}</p></>}{onUseMetric&&r.status==='complete'&&!r.currency&&!r.metric.startsWith('retention_')&&r.value!=null&&<Button size="sm" variant="outline" onClick={()=>onUseMetric(r.metric,Number(r.value),r.id,{start:r.period_start,end:r.period_end})}>Review for an experiment</Button>}</article>)}</div></details>
 <details><summary className="cursor-pointer text-sm font-medium">Spend, founder time and acquisition cost</summary><div className="mt-3 grid gap-3 sm:grid-cols-3">{[['Cash spend',spend,setSpend],['Founder hours',hours,setHours],['New customers attributed in this period',newCustomers,setNewCustomers]].map(([label,value,setter])=><label key={String(label)} className="text-sm">{String(label)}<Input type="number" min="0" value={value as string} onChange={e=>(setter as (s:string)=>void)(e.target.value)}/></label>)}</div><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={costComplete} onChange={e=>setCostComplete(e.target.checked)}/>All acquisition cash costs for this period and campaign are included in one currency</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={attributed} onChange={e=>setAttributed(e.target.checked)}/>I checked that these are new, uniquely attributed customers in this period</label><p className="mt-2 text-sm">Acquisition cost: {cac==null?'Unknown — confirm cost coverage and customer attribution.':`${cac.toFixed(2)} per new customer (founder-confirmed estimate)`}. Founder hours are reported separately.</p></details>
 {plan&&<details><summary className="cursor-pointer text-sm font-medium">Campaign tracking link</summary><Input aria-label="Campaign destination URL" type="url" placeholder="https://your-product.com" value={url} onChange={e=>setUrl(e.target.value)}/><Button className="mt-2" variant="outline" disabled={!campaign||!url} onClick={()=>{try{setTracking(campaignUrl(url,plan.plays.find(p=>p.id===campaign)?.channelId||'',campaign));}catch(e){toast.error((e as Error).message);}}}>Create link for selected campaign</Button>{tracking&&<Input className="mt-2" readOnly aria-label="Campaign tracking URL" value={tracking} onFocus={e=>e.target.select()}/>}</details>}
 {plan&&onUpdatePlan&&deals.length>0&&<details><summary className="cursor-pointer text-sm font-medium">Review CRM opportunities ({deals.length})</summary><p className="text-xs">Choose the destination experiment. Recognized CRM stages are suggested; review the stage before adding each opportunity. Only USD amounts enter the existing USD pipeline totals; other amounts stay in source notes. Imported entries retain a source reference; later manual edits are founder supplied.</p><select aria-label="CRM destination play" className="my-2 w-full rounded border bg-background p-2" value={assignedPlay} onChange={e=>setAssignedPlay(e.target.value)}><option value="">Choose a channel experiment</option>{plan.plays.map(p=><option key={p.id} value={p.id}>{p.channelName}</option>)}</select>{deals.map(e=><div key={e.id} className="flex flex-wrap items-center gap-2 border-b py-2 text-sm"><span className="flex-1">{e.original.dealname||e.original.id} · Source stage: {e.original.dealstage} · {e.original.hs_analytics_source||'Unknown source'}</span><select aria-label={`Stage for ${e.original.dealname}`} value={stages[e.id]??suggestDealStage(e.original.dealstage||'')} onChange={event=>setStages({...stages,[e.id]:event.target.value})}><option value="">Map stage</option>{['lead','qualified','opportunity','customer','lost'].map(stage=><option key={stage}>{stage}</option>)}</select><Button size="sm" disabled={busy||!assignedPlay||!(stages[e.id]??suggestDealStage(e.original.dealstage||''))} onClick={async()=>{setBusy(true);try{const play=plan.plays.find(p=>p.id===assignedPlay)!;const entry:GTMPipelineEntry={id:e.id,playId:play.id,name:e.original.dealname||'CRM opportunity',stage:(stages[e.id]??suggestDealStage(e.original.dealstage||'')) as GTMPipelineEntry['stage'],value:e.original.deal_currency_code==='USD'?Math.max(0,Number(e.original.amount)||0):0,sourceChannelId:play.channelId,momentum:'active',occurredAt:e.captured_at.slice(0,10),notes:`Founder-mapped HubSpot evidence ${e.id}. Source attribution: ${e.original.hs_analytics_source||'unknown'}. Original amount: ${e.original.amount||'unknown'} ${e.original.deal_currency_code||'currency unknown'}; non-USD values are excluded from USD pipeline totals.`};await onUpdatePlan({...plan,pipeline:[...(plan.pipeline||[]).filter(p=>p.id!==entry.id),entry]});toast.success('CRM opportunity added to the pipeline.');}catch(err){toast.error((err as Error).message);}finally{setBusy(false);}}}>Add or update</Button></div>)}</details>}
 <Button variant="outline" onClick={download}>Download source-backed review</Button><p className="text-xs text-muted-foreground">Review changes against your previous experiment, add missing context, and record your decision in the weekly workspace.</p>
 </section>;
}
