import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { addDays, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameMonth, parseISO, startOfMonth, startOfWeek } from 'date-fns';
import { ArrowDown, ArrowRight, ArrowUp, CalendarDays, Check, CheckCircle2, ChevronLeft, ChevronRight, Circle, Clock3, ExternalLink, History, Inbox, ListTodo, Loader2, MoreHorizontal, Pencil, Plus, RefreshCw, Sparkles, Target, Trash2 } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Progress } from '@/components/ui/progress';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { useDailyTaskPlan, type TaskDraft } from '@/hooks/useDailyTaskPlan';
import { normalizePriority, type CalendarTaskRow, type TaskPriority } from '@/lib/taskCalendar';
import { getNextPlanItem, isPlatformRecommendation, taskEstimatedMinutes, type DailyTaskPlanItem, type TaskPlanView } from '@/lib/taskPlan';
import { cn } from '@/lib/utils';

const VIEW_OPTIONS: Array<{ key: TaskPlanView; label: string; icon: typeof ListTodo }> = [
  { key: 'today', label: 'Today', icon: Target },
  { key: 'upcoming', label: 'Upcoming', icon: CalendarDays },
  { key: 'backlog', label: 'Backlog', icon: Inbox },
  { key: 'history', label: 'History', icon: History },
];

function TaskCheck({ completed, label, disabled, onClick, large = false }: { completed: boolean; label: string; disabled: boolean; onClick: () => void; large?: boolean }) {
  return <button type="button" disabled={disabled} onClick={onClick} aria-label={completed ? `Mark ${label} incomplete` : `Complete ${label}`} className={cn('flex shrink-0 items-center justify-center rounded-full border transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring', large ? 'h-9 w-9' : 'h-6 w-6', completed ? 'border-primary bg-primary text-primary-foreground' : 'border-muted-foreground/40 bg-background hover:border-primary hover:bg-primary/5')}>{completed ? <Check className={large ? 'h-5 w-5' : 'h-3.5 w-3.5'} /> : null}</button>;
}

function TaskEditor({ task, open, onOpenChange, onSave, isSaving }: { task: CalendarTaskRow | null; open: boolean; onOpenChange: (open: boolean) => void; onSave: (draft: TaskDraft) => Promise<boolean>; isSaving: boolean }) {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [date, setDate] = useState(format(new Date(), 'yyyy-MM-dd'));
  const [priority, setPriority] = useState<TaskPriority>('medium');
  const [minutes, setMinutes] = useState(15);
  useEffect(() => {
    if (!open) return;
    setTitle(task?.task_text ?? ''); setDescription(task?.task_description ?? '');
    setDate(task?.task_date ?? format(new Date(), 'yyyy-MM-dd'));
    setPriority(normalizePriority(task?.priority)); setMinutes(task ? taskEstimatedMinutes(task) : 15);
  }, [open, task]);
  const save = async () => { const ok = await onSave({ title, description, date, priority, estimatedMinutes: minutes }); if (ok) onOpenChange(false); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{task ? 'Edit task' : 'Add task'}</DialogTitle><DialogDescription>Keep the action concrete and small enough to finish.</DialogDescription></DialogHeader><div className="space-y-4 py-2"><div className="space-y-2"><Label htmlFor="task-edit-title">Task</Label><Input id="task-edit-title" autoFocus value={title} onChange={(event) => setTitle(event.target.value)} /></div><div className="space-y-2"><Label htmlFor="task-edit-description">Details</Label><Textarea id="task-edit-description" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Optional context" /></div><div className="grid gap-4 sm:grid-cols-3"><div className="space-y-2"><Label htmlFor="task-edit-date">Date</Label><Input id="task-edit-date" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></div><div className="space-y-2"><Label>Priority</Label><Select value={priority} onValueChange={(value) => setPriority(value as TaskPriority)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="low">Low</SelectItem><SelectItem value="medium">Medium</SelectItem><SelectItem value="high">High</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label htmlFor="task-edit-minutes">Minutes</Label><Input id="task-edit-minutes" type="number" min={5} max={240} step={5} value={minutes} onChange={(event) => setMinutes(Number(event.target.value) || 15)} /></div></div></div><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button onClick={() => void save()} disabled={!title.trim() || !date || isSaving}>{isSaving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}Save</Button></DialogFooter></DialogContent></Dialog>;
}

type RecAction = 'make_next' | 'snooze' | 'replace' | 'not_relevant';

function RecommendationMenu({ item, index, total, disabled, onAction, onEdit, onMove }: { item: DailyTaskPlanItem; index: number; total: number; disabled: boolean; onAction: (action: RecAction) => void; onEdit: () => void; onMove: (direction: -1 | 1) => void }) {
  return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="h-9 w-9 text-muted-foreground" disabled={disabled} aria-label={`Manage ${item.task.task_text}`}><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52">{index > 0 ? <DropdownMenuItem onClick={() => onAction('make_next')}><Target className="mr-2 h-4 w-4" />Make next</DropdownMenuItem> : null}<DropdownMenuItem onClick={onEdit}><Pencil className="mr-2 h-4 w-4" />Edit</DropdownMenuItem><DropdownMenuItem onClick={onEdit}><CalendarDays className="mr-2 h-4 w-4" />Reschedule…</DropdownMenuItem><DropdownMenuItem disabled={index === 0} onClick={() => onMove(-1)}><ArrowUp className="mr-2 h-4 w-4" />Move up</DropdownMenuItem><DropdownMenuItem disabled={index === total - 1} onClick={() => onMove(1)}><ArrowDown className="mr-2 h-4 w-4" />Move down</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem onClick={() => onAction('snooze')}><Clock3 className="mr-2 h-4 w-4" />Snooze until tomorrow</DropdownMenuItem><DropdownMenuItem onClick={() => onAction('replace')}><RefreshCw className="mr-2 h-4 w-4" />Replace task</DropdownMenuItem><DropdownMenuItem className="text-destructive focus:text-destructive" onClick={() => onAction('not_relevant')}>Not relevant</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
}

function NextActionCard({ item, disabled, onComplete, onOpenEdit, onAction }: { item: DailyTaskPlanItem; disabled: boolean; onComplete: () => void; onOpenEdit: () => void; onAction: (action: RecAction) => void }) {
  const task = item.task; const impact = Math.round(Number(item.scoreBreakdown?.impact ?? task.business_impact_score ?? 7));
  return <Card id={`task-${task.id}`} className="overflow-hidden border-primary/30 bg-gradient-to-br from-primary/[0.09] via-card to-card shadow-sm"><CardContent className="p-5 sm:p-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm font-semibold text-primary"><Sparkles className="h-4 w-4" />Do this next</div><RecommendationMenu item={item} index={0} total={1} disabled={disabled} onAction={onAction} onEdit={onOpenEdit} onMove={() => undefined} /></div><div className="mt-5 flex items-start gap-4"><TaskCheck large completed={Boolean(task.is_completed)} label={task.task_text} disabled={disabled} onClick={onComplete} /><div className="min-w-0 flex-1"><h2 className="text-xl font-semibold tracking-tight sm:text-2xl">{task.task_text}</h2>{task.task_description ? <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{task.task_description}</p> : null}<div className="mt-4 rounded-xl border border-primary/15 bg-background/70 p-3 text-sm"><span className="font-medium">Why now: </span><span className="text-muted-foreground">{task.recommendation_reason || item.selectionReason || 'This is the strongest available next action for your current progress.'}</span></div><div className="mt-4 flex flex-wrap items-center gap-2"><Badge variant="secondary"><Clock3 className="mr-1 h-3.5 w-3.5" />{taskEstimatedMinutes(task)} min</Badge><Badge variant="secondary">Impact {impact}/10</Badge><Badge variant="outline" className="capitalize">{normalizePriority(task.priority)} priority</Badge>{item.carriedForward ? <Badge variant="outline">Carried forward</Badge> : null}</div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={onComplete} disabled={disabled}><CheckCircle2 className="mr-2 h-4 w-4" />Mark complete</Button>{task.source_route ? <Button variant="outline" asChild><Link to={task.source_route}>Open workspace<ArrowRight className="ml-2 h-4 w-4" /></Link></Button> : null}</div></div></div></CardContent></Card>;
}

function RecommendationRow({ item, index, total, disabled, onComplete, onEdit, onAction, onMove }: { item: DailyTaskPlanItem; index: number; total: number; disabled: boolean; onComplete: () => void; onEdit: () => void; onAction: (action: RecAction) => void; onMove: (direction: -1 | 1) => void }) {
  const task = item.task;
  return <div id={`task-${task.id}`} className={cn('flex items-start gap-3 px-4 py-4 sm:px-5', task.is_completed && 'bg-muted/25')}><TaskCheck completed={Boolean(task.is_completed)} label={task.task_text} disabled={disabled} onClick={onComplete} /><div className="min-w-0 flex-1"><p className={cn('text-sm font-medium', task.is_completed && 'text-muted-foreground line-through')}>{task.task_text}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{task.recommendation_reason || item.selectionReason}</p><div className="mt-2 flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><span>{taskEstimatedMinutes(task)} min</span><span>•</span><span className="capitalize">{normalizePriority(task.priority)} impact</span>{task.source_route ? <><span>•</span><Link className="inline-flex items-center gap-1 text-primary hover:underline" to={task.source_route}>Open<ExternalLink className="h-3 w-3" /></Link></> : null}</div></div><RecommendationMenu item={item} index={index} total={total} disabled={disabled} onAction={onAction} onEdit={onEdit} onMove={onMove} /></div>;
}

function ManualTaskRow({ task, disabled, onToggle, onEdit, onDelete }: { task: CalendarTaskRow; disabled: boolean; onToggle: () => void; onEdit: () => void; onDelete: () => void }) {
  return <div id={`task-${task.id}`} className="flex items-start gap-3 border-b px-4 py-3.5 last:border-b-0 sm:px-5"><TaskCheck completed={Boolean(task.is_completed)} label={task.task_text} disabled={disabled} onClick={onToggle} /><div className="min-w-0 flex-1"><p className={cn('text-sm font-medium', task.is_completed && 'text-muted-foreground line-through')}>{task.task_text}</p><p className="mt-1 text-xs text-muted-foreground">{format(parseISO(`${task.task_date}T00:00:00`), 'MMM d')} · {normalizePriority(task.priority)} · {taskEstimatedMinutes(task)} min</p></div><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost" className="h-9 w-9" aria-label={`Manage ${task.task_text}`}><MoreHorizontal className="h-4 w-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={onEdit}><Pencil className="mr-2 h-4 w-4" />Edit</DropdownMenuItem>{!isPlatformRecommendation(task) ? <DropdownMenuItem className="text-destructive focus:text-destructive" onClick={onDelete}><Trash2 className="mr-2 h-4 w-4" />Delete</DropdownMenuItem> : null}</DropdownMenuContent></DropdownMenu></div>;
}

function HistoryCalendar({ tasks }: { tasks: CalendarTaskRow[] }) {
  const [month, setMonth] = useState(startOfMonth(new Date()));
  const days = eachDayOfInterval({ start: startOfWeek(startOfMonth(month), { weekStartsOn: 1 }), end: endOfWeek(endOfMonth(month), { weekStartsOn: 1 }) });
  const counts = useMemo(() => tasks.reduce<Record<string, number>>((acc, task) => { acc[task.task_date] = (acc[task.task_date] ?? 0) + 1; return acc; }, {}), [tasks]);
  return <Card className="mb-4"><CardContent className="p-4"><div className="mb-4 flex items-center justify-between"><Button variant="ghost" size="icon" onClick={() => setMonth((current) => addDays(startOfMonth(current), -1))}><ChevronLeft className="h-4 w-4" /></Button><p className="font-medium">{format(month, 'MMMM yyyy')}</p><Button variant="ghost" size="icon" onClick={() => setMonth((current) => addDays(endOfMonth(current), 1))}><ChevronRight className="h-4 w-4" /></Button></div><div className="grid grid-cols-7 gap-1 text-center text-xs text-muted-foreground">{['M','T','W','T','F','S','S'].map((label, index) => <span key={`${label}-${index}`}>{label}</span>)}{days.map((day) => { const key = format(day, 'yyyy-MM-dd'); const count = counts[key] ?? 0; return <div key={key} className={cn('relative mt-1 flex h-9 items-center justify-center rounded-lg text-sm text-foreground', !isSameMonth(day, month) && 'text-muted-foreground/40', count && 'bg-primary/10 font-medium text-primary')}>{format(day, 'd')}{count ? <span className="absolute bottom-1 h-1 w-1 rounded-full bg-primary" /> : null}</div>; })}</div></CardContent></Card>;
}

export function TaskTodayWorkspace() {
  const engine = useDailyTaskPlan(); const [searchParams] = useSearchParams();
  const [quickTitle, setQuickTitle] = useState(''); const [editingTask, setEditingTask] = useState<CalendarTaskRow | null>(null); const [editorOpen, setEditorOpen] = useState(false); const deepLinkHandled = useRef(false);
  const nextItem = getNextPlanItem(engine.planItems); const remaining = engine.planItems.filter((item) => item.task.id !== nextItem?.task.id);
  useEffect(() => {
    if (deepLinkHandled.current || engine.isLoading) return;
    deepLinkHandled.current = true;
    const date = searchParams.get('date'); const taskId = searchParams.get('task');
    if (taskId) {
      void engine.openDeepLinkTask(taskId, date).then(() => window.setTimeout(() => document.getElementById(`task-${taskId}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' }), 50));
    } else if (date && date < engine.today) engine.selectView('backlog');
    else if (date && date > engine.today) engine.selectView('upcoming');
  }, [engine, searchParams]);
  const quickAdd = async (event: FormEvent) => { event.preventDefault(); if (!quickTitle.trim()) return; const ok = await engine.createManualTask({ title: quickTitle, date: engine.today }); if (ok) setQuickTitle(''); };
  const saveEditor = async (draft: TaskDraft) => { if (!editingTask) return engine.createManualTask(draft); if (isPlatformRecommendation(editingTask)) { const edited = await engine.mutateRecommendation(editingTask.id, 'edit', { title: draft.title, description: draft.description, priority: draft.priority, estimatedMinutes: draft.estimatedMinutes }); if (!edited) return false; if (draft.date !== editingTask.task_date) return engine.mutateRecommendation(editingTask.id, 'reschedule', { date: draft.date }); return true; } return engine.updateTask(editingTask, { task_text: draft.title, task_description: draft.description || null, task_date: draft.date, priority: draft.priority, estimated_minutes: draft.estimatedMinutes }); };
  const openEditor = (task: CalendarTaskRow | null) => { setEditingTask(task); setEditorOpen(true); };
  const recommendationAction = (item: DailyTaskPlanItem, action: RecAction) => { const actionPayload = action === 'snooze' ? { date: format(addDays(new Date(), 1), 'yyyy-MM-dd') } : {}; void engine.mutateRecommendation(item.task.id, action, actionPayload); };
  const toggleManual = (task: CalendarTaskRow) => void engine.updateTask(task, { is_completed: !task.is_completed, completed_at: !task.is_completed ? new Date().toISOString() : null });
  if (engine.isLoading) return <div className="mx-auto flex min-h-72 max-w-5xl items-center justify-center gap-3 text-sm text-muted-foreground"><Loader2 className="h-5 w-5 animate-spin" />Preparing today’s plan…</div>;
  return <div className="mx-auto max-w-5xl space-y-6 pb-12">
    <header className="space-y-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-sm font-medium text-primary"><ListTodo className="h-4 w-4" />Founder focus</div><h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">What matters today.</h1><p className="mt-2 text-sm text-muted-foreground">{format(new Date(), 'EEEE, MMMM d')} · Three actions chosen from your stage, goals, and progress.</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant="secondary" className="px-3 py-1.5">{engine.progress.completed}/{engine.progress.total || 3} complete</Badge>{engine.overdue.length ? <Badge variant="destructive" className="px-3 py-1.5">{engine.overdue.length} overdue</Badge> : null}</div></div><form onSubmit={quickAdd} className="flex flex-col gap-2 rounded-xl border bg-card p-2 shadow-sm sm:flex-row"><div className="flex min-w-0 flex-1 items-center gap-2 px-2"><Plus className="h-4 w-4 text-primary" /><Input value={quickTitle} onChange={(event) => setQuickTitle(event.target.value)} placeholder="Add a task for today…" className="h-11 border-0 bg-transparent px-0 shadow-none focus-visible:ring-0" /></div><Button type="submit" disabled={!quickTitle.trim() || engine.isMutating}>Add task</Button><Button type="button" variant="ghost" onClick={() => openEditor(null)}>More details</Button></form></header>
    <nav className="flex gap-1 overflow-x-auto rounded-xl bg-muted/60 p-1" aria-label="Task views">{VIEW_OPTIONS.map((option) => { const Icon = option.icon; return <button key={option.key} type="button" onClick={() => engine.selectView(option.key)} className={cn('flex min-w-fit flex-1 items-center justify-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-colors', engine.listView === option.key ? 'bg-background text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground')}><Icon className="h-4 w-4" />{option.label}</button>; })}</nav>
    {engine.listView === 'today' ? <div className="space-y-6">
      {engine.error ? <Card className="border-destructive/30"><CardContent className="flex items-center justify-between gap-3 p-4"><p className="text-sm text-destructive">{engine.error}</p><Button size="sm" variant="outline" onClick={() => void engine.loadPlan()}><RefreshCw className="mr-2 h-4 w-4" />Retry</Button></CardContent></Card> : null}
      {engine.baseComplete ? <Card className="border-success/30 bg-success/[0.07]"><CardContent className="flex flex-col gap-4 p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><span className="rounded-full bg-success/15 p-2 text-success"><CheckCircle2 className="h-5 w-5" /></span><div><h2 className="font-semibold">Today’s essential work is complete.</h2><p className="mt-1 text-sm text-muted-foreground">You can stop with a clean slate or ask for one more useful action.</p></div></div><Button variant="outline" onClick={() => void engine.addNextTask()} disabled={engine.isMutating}>Keep going<ArrowRight className="ml-2 h-4 w-4" /></Button></CardContent></Card> : null}
      {nextItem ? <NextActionCard item={nextItem} disabled={engine.isMutating} onComplete={() => void engine.mutateRecommendation(nextItem.task.id, nextItem.task.is_completed ? 'reopen' : 'complete')} onOpenEdit={() => openEditor(nextItem.task)} onAction={(action) => recommendationAction(nextItem, action)} /> : null}
      {remaining.length ? <Card className="overflow-hidden"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="font-semibold">Today’s plan</h2><p className="mt-1 text-xs text-muted-foreground">Ordered by impact, urgency, and relevance.</p></div><Progress value={engine.progress.percentage} className="h-2 w-24" /></div><div className="divide-y">{remaining.map((item) => { const actualIndex = engine.planItems.findIndex((candidate) => candidate.task.id === item.task.id); return <RecommendationRow key={item.id} item={item} index={actualIndex} total={engine.planItems.length} disabled={engine.isMutating} onComplete={() => void engine.mutateRecommendation(item.task.id, item.task.is_completed ? 'reopen' : 'complete')} onEdit={() => openEditor(item.task)} onAction={(action) => recommendationAction(item, action)} onMove={(direction) => void engine.reorderRecommendation(item.task.id, direction)} />; })}</div></Card> : null}
      {engine.manualToday.length ? <Card className="overflow-hidden"><div className="border-b px-5 py-4"><h2 className="font-semibold">Your tasks</h2><p className="mt-1 text-xs text-muted-foreground">Founder-created work is separate from the three recommendations.</p></div>{engine.manualToday.map((task) => <ManualTaskRow key={task.id} task={task} disabled={engine.isMutating} onToggle={() => toggleManual(task)} onEdit={() => openEditor(task)} onDelete={() => void engine.deleteManualTask(task)} />)}</Card> : null}
      {engine.overdue.length ? <Card className="overflow-hidden border-warning/30"><div className="border-b px-5 py-4"><h2 className="font-semibold">Needs a decision</h2><p className="mt-1 text-xs text-muted-foreground">Complete, edit, or reschedule overdue work—none of it reduces today’s recommendation quota.</p></div>{engine.overdue.slice(0, 6).map((task) => <ManualTaskRow key={task.id} task={task} disabled={engine.isMutating} onToggle={() => isPlatformRecommendation(task) ? void engine.mutateRecommendation(task.id, 'complete') : toggleManual(task)} onEdit={() => openEditor(task)} onDelete={() => void engine.deleteManualTask(task)} />)}</Card> : null}
    </div> : <section>{engine.listView === 'history' ? <HistoryCalendar tasks={engine.listTasks} /> : null}<Card className="overflow-hidden"><div className="border-b px-5 py-4"><h2 className="font-semibold capitalize">{engine.listView}</h2><p className="mt-1 text-xs text-muted-foreground">{engine.listView === 'upcoming' ? 'Planned work after today.' : engine.listView === 'backlog' ? 'Unfinished work that needs a decision.' : 'Completed work and momentum over time.'}</p></div>{engine.isListLoading && !engine.listTasks.length ? <div className="flex items-center justify-center gap-2 p-10 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />Loading tasks…</div> : engine.listTasks.length ? engine.listTasks.map((task) => <ManualTaskRow key={task.id} task={task} disabled={engine.isMutating} onToggle={() => isPlatformRecommendation(task) ? void engine.mutateRecommendation(task.id, task.is_completed ? 'reopen' : 'complete') : toggleManual(task)} onEdit={() => openEditor(task)} onDelete={() => void engine.deleteManualTask(task)} />) : <div className="p-10 text-center"><Circle className="mx-auto h-8 w-8 text-muted-foreground/50" /><p className="mt-3 text-sm font-medium">Nothing here yet</p><p className="mt-1 text-sm text-muted-foreground">This view will fill as you plan and complete work.</p></div>}{engine.hasMore ? <div className="border-t p-3 text-center"><Button variant="ghost" onClick={() => void engine.loadMore()} disabled={engine.isListLoading}>{engine.isListLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}Load more</Button></div> : null}</Card></section>}
    <TaskEditor task={editingTask} open={editorOpen} onOpenChange={setEditorOpen} onSave={saveEditor} isSaving={engine.isMutating} />
  </div>;
}
