-- ================================================
-- INVESTOR MATCHING ENGINE - SEED INITIAL INVESTORS
-- Curated list of 30+ investors for MVP
-- ================================================

-- Seed investors (idempotent - safe to run multiple times)
INSERT INTO public.investors (
  name, firm_name, firm_website, industries, investment_stages,
  typical_check_size_min, typical_check_size_max,
  geographic_focus, locations, remote_friendly,
  investment_thesis, portfolio_companies,
  contact_preference, is_featured, is_active
) VALUES

-- Pre-seed & Seed Stage Investors
('Y Combinator', 'Y Combinator', 'https://www.ycombinator.com', 
 ARRAY['SaaS', 'AI', 'Fintech', 'E-commerce', 'Healthcare'], 
 ARRAY['pre-seed', 'seed'], 
 125000, 500000,
 ARRAY['US', 'Global'], ARRAY['San Francisco', 'Remote'], true,
 'We fund startups at the earliest stages. We look for great founders with bold ideas and a bias toward building products users love.',
 '[{"name": "Stripe", "industry": "Fintech"}, {"name": "Airbnb", "industry": "E-commerce"}, {"name": "Dropbox", "industry": "SaaS"}]'::jsonb,
 'application', true, true),

('Techstars', 'Techstars', 'https://www.techstars.com',
 ARRAY['SaaS', 'AI', 'Fintech', 'E-commerce', 'Healthcare'],
 ARRAY['pre-seed', 'seed'],
 20000, 120000,
 ARRAY['US', 'Global'], ARRAY['Boulder', 'New York', 'Boston', 'Remote'], true,
 'We help entrepreneurs succeed by connecting them with mentors, investors, and resources.',
 '[{"name": "SendGrid", "industry": "SaaS"}, {"name": "DigitalOcean", "industry": "SaaS"}]'::jsonb,
 'application', true, true),

('500 Startups', '500 Startups', 'https://500.co',
 ARRAY['SaaS', 'AI', 'Fintech', 'E-commerce', 'Marketplace'],
 ARRAY['pre-seed', 'seed'],
 100000, 250000,
 ARRAY['US', 'Global'], ARRAY['San Francisco', 'Remote'], true,
 'We invest in early-stage startups with strong potential for growth.',
 '[{"name": "Canva", "industry": "SaaS"}, {"name": "Credit Karma", "industry": "Fintech"}]'::jsonb,
 'application', true, true),

('First Round Capital', 'First Round Capital', 'https://firstround.com',
 ARRAY['SaaS', 'AI', 'E-commerce', 'Marketplace'],
 ARRAY['pre-seed', 'seed'],
 500000, 1000000,
 ARRAY['US'], ARRAY['San Francisco', 'New York'], false,
 'We partner with entrepreneurs at the very beginning to help them build the best companies.',
 '[{"name": "Square", "industry": "Fintech"}, {"name": "Roblox", "industry": "Gaming"}]'::jsonb,
 'warm-intro-only', true, true),

('Andreessen Horowitz', 'Andreessen Horowitz', 'https://a16z.com',
 ARRAY['SaaS', 'AI', 'Fintech', 'Crypto', 'Enterprise'],
 ARRAY['seed', 'series-a'],
 1000000, 5000000,
 ARRAY['US'], ARRAY['Menlo Park'], false,
 'We invest in bold entrepreneurs who are building the future through technology.',
 '[{"name": "Coinbase", "industry": "Crypto"}, {"name": "GitHub", "industry": "SaaS"}]'::jsonb,
 'warm-intro-only', true, true),

('Sequoia Capital', 'Sequoia Capital', 'https://www.sequoiacap.com',
 ARRAY['SaaS', 'AI', 'Enterprise', 'Healthcare'],
 ARRAY['seed', 'series-a', 'series-b'],
 2000000, 10000000,
 ARRAY['US', 'Global'], ARRAY['Menlo Park', 'San Francisco'], false,
 'We help build legendary companies from idea to IPO and beyond.',
 '[{"name": "Apple", "industry": "Hardware"}, {"name": "Google", "industry": "AI"}]'::jsonb,
 'warm-intro-only', true, true),

('Accel Partners', 'Accel', 'https://www.accel.com',
 ARRAY['SaaS', 'Enterprise', 'Healthcare', 'Fintech'],
 ARRAY['seed', 'series-a'],
 1000000, 5000000,
 ARRAY['US', 'Global'], ARRAY['Palo Alto', 'London'], false,
 'We partner with exceptional founders from seed to growth stage.',
 '[{"name": "Facebook", "industry": "Social"}, {"name": "Slack", "industry": "SaaS"}]'::jsonb,
 'warm-intro-only', true, true),

('Greylock Partners', 'Greylock Partners', 'https://greylock.com',
 ARRAY['SaaS', 'Enterprise', 'AI'],
 ARRAY['seed', 'series-a'],
 1000000, 3000000,
 ARRAY['US'], ARRAY['Menlo Park'], false,
 'We partner with entrepreneurs to help them build category-defining companies.',
 '[{"name": "LinkedIn", "industry": "SaaS"}, {"name": "Palo Alto Networks", "industry": "Security"}]'::jsonb,
 'warm-intro-only', true, true),

('Index Ventures', 'Index Ventures', 'https://www.indexventures.com',
 ARRAY['SaaS', 'E-commerce', 'Marketplace', 'Gaming'],
 ARRAY['seed', 'series-a'],
 500000, 3000000,
 ARRAY['US', 'Europe'], ARRAY['San Francisco', 'London'], false,
 'We back exceptional entrepreneurs building global companies.',
 '[{"name": "Dropbox", "industry": "SaaS"}, {"name": "Etsy", "industry": "E-commerce"}]'::jsonb,
 'warm-intro-only', true, true),

('Benchmark', 'Benchmark', 'https://www.benchmark.com',
 ARRAY['SaaS', 'Marketplace', 'E-commerce'],
 ARRAY['seed', 'series-a'],
 1000000, 5000000,
 ARRAY['US'], ARRAY['San Francisco'], false,
 'We invest early in great entrepreneurs building great products.',
 '[{"name": "Twitter", "industry": "Social"}, {"name": "Uber", "industry": "Marketplace"}]'::jsonb,
 'warm-intro-only', true, true),

-- Emerging/Newer VCs
('Union Square Ventures', 'Union Square Ventures', 'https://www.usv.com',
 ARRAY['SaaS', 'Marketplace', 'Crypto'],
 ARRAY['pre-seed', 'seed'],
 250000, 1500000,
 ARRAY['US'], ARRAY['New York'], false,
 'We invest in networks, platforms, and protocols.',
 '[{"name": "Twitter", "industry": "Social"}, {"name": "Coinbase", "industry": "Crypto"}]'::jsonb,
 'warm-intro-only', false, true),

('Spark Capital', 'Spark Capital', 'https://www.sparkcapital.com',
 ARRAY['SaaS', 'E-commerce', 'Marketplace'],
 ARRAY['seed', 'series-a'],
 500000, 2000000,
 ARRAY['US'], ARRAY['Boston', 'San Francisco'], false,
 'We invest in companies that change the way we live and work.',
 '[{"name": "Twitter", "industry": "Social"}, {"name": "Oculus", "industry": "Gaming"}]'::jsonb,
 'warm-intro-only', false, true),

('General Catalyst', 'General Catalyst', 'https://www.generalcatalyst.com',
 ARRAY['Enterprise', 'Healthcare', 'Fintech'],
 ARRAY['seed', 'series-a'],
 1000000, 5000000,
 ARRAY['US'], ARRAY['Boston', 'San Francisco'], false,
 'We partner with entrepreneurs to build innovative companies.',
 '[{"name": "Snapchat", "industry": "Social"}, {"name": "Stripe", "industry": "Fintech"}]'::jsonb,
 'warm-intro-only', false, true),

('Founders Fund', 'Founders Fund', 'https://foundersfund.com',
 ARRAY['AI', 'Space', 'Biotech', 'Deep Tech'],
 ARRAY['seed', 'series-a'],
 1000000, 5000000,
 ARRAY['US'], ARRAY['San Francisco'], false,
 'We invest in companies solving problems through innovative technology.',
 '[{"name": "SpaceX", "industry": "Space"}, {"name": "Palantir", "industry": "AI"}]'::jsonb,
 'warm-intro-only', false, true),

('Lightspeed Venture Partners', 'Lightspeed Venture Partners', 'https://lsvp.com',
 ARRAY['Enterprise', 'SaaS', 'Fintech'],
 ARRAY['seed', 'series-a'],
 500000, 3000000,
 ARRAY['US', 'Global'], ARRAY['Menlo Park', 'Remote'], true,
 'We partner with exceptional entrepreneurs to build market-leading companies.',
 '[{"name": "Snapchat", "industry": "Social"}, {"name": "Nutanix", "industry": "Enterprise"}]'::jsonb,
 'warm-intro-only', false, true),

('Khosla Ventures', 'Khosla Ventures', 'https://www.khoslaventures.com',
 ARRAY['AI', 'Healthcare', 'Energy', 'Deep Tech'],
 ARRAY['seed', 'series-a'],
 1000000, 5000000,
 ARRAY['US'], ARRAY['Menlo Park'], false,
 'We invest in breakthrough technologies that solve big problems.',
 '[{"name": "Square", "industry": "Fintech"}, {"name": "Okta", "industry": "Security"}]'::jsonb,
 'warm-intro-only', false, true),

-- Pre-seed Focused
('Precursor Ventures', 'Precursor Ventures', 'https://www.precursorvc.com',
 ARRAY['SaaS', 'E-commerce', 'Marketplace'],
 ARRAY['pre-seed'],
 25000, 100000,
 ARRAY['US'], ARRAY['San Francisco', 'Remote'], true,
 'We invest in pre-seed stage startups with ambitious founders.',
 '[]'::jsonb,
 'email', false, true),

('Hustle Fund', 'Hustle Fund', 'https://www.hustlefund.vc',
 ARRAY['SaaS', 'E-commerce', 'Marketplace', 'AI'],
 ARRAY['pre-seed'],
 25000, 100000,
 ARRAY['US', 'Global'], ARRAY['Remote'], true,
 'We make fast, small investments in early-stage startups.',
 '[]'::jsonb,
 'email', false, true),

('Day One Ventures', 'Day One Ventures', 'https://www.dayoneventures.com',
 ARRAY['SaaS', 'AI', 'Fintech'],
 ARRAY['pre-seed', 'seed'],
 50000, 200000,
 ARRAY['US', 'Global'], ARRAY['Remote'], true,
 'We back exceptional founders from day one.',
 '[]'::jsonb,
 'email', false, true),

-- Industry-Specific
('F-Prime Capital', 'F-Prime Capital', 'https://www.fprimecapital.com',
 ARRAY['Healthcare', 'Biotech', 'Life Sciences'],
 ARRAY['seed', 'series-a'],
 1000000, 5000000,
 ARRAY['US'], ARRAY['Boston', 'San Francisco'], false,
 'We invest in healthcare and technology companies.',
 '[]'::jsonb,
 'warm-intro-only', false, true),

('Insight Partners', 'Insight Partners', 'https://www.insightpartners.com',
 ARRAY['Enterprise', 'SaaS'],
 ARRAY['series-a', 'series-b'],
 5000000, 20000000,
 ARRAY['US', 'Global'], ARRAY['New York', 'Remote'], true,
 'We scale software companies to their full potential.',
 '[{"name": "Twitter", "industry": "Social"}, {"name": "Shopify", "industry": "E-commerce"}]'::jsonb,
 'warm-intro-only', false, true),

('NEA (New Enterprise Associates)', 'NEA', 'https://www.nea.com',
 ARRAY['Enterprise', 'Healthcare', 'Biotech'],
 ARRAY['seed', 'series-a', 'series-b'],
 2000000, 10000000,
 ARRAY['US'], ARRAY['Menlo Park', 'Chevy Chase'], false,
 'We partner with entrepreneurs to build transformational businesses.',
 '[]'::jsonb,
 'warm-intro-only', false, true),

('Bessemer Venture Partners', 'Bessemer Venture Partners', 'https://www.bvp.com',
 ARRAY['Enterprise', 'SaaS', 'Cloud'],
 ARRAY['seed', 'series-a'],
 1000000, 5000000,
 ARRAY['US', 'Global'], ARRAY['San Francisco', 'New York'], false,
 'We partner with entrepreneurs to build enduring companies.',
 '[{"name": "Pinterest", "industry": "Social"}, {"name": "LinkedIn", "industry": "SaaS"}]'::jsonb,
 'warm-intro-only', false, true),

-- Geographic Focus
('Atomico', 'Atomico', 'https://www.atomico.com',
 ARRAY['SaaS', 'E-commerce', 'Marketplace'],
 ARRAY['seed', 'series-a'],
 500000, 3000000,
 ARRAY['Europe'], ARRAY['London'], false,
 'We invest in ambitious European startups.',
 '[]'::jsonb,
 'warm-intro-only', false, true),

('LocalGlobe', 'LocalGlobe', 'https://www.localglobe.vc',
 ARRAY['SaaS', 'E-commerce', 'Marketplace'],
 ARRAY['pre-seed', 'seed'],
 100000, 500000,
 ARRAY['UK', 'Europe'], ARRAY['London'], false,
 'We back exceptional founders in the UK and Europe.',
 '[]'::jsonb,
 'warm-intro-only', false, true),

('Cherry Ventures', 'Cherry Ventures', 'https://www.cherry.vc',
 ARRAY['SaaS', 'E-commerce', 'Marketplace'],
 ARRAY['pre-seed', 'seed'],
 100000, 500000,
 ARRAY['Europe'], ARRAY['Berlin', 'Remote'], true,
 'We invest early in European startups.',
 '[]'::jsonb,
 'warm-intro-only', false, true),

-- Remote-Friendly
('TinySeed', 'TinySeed', 'https://tinyseed.com',
 ARRAY['SaaS', 'B2B'],
 ARRAY['pre-seed', 'seed'],
 120000, 240000,
 ARRAY['Global'], ARRAY['Remote'], true,
 'We fund early-stage B2B SaaS startups.',
 '[]'::jsonb,
 'application', false, true),

('Indie.vc', 'Indie.vc', 'https://www.indie.vc',
 ARRAY['SaaS', 'B2B'],
 ARRAY['pre-seed'],
 100000, 250000,
 ARRAY['Global'], ARRAY['Remote'], true,
 'We fund indie founders building profitable businesses.',
 '[]'::jsonb,
 'application', false, true)

ON CONFLICT DO NOTHING;

-- Update timestamps for all seeded investors
UPDATE public.investors
SET last_updated = now()
WHERE data_source IS NULL OR data_source = 'manual';

