-- Create diverse realistic user profiles with proper avatars
INSERT INTO profiles (id, full_name, avatar_url) VALUES
(gen_random_uuid(), 'Sarah Chen', 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah&backgroundColor=b6e3f4&topType=LongHairStraight&accessoriesType=Blank&hairColor=BrownDark&facialHairType=Blank&clotheType=BlazerShirt&eyeType=Happy&eyebrowType=Default&mouthType=Smile&skinColor=Light'),
(gen_random_uuid(), 'Marcus Rodriguez', 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus&backgroundColor=c0aede&topType=ShortHairShortFlat&accessoriesType=Blank&hairColor=Black&facialHairType=BeardMedium&clotheType=Hoodie&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Brown'),
(gen_random_uuid(), 'Emma Thompson', 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma&backgroundColor=ffd93d&topType=LongHairBigHair&accessoriesType=Prescription02&hairColor=Blonde&facialHairType=Blank&clotheType=GraphicShirt&eyeType=Default&eyebrowType=RaisedExcited&mouthType=Smile&skinColor=Light'),
(gen_random_uuid(), 'David Kim', 'https://api.dicebear.com/7.x/avataaars/svg?seed=david&backgroundColor=ffdfbf&topType=ShortHairDreads01&accessoriesType=Blank&hairColor=Black&facialHairType=Blank&clotheType=ShirtCrewNeck&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Yellow'),
(gen_random_uuid(), 'Lisa Johnson', 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisa&backgroundColor=c7ecee&topType=LongHairCurly&accessoriesType=Blank&hairColor=Red&facialHairType=Blank&clotheType=BlazerSweater&eyeType=Wink&eyebrowType=Default&mouthType=Smile&skinColor=Light'),
(gen_random_uuid(), 'Ahmed Hassan', 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmed&backgroundColor=d1d4f9&topType=ShortHairShortCurly&accessoriesType=Blank&hairColor=Black&facialHairType=BeardLight&clotheType=CollarSweater&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Brown'),
(gen_random_uuid(), 'Rachel Green', 'https://api.dicebear.com/7.x/avataaars/svg?seed=rachel&backgroundColor=fecaca&topType=LongHairStraight2&accessoriesType=Wayfarers&hairColor=Brown&facialHairType=Blank&clotheType=Overall&eyeType=Default&eyebrowType=Default&mouthType=Smile&skinColor=Light'),
(gen_random_uuid(), 'Carlos Mendez', 'https://api.dicebear.com/7.x/avataaars/svg?seed=carlos&backgroundColor=fed7aa&topType=ShortHairFrizzle&accessoriesType=Blank&hairColor=Black&facialHairType=MoustacheFancy&clotheType=ShirtScoopNeck&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Brown'),
(gen_random_uuid(), 'Jessica Park', 'https://api.dicebear.com/7.x/avataaars/svg?seed=jessica&backgroundColor=ddd6fe&topType=LongHairMiaWallace&accessoriesType=Blank&hairColor=Black&facialHairType=Blank&clotheType=Hoodie&eyeType=Default&eyebrowType=Default&mouthType=Smile&skinColor=Yellow'),
(gen_random_uuid(), 'Michael O''Connor', 'https://api.dicebear.com/7.x/avataaars/svg?seed=michael&backgroundColor=bbf7d0&topType=ShortHairTheCaesar&accessoriesType=Blank&hairColor=Auburn&facialHairType=BeardMedium&clotheType=BlazerShirt&eyeType=Default&eyebrowType=Default&mouthType=Default&skinColor=Light');

-- Create realistic community posts from these users
INSERT INTO community_posts (user_id, title, content, tags, created_at) 
SELECT 
  p.id,
  post.title,
  post.content,
  post.tags,
  post.created_at
FROM profiles p
CROSS JOIN (
  VALUES 
    ('Just hit $10K MRR with my productivity app!', 'Started this side project 8 months ago because I was frustrated with existing task managers. Built it nights and weekends while working my day job. Today we crossed $10K monthly recurring revenue! The key was really listening to early users and iterating fast. Next goal: $25K MRR by year end. Anyone else grinding on SaaS products?', ARRAY['saas', 'productivity', 'milestone'], now() - interval '2 hours'),
    ('Failed startup taught me everything about customer validation', 'Spent 2 years building a "revolutionary" social media platform without talking to a single potential user. Burned through $50K of savings. Complete failure. But that failure taught me more than any business course ever could. Now I validate ideas in 2 weeks max before writing any code. Current project is already profitable after 3 months because I learned from my mistakes.', ARRAY['failure', 'lessons', 'validation'], now() - interval '5 hours'),
    ('From $0 to $100K: My freelance design journey', 'Started freelancing graphic design 18 months ago after getting laid off. First month: $200. Last month: $8,500. Here is what worked: 1) Niche down (I only do SaaS landing pages now), 2) Create templates and productize services, 3) Raise prices every 3 months, 4) Build relationships, not just complete projects. Currently booking out 6 weeks in advance!', ARRAY['freelancing', 'design', 'income'], now() - interval '8 hours'),
    ('Remote team building: 15 employees across 8 countries', 'Building a fully remote company has been wild. Started with just me in my bedroom, now we are 15 people across 8 countries. Biggest challenges: time zones, communication, and maintaining culture. What worked: daily standups, monthly virtual hangouts, and yearly in-person retreats. Revenue grew 300% this year. Remote is definitely the future for tech companies.', ARRAY['remote', 'team', 'growth'], now() - interval '12 hours'),
    ('Turned my side hustle into my main hustle', 'Been selling custom iPhone cases on Etsy for 2 years as a side business. Last month it finally generated more income than my 9-5 job! Just put in my 2 weeks notice yesterday. Scared but excited. The key was finding a profitable niche (pet owners who want custom cases with their pet photos) and optimizing for SEO. Now focusing on this full-time!', ARRAY['side-hustle', 'etsy', 'transition'], now() - interval '1 day'),
    ('AI tool generated $50K in first quarter', 'Built an AI writing assistant specifically for real estate agents. Took 4 months to build, launched in January. Q1 revenue: $52K. The demand for industry-specific AI tools is insane right now. My advice: don not build another generic ChatGPT wrapper. Find a specific industry with specific needs and solve those problems. Currently have 850 paying customers.', ARRAY['ai', 'saas', 'revenue'], now() - interval '1 day'),
    ('Bootstrapped to $1M ARR without any funding', 'Just crossed $1M annual recurring revenue with my project management tool! Zero funding, just pure bootstrapping. Started 3 years ago with $5K savings. Growth was slow first year ($2K MRR), but compound growth is real. Year 2: $25K MRR. Year 3: $85K MRR. The best part? I own 100% of my company. Patience and persistence beats venture capital.', ARRAY['bootstrap', 'milestone', 'growth'], now() - interval '2 days'),
    ('Marketing experiment: $500 ad spend = $5000 revenue', 'Tried something crazy last week. Instead of typical Facebook ads, I bought banner ads on 5 niche forums related to my target audience (small business owners). Spent $500 total, generated $5,000 in sales. 10x ROI! Sometimes the old-school methods work better than the trendy ones. Going to double down on forum advertising next month.', ARRAY['marketing', 'advertising', 'experiment'], now() - interval '2 days'),
    ('Work-life balance as a solo founder', 'Running a business solo while raising two kids is brutal. Some weeks I work 80 hours, other weeks 20. The key insight: business growth does not require constant grinding. Focus on systems and automation. I built recurring revenue streams that work while I sleep. Last month took a 2-week family vacation and revenue actually went UP. Smart work beats hard work.', ARRAY['solo-founder', 'balance', 'automation'], now() - interval '3 days'),
    ('From idea to $100K revenue in 6 months', 'Saw a problem in my previous job (construction project management), quit, and built a solution. Launched MVP in 8 weeks. First customer in week 10. $100K revenue by month 6. Key lessons: 1) Solve your own problem, 2) Charge from day one, 3) Get feedback constantly, 4) Ship fast and iterate. Now at $180K revenue and growing 25% monthly. Sometimes you just have to take the leap!', ARRAY['startup', 'construction', 'growth'], now() - interval '3 days')
) AS post(title, content, tags, created_at)
WHERE p.full_name IN ('Sarah Chen', 'Marcus Rodriguez', 'Emma Thompson', 'David Kim', 'Lisa Johnson', 'Ahmed Hassan', 'Rachel Green', 'Carlos Mendez', 'Jessica Park', 'Michael O''Connor')
ORDER BY p.created_at
LIMIT 10;