WITH vc_seed (
  slug, name, firm_name, firm_website, logo_url, investment_stages, industries,
  typical_check_size_min, typical_check_size_max, geographic_focus, locations,
  remote_friendly, investment_thesis, portfolio_companies, contact_preference,
  application_url, requires_warm_intro, is_featured
) AS (
  VALUES
    ('union-square-ventures','Union Square Ventures','Union Square Ventures','https://www.usv.com','https://logo.clearbit.com/usv.com',ARRAY['pre-seed','seed','series-a'],ARRAY['Climate','Fintech','Developer Tools','Healthcare','Consumer'],250000,2500000,ARRAY['United States','Europe'],ARRAY['New York'],false,'Early-stage venture firm investing behind trusted brands, enabling infrastructure, and large network effects.','[{"name":"Twilio","industry":"Communications"},{"name":"Etsy","industry":"Marketplace"},{"name":"MongoDB","industry":"Developer Tools"}]'::jsonb,'warm-intro-only','https://www.usv.com',true,false),
    ('kleiner-perkins','Kleiner Perkins','Kleiner Perkins','https://www.kleinerperkins.com','https://logo.clearbit.com/kleinerperkins.com',ARRAY['seed','series-a','series-b'],ARRAY['AI','Enterprise','Healthcare','Climate','Consumer'],500000,5000000,ARRAY['United States'],ARRAY['Menlo Park'],false,'Venture firm with a long track record in category creation across software, life sciences, and industrial innovation.','[{"name":"Amazon","industry":"Commerce"},{"name":"Google","industry":"Search"},{"name":"Rippling","industry":"HR Tech"}]'::jsonb,'warm-intro-only','https://www.kleinerperkins.com',true,true),
    ('gv','GV','GV','https://www.gv.com','https://logo.clearbit.com/gv.com',ARRAY['seed','series-a','series-b'],ARRAY['AI','Healthcare','Developer Tools','Climate','Consumer'],250000,5000000,ARRAY['United States','Europe'],ARRAY['San Francisco','New York','London'],true,'Alphabet-backed venture platform backing technical founders in software, health, and frontier technology.','[{"name":"Uber","industry":"Mobility"},{"name":"Flatiron Health","industry":"Healthcare"},{"name":"GitLab","industry":"Developer Tools"}]'::jsonb,'warm-intro-only','https://www.gv.com',true,true),
    ('sapphire-ventures','Sapphire Ventures','Sapphire Ventures','https://sapphireventures.com','https://logo.clearbit.com/sapphireventures.com',ARRAY['series-a','series-b'],ARRAY['Enterprise','AI','Cybersecurity','Fintech','Infrastructure'],1000000,8000000,ARRAY['United States','Europe','Israel'],ARRAY['Palo Alto','Austin','London'],true,'B2B software-focused firm helping founders scale go-to-market, executive recruiting, and enterprise expansion.','[{"name":"Monday.com","industry":"Work Management"},{"name":"Snyk","industry":"Security"},{"name":"Outreach","industry":"Sales Tech"}]'::jsonb,'warm-intro-only','https://sapphireventures.com',true,false),
    ('menlo-ventures','Menlo Ventures','Menlo Ventures','https://menlovc.com','https://logo.clearbit.com/menlovc.com',ARRAY['seed','series-a','series-b'],ARRAY['AI','Cybersecurity','Consumer','SaaS','Healthcare'],500000,5000000,ARRAY['United States'],ARRAY['Menlo Park'],false,'Multi-stage investor active in consumer internet, enterprise infrastructure, cybersecurity, and applied AI.','[{"name":"Carta","industry":"Fintech"},{"name":"Roku","industry":"Consumer Hardware"},{"name":"Anthropic","industry":"AI"}]'::jsonb,'warm-intro-only','https://menlovc.com',true,false),
    ('craft-ventures','Craft Ventures','Craft Ventures','https://craftventures.com','https://logo.clearbit.com/craftventures.com',ARRAY['seed','series-a'],ARRAY['SaaS','Marketplaces','Fintech','Consumer','Developer Tools'],250000,3000000,ARRAY['United States'],ARRAY['San Francisco'],true,'Founder-led venture fund focused on software and marketplace companies with strong capital efficiency and distribution.','[{"name":"Bird","industry":"Mobility"},{"name":"ClickUp","industry":"Productivity"},{"name":"Reddit","industry":"Community"}]'::jsonb,'application','https://craftventures.com',false,false),
    ('initialized-capital','Initialized Capital','Initialized Capital','https://initialized.com','https://logo.clearbit.com/initialized.com',ARRAY['pre-seed','seed','series-a'],ARRAY['AI','Developer Tools','Fintech','B2B SaaS','Consumer'],500000,2000000,ARRAY['United States'],ARRAY['San Francisco'],true,'Early-stage firm backing founders from day zero across software, applied AI, and internet platforms.','[{"name":"Coinbase","industry":"Crypto"},{"name":"Flexport","industry":"Logistics"},{"name":"Rippling","industry":"HR Tech"}]'::jsonb,'application','https://initialized.com',false,false),
    ('felicis','Felicis','Felicis','https://felicis.com','https://logo.clearbit.com/felicis.com',ARRAY['seed','series-a'],ARRAY['AI','Security','Developer Tools','Healthcare','Consumer'],500000,3000000,ARRAY['United States','Europe'],ARRAY['Menlo Park'],true,'Venture firm backing iconic founders early in AI, developer tools, cloud, health, and security.','[{"name":"Canva","industry":"Design SaaS"},{"name":"Notion","industry":"Productivity"},{"name":"Twitch","industry":"Consumer Internet"}]'::jsonb,'application','https://felicis.com',false,false),
    ('meritech-capital','Meritech Capital','Meritech Capital','https://meritechcapital.com','https://logo.clearbit.com/meritechcapital.com',ARRAY['series-a','series-b'],ARRAY['Enterprise','Cloud','Fintech','Security','Consumer'],2000000,10000000,ARRAY['United States'],ARRAY['Palo Alto'],false,'Growth-oriented firm backing software and internet companies with strong product-market fit and efficient scaling.','[{"name":"Snowflake","industry":"Data Infrastructure"},{"name":"Datadog","industry":"Observability"},{"name":"Coupa","industry":"Spend Management"}]'::jsonb,'warm-intro-only','https://meritechcapital.com',true,false),
    ('redpoint-ventures','Redpoint','Redpoint Ventures','https://www.redpoint.com','https://logo.clearbit.com/redpoint.com',ARRAY['pre-seed','seed','series-a'],ARRAY['Consumer','Enterprise','Fintech','AI','Infrastructure'],250000,3000000,ARRAY['United States'],ARRAY['San Francisco','Los Angeles'],true,'Early-stage firm investing across consumer and enterprise with strong operating support around product and growth.','[{"name":"Stripe","industry":"Fintech"},{"name":"Snowflake","industry":"Data Infrastructure"},{"name":"Netflix","industry":"Streaming"}]'::jsonb,'application','https://www.redpoint.com',false,false),
    ('mayfield','Mayfield','Mayfield','https://mayfield.com','https://logo.clearbit.com/mayfield.com',ARRAY['seed','series-a'],ARRAY['AI','Enterprise','Human Productivity','Consumer','Health'],500000,3000000,ARRAY['United States','India'],ARRAY['Menlo Park'],true,'Long-standing seed and Series A firm investing in founders building the next generation of human productivity.','[{"name":"HashiCorp","industry":"Developer Tools"},{"name":"Mammoth Biosciences","industry":"Biotech"},{"name":"Pivotal","industry":"Cloud"}]'::jsonb,'application','https://mayfield.com',false,false),
    ('madrona','Madrona','Madrona','https://madrona.com','https://logo.clearbit.com/madrona.com',ARRAY['pre-seed','seed','series-a'],ARRAY['AI','Cloud','SaaS','Fintech','Developer Tools'],250000,2000000,ARRAY['Pacific Northwest','United States'],ARRAY['Seattle'],true,'Seattle-based early-stage investor with deep roots in cloud, AI, developer infrastructure, and enterprise software.','[{"name":"Snowflake","industry":"Data Infrastructure"},{"name":"Common Room","industry":"Community Intelligence"},{"name":"Pulumi","industry":"Developer Tools"}]'::jsonb,'application','https://madrona.com',false,false),
    ('645-ventures','645 Ventures','645 Ventures','https://645ventures.com','https://logo.clearbit.com/645ventures.com',ARRAY['pre-seed','seed','series-a'],ARRAY['Enterprise','Fintech','Consumer','Healthtech','AI'],250000,2000000,ARRAY['United States'],ARRAY['New York','San Francisco'],true,'Data-driven early-stage fund supporting founders with market maps, benchmarking, and customer development support.','[{"name":"Goldbelly","industry":"Marketplace"},{"name":"Resident","industry":"Commerce"},{"name":"FiscalNote","industry":"GovTech"}]'::jsonb,'application','https://645ventures.com',false,false),
    ('costanoa-ventures','Costanoa Ventures','Costanoa Ventures','https://costanoa.vc','https://logo.clearbit.com/costanoa.vc',ARRAY['pre-seed','seed','series-a'],ARRAY['Enterprise','Developer Tools','Cybersecurity','Fintech','AI'],250000,2000000,ARRAY['United States'],ARRAY['Palo Alto'],true,'Seed-stage venture firm with deep enterprise conviction and hands-on support for customer discovery and go-to-market.','[{"name":"Nauto","industry":"Transportation AI"},{"name":"Demandbase","industry":"B2B Marketing"},{"name":"Viz.ai","industry":"Healthcare AI"}]'::jsonb,'application','https://costanoa.vc',false,false),
    ('emergence-capital','Emergence Capital','Emergence Capital','https://emcap.com','https://logo.clearbit.com/emcap.com',ARRAY['seed','series-a','series-b'],ARRAY['B2B SaaS','Future of Work','AI','Developer Tools','Vertical SaaS'],1000000,5000000,ARRAY['United States'],ARRAY['San Mateo'],false,'Enterprise software specialist backing founders building the operating systems of modern work.','[{"name":"Salesforce","industry":"CRM"},{"name":"Zoom","industry":"Communications"},{"name":"Veeva","industry":"Vertical SaaS"}]'::jsonb,'warm-intro-only','https://emcap.com',true,false),
    ('true-ventures','True Ventures','True Ventures','https://trueventures.com','https://logo.clearbit.com/trueventures.com',ARRAY['pre-seed','seed','series-a'],ARRAY['Consumer','Enterprise','Healthcare','Climate','Fintech'],250000,2000000,ARRAY['United States'],ARRAY['San Francisco','Palo Alto'],true,'Founder-centric early-stage fund investing in software, consumer, climate, and health with strong community support.','[{"name":"Ring","industry":"Smart Home"},{"name":"Peloton","industry":"Fitness"},{"name":"Blue Bottle Coffee","industry":"Consumer"}]'::jsonb,'application','https://trueventures.com',false,false),
    ('foundry','Foundry','Foundry','https://foundry.vc','https://logo.clearbit.com/foundry.vc',ARRAY['seed','series-a'],ARRAY['SaaS','Developer Tools','Marketplaces','Consumer','AI'],500000,3000000,ARRAY['United States'],ARRAY['Boulder','San Francisco'],true,'Theme-driven early-stage firm known for founder empathy and long-term support across software and internet businesses.','[{"name":"SendGrid","industry":"Communications"},{"name":"Zynga","industry":"Gaming"},{"name":"Fitbit","industry":"Consumer Hardware"}]'::jsonb,'application','https://foundry.vc',false,false),
    ('balderton-capital','Balderton Capital','Balderton Capital','https://www.balderton.com','https://logo.clearbit.com/balderton.com',ARRAY['seed','series-a','series-b'],ARRAY['Enterprise','Fintech','Consumer','Marketplace','AI'],500000,5000000,ARRAY['Europe'],ARRAY['London'],true,'Europe-focused venture firm backing ambitious technology founders from first round through scale.','[{"name":"Revolut","industry":"Fintech"},{"name":"GoCardless","industry":"Payments"},{"name":"Depop","industry":"Marketplace"}]'::jsonb,'warm-intro-only','https://www.balderton.com',true,false),
    ('northzone','Northzone','Northzone','https://northzone.com','https://logo.clearbit.com/northzone.com',ARRAY['seed','series-a','series-b'],ARRAY['Consumer','Fintech','SaaS','Healthtech','Climate'],500000,4000000,ARRAY['Europe','United States'],ARRAY['London','Stockholm','New York','Oslo'],true,'European venture firm investing in founders building enduring global technology companies.','[{"name":"Spotify","industry":"Music Tech"},{"name":"Klarna","industry":"Fintech"},{"name":"Personio","industry":"HR Tech"}]'::jsonb,'warm-intro-only','https://northzone.com',true,false),
    ('peak-xv-partners','Peak XV Partners','Peak XV Partners','https://www.peakxv.com','https://logo.clearbit.com/peakxv.com',ARRAY['seed','series-a','series-b'],ARRAY['SaaS','Fintech','Consumer','Edtech','Healthcare'],250000,5000000,ARRAY['India','Southeast Asia'],ARRAY['Bengaluru','Singapore'],true,'Regional venture platform backing founders across India and Southeast Asia from company formation through scale.','[{"name":"Freshworks","industry":"SaaS"},{"name":"Pine Labs","industry":"Fintech"},{"name":"Carousell","industry":"Marketplace"}]'::jsonb,'application','https://www.peakxv.com',false,false),
    ('octopus-ventures','Octopus Ventures','Octopus Ventures','https://octopusventures.com','https://logo.clearbit.com/octopusventures.com',ARRAY['pre-seed','seed','series-a'],ARRAY['B2B Software','Climate','Health','Deep Tech','Fintech'],250000,3000000,ARRAY['United Kingdom','Europe'],ARRAY['London'],true,'London-based early-stage investor with strong conviction in health, climate, fintech, and deep tech.','[{"name":"ManyPets","industry":"Insurtech"},{"name":"WaveOptics","industry":"AR Hardware"},{"name":"Cazoo","industry":"Automotive"}]'::jsonb,'application','https://octopusventures.com',false,false),
    ('notion-capital','Notion Capital','Notion Capital','https://notion.vc','https://logo.clearbit.com/notion.vc',ARRAY['seed','series-a'],ARRAY['B2B SaaS','Cloud','Fintech','Vertical SaaS','AI'],500000,3000000,ARRAY['Europe'],ARRAY['London'],true,'European B2B SaaS specialist backing software founders from seed through scaling milestones.','[{"name":"GoCardless","industry":"Payments"},{"name":"Tradeshift","industry":"B2B Commerce"},{"name":"Mews","industry":"Hospitality SaaS"}]'::jsonb,'application','https://notion.vc',false,false),
    ('amplify-partners','Amplify Partners','Amplify Partners','https://www.amplifypartners.com','https://logo.clearbit.com/amplifypartners.com',ARRAY['seed','series-a'],ARRAY['Developer Tools','Infrastructure','AI','Data','Security'],500000,3000000,ARRAY['United States'],ARRAY['Menlo Park'],false,'Technical seed and Series A investor focused on infrastructure, data, developer tools, and applied AI.','[{"name":"Databricks","industry":"Data Infrastructure"},{"name":"dbt Labs","industry":"Analytics"},{"name":"Chainguard","industry":"Software Supply Chain"}]'::jsonb,'warm-intro-only','https://www.amplifypartners.com',true,false),
    ('crv','CRV','CRV','https://www.crv.com','https://logo.clearbit.com/crv.com',ARRAY['pre-seed','seed','series-a'],ARRAY['Consumer','Enterprise','Developer Tools','Fintech','Climate'],250000,2500000,ARRAY['United States'],ARRAY['Cambridge','San Francisco'],true,'Long-running seed firm backing technical founders early across software, climate, fintech, and internet platforms.','[{"name":"DoorDash","industry":"Delivery"},{"name":"Twitter","industry":"Social"},{"name":"Vercel","industry":"Developer Tools"}]'::jsonb,'application','https://www.crv.com',false,false),
    ('scale-venture-partners','Scale Venture Partners','Scale Venture Partners','https://www.scalevp.com','https://logo.clearbit.com/scalevp.com',ARRAY['seed','series-a','series-b'],ARRAY['Cloud','Developer Tools','Security','AI','Vertical SaaS'],500000,4000000,ARRAY['United States'],ARRAY['Foster City'],false,'Software specialist investing in data, cloud, infrastructure, and developer-first companies from seed through growth.','[{"name":"DocuSign","industry":"Workflow SaaS"},{"name":"HubSpot","industry":"Marketing SaaS"},{"name":"Bill.com","industry":"Fintech"}]'::jsonb,'warm-intro-only','https://www.scalevp.com',true,false)
)
INSERT INTO public.investors (
  slug, name, firm_name, firm_website, logo_url, investor_type, investment_stages,
  industries, typical_check_size_min, typical_check_size_max, geographic_focus,
  locations, remote_friendly, investment_thesis, portfolio_companies,
  recent_investments_count, total_portfolio_count, contact_preference,
  application_url, requires_warm_intro, is_featured, is_active, data_source, last_updated
)
SELECT
  slug, name, firm_name, firm_website, logo_url, 'vc', investment_stages, industries,
  typical_check_size_min, typical_check_size_max, geographic_focus, locations,
  remote_friendly, investment_thesis, portfolio_companies, 0,
  jsonb_array_length(portfolio_companies), contact_preference, application_url,
  requires_warm_intro, is_featured, true, 'manual', now()
FROM vc_seed
ON CONFLICT (slug) DO UPDATE
SET
  name = EXCLUDED.name,
  firm_name = EXCLUDED.firm_name,
  firm_website = EXCLUDED.firm_website,
  logo_url = EXCLUDED.logo_url,
  investor_type = EXCLUDED.investor_type,
  investment_stages = EXCLUDED.investment_stages,
  industries = EXCLUDED.industries,
  typical_check_size_min = EXCLUDED.typical_check_size_min,
  typical_check_size_max = EXCLUDED.typical_check_size_max,
  geographic_focus = EXCLUDED.geographic_focus,
  locations = EXCLUDED.locations,
  remote_friendly = EXCLUDED.remote_friendly,
  investment_thesis = EXCLUDED.investment_thesis,
  portfolio_companies = EXCLUDED.portfolio_companies,
  total_portfolio_count = EXCLUDED.total_portfolio_count,
  contact_preference = EXCLUDED.contact_preference,
  application_url = EXCLUDED.application_url,
  requires_warm_intro = EXCLUDED.requires_warm_intro,
  is_featured = EXCLUDED.is_featured,
  is_active = EXCLUDED.is_active,
  data_source = EXCLUDED.data_source,
  last_updated = now();
