-- Harden auth signup trigger so profile bootstrap failures never block auth.users creation.
-- This keeps account creation resilient while preserving diagnostics for failures.

CREATE TABLE IF NOT EXISTS public.signup_trigger_failures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID,
  email TEXT,
  error_code TEXT,
  error_message TEXT,
  raw_user_meta_data JSONB,
  context JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_signup_trigger_failures_created_at
  ON public.signup_trigger_failures (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_signup_trigger_failures_email
  ON public.signup_trigger_failures (lower(email));

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  generated_username TEXT;
  name_parts TEXT[];
  first_name TEXT;
  last_name TEXT;
  base_slug TEXT;
  final_slug TEXT;
  counter INTEGER := 1;
  is_admin BOOLEAN;
  admin_tier TEXT;
  display_name TEXT;
BEGIN
  is_admin := (lower(COALESCE(NEW.email, '')) = 'admin@creatives-takeover.com');
  admin_tier := CASE WHEN is_admin THEN 'professional' ELSE 'free' END;

  display_name := COALESCE(
    NULLIF(NEW.raw_user_meta_data->>'full_name', ''),
    split_part(COALESCE(NEW.email, ''), '@', 1),
    'user'
  );

  -- Build base username inline to avoid hard dependency on helper functions.
  base_slug := NULL;
  IF display_name IS NOT NULL AND btrim(display_name) <> '' THEN
    name_parts := regexp_split_to_array(btrim(display_name), '\s+');

    IF array_length(name_parts, 1) >= 2 THEN
      first_name := regexp_replace(lower(COALESCE(name_parts[1], '')), '[^a-z0-9]', '', 'g');
      last_name := regexp_replace(lower(COALESCE(name_parts[array_length(name_parts, 1)], '')), '[^a-z0-9]', '', 'g');
      base_slug := first_name || last_name;
    ELSIF array_length(name_parts, 1) = 1 THEN
      base_slug := regexp_replace(lower(COALESCE(name_parts[1], '')), '[^a-z0-9]', '', 'g');
    END IF;
  END IF;

  IF base_slug IS NULL OR base_slug = '' THEN
    base_slug := 'user' || substring(NEW.id::TEXT FROM 1 FOR 8);
  END IF;

  final_slug := base_slug;
  WHILE EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE lower(username) = lower(final_slug)
      AND id <> NEW.id
  ) LOOP
    final_slug := base_slug || counter::TEXT;
    counter := counter + 1;
  END LOOP;
  generated_username := final_slug;

  BEGIN
    INSERT INTO public.profiles (id, full_name, avatar_url, username, subscription_tier)
    VALUES (
      NEW.id,
      display_name,
      NEW.raw_user_meta_data->>'avatar_url',
      generated_username,
      admin_tier
    )
    ON CONFLICT (id) DO UPDATE SET
      full_name = COALESCE(public.profiles.full_name, EXCLUDED.full_name),
      avatar_url = COALESCE(public.profiles.avatar_url, EXCLUDED.avatar_url),
      username = COALESCE(public.profiles.username, EXCLUDED.username),
      subscription_tier = CASE
        WHEN is_admin THEN 'professional'
        ELSE public.profiles.subscription_tier
      END;
  EXCEPTION WHEN OTHERS THEN
    INSERT INTO public.signup_trigger_failures (
      user_id, email, error_code, error_message, raw_user_meta_data, context
    )
    VALUES (
      NEW.id,
      NEW.email,
      SQLSTATE,
      SQLERRM,
      NEW.raw_user_meta_data,
      jsonb_build_object('stage', 'profiles_upsert')
    );

    RAISE LOG '[SIGNUP_TRIGGER] profiles upsert failed user_id=% email=% code=% msg=%',
      NEW.id, NEW.email, SQLSTATE, SQLERRM;
    RETURN NEW;
  END;

  IF is_admin THEN
    BEGIN
      INSERT INTO public.user_credits (user_id, balance, subscription_tier, monthly_quota)
      VALUES (NEW.id, 5, 'professional', 5)
      ON CONFLICT (user_id) DO UPDATE
      SET subscription_tier = 'professional';

      INSERT INTO public.subscribers (user_id, email, subscribed, subscription_tier)
      VALUES (NEW.id, NEW.email, true, 'professional')
      ON CONFLICT (email) DO UPDATE
      SET subscribed = true,
          subscription_tier = 'professional';
    EXCEPTION WHEN OTHERS THEN
      INSERT INTO public.signup_trigger_failures (
        user_id, email, error_code, error_message, raw_user_meta_data, context
      )
      VALUES (
        NEW.id,
        NEW.email,
        SQLSTATE,
        SQLERRM,
        NEW.raw_user_meta_data,
        jsonb_build_object('stage', 'admin_bootstrap')
      );

      RAISE LOG '[SIGNUP_TRIGGER] admin bootstrap failed user_id=% email=% code=% msg=%',
        NEW.id, NEW.email, SQLSTATE, SQLERRM;
    END;
  END IF;

  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  INSERT INTO public.signup_trigger_failures (
    user_id, email, error_code, error_message, raw_user_meta_data, context
  )
  VALUES (
    NEW.id,
    NEW.email,
    SQLSTATE,
    SQLERRM,
    NEW.raw_user_meta_data,
    jsonb_build_object('stage', 'handle_new_user_unhandled')
  );

  RAISE LOG '[SIGNUP_TRIGGER] unhandled failure user_id=% email=% code=% msg=%',
    NEW.id, NEW.email, SQLSTATE, SQLERRM;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

