-- Revenue P0: replace unverified external-calendar bookings with an
-- admin-coordinated, zero-credit mentor checkpoint.

ALTER TABLE public.first_customer_sprints
  ADD COLUMN IF NOT EXISTS checkpoint_status text NOT NULL DEFAULT 'not_requested',
  ADD COLUMN IF NOT EXISTS checkpoint_requested_at timestamptz,
  ADD COLUMN IF NOT EXISTS checkpoint_scheduled_for timestamptz,
  ADD COLUMN IF NOT EXISTS checkpoint_verified_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS checkpoint_verified_at timestamptz,
  ADD COLUMN IF NOT EXISTS checkpoint_redacted_brief jsonb;

ALTER TABLE public.first_customer_sprints
  DROP CONSTRAINT IF EXISTS first_customer_sprints_checkpoint_status_check;
ALTER TABLE public.first_customer_sprints
  ADD CONSTRAINT first_customer_sprints_checkpoint_status_check
  CHECK (checkpoint_status IN ('not_requested', 'requested', 'scheduled', 'completed', 'cancelled'));

-- Legacy client-controlled completion timestamps are not verified checkpoint
-- evidence. Keep recommendations, but require the new admin verification path
-- before a checkpoint can count toward sprint completion.
UPDATE public.first_customer_sprints
SET mentor_checkpoint_completed_at = NULL
WHERE checkpoint_verified_at IS NULL
   OR length(trim(COALESCE(mentor_recommendation_summary, ''))) < 3;

CREATE TABLE IF NOT EXISTS public.first_customer_sprint_checkpoint_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sprint_id uuid NOT NULL REFERENCES public.first_customer_sprints(id) ON DELETE CASCADE,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  previous_status text,
  next_status text NOT NULL,
  scheduled_for timestamptz,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.first_customer_sprint_checkpoint_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.first_customer_sprint_checkpoint_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.first_customer_sprint_checkpoint_events TO service_role;

CREATE OR REPLACE FUNCTION public.sync_first_customer_checkpoint_completion_v1()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.checkpoint_status = 'completed'
    AND length(trim(COALESCE(NEW.mentor_recommendation_summary, ''))) >= 3
    AND NEW.checkpoint_verified_at IS NOT NULL THEN
    NEW.mentor_checkpoint_completed_at := COALESCE(OLD.mentor_checkpoint_completed_at, NEW.checkpoint_verified_at, now());
  ELSE
    NEW.mentor_checkpoint_completed_at := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_first_customer_checkpoint_completion_v1
  ON public.first_customer_sprints;
CREATE TRIGGER sync_first_customer_checkpoint_completion_v1
BEFORE INSERT OR UPDATE OF checkpoint_status, checkpoint_verified_at, mentor_recommendation_summary, mentor_checkpoint_completed_at
ON public.first_customer_sprints
FOR EACH ROW EXECUTE FUNCTION public.sync_first_customer_checkpoint_completion_v1();

CREATE OR REPLACE FUNCTION public.request_first_customer_sprint_checkpoint_v1(
  p_sprint_id uuid,
  p_mentor_id uuid,
  p_redacted_brief jsonb
)
RETURNS public.first_customer_sprints
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sprint public.first_customer_sprints%ROWTYPE;
  v_attached integer;
  v_brief jsonb;
  v_previous_status text;
BEGIN
  SELECT * INTO v_sprint
  FROM public.first_customer_sprints
  WHERE id = p_sprint_id AND founder_id = auth.uid() AND status IN ('draft', 'active', 'paused')
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Sprint not found' USING ERRCODE='42501'; END IF;
  IF v_sprint.selected_message_variant IS NULL THEN RAISE EXCEPTION 'Select a primary message first'; END IF;
  SELECT count(*)::integer INTO v_attached
  FROM public.first_customer_sprint_contacts WHERE sprint_id = p_sprint_id;
  IF v_attached < 10 THEN RAISE EXCEPTION 'Attach at least 10 prospects before requesting a checkpoint'; END IF;
  IF NOT EXISTS (SELECT 1 FROM public.mentors WHERE id=p_mentor_id AND COALESCE(is_active, false)) THEN
    RAISE EXCEPTION 'Selected mentor is unavailable';
  END IF;
  IF p_redacted_brief IS NULL OR jsonb_typeof(p_redacted_brief) <> 'object' THEN
    RAISE EXCEPTION 'A redacted checkpoint brief is required';
  END IF;
  IF p_redacted_brief ?| ARRAY['profileUrl','profile_url','email','notes'] THEN
    RAISE EXCEPTION 'The checkpoint brief contains private fields';
  END IF;
  IF jsonb_typeof(COALESCE(p_redacted_brief->'contacts', '[]'::jsonb)) <> 'array' THEN
    RAISE EXCEPTION 'The checkpoint contact summary must be an array';
  END IF;
  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(COALESCE(p_redacted_brief->'contacts', '[]'::jsonb)) contact
    WHERE jsonb_typeof(contact) <> 'object'
       OR EXISTS (
         SELECT 1 FROM jsonb_object_keys(contact) field
         WHERE field NOT IN ('displayName','company','role','stage')
       )
       OR COALESCE(contact->>'displayName', '') !~ '^Prospect [1-9][0-9]*$'
       OR (contact ? 'company' AND jsonb_typeof(contact->'company') <> 'null')
       OR octet_length(COALESCE(contact->>'role', '')) > 200
       OR octet_length(COALESCE(contact->>'stage', '')) > 100
  ) THEN
    RAISE EXCEPTION 'The checkpoint contact summary is not redacted';
  END IF;
  IF octet_length(p_redacted_brief::text) > 20000 THEN RAISE EXCEPTION 'Checkpoint brief is too large'; END IF;

  IF v_sprint.checkpoint_status IN ('requested','scheduled','completed') THEN RETURN v_sprint; END IF;
  v_previous_status := v_sprint.checkpoint_status;
  v_brief := p_redacted_brief - ARRAY['contacts','profileUrl','profile_url','email','notes'];

  UPDATE public.first_customer_sprints
  SET mentor_id = p_mentor_id,
      checkpoint_status = 'requested',
      checkpoint_requested_at = now(),
      checkpoint_scheduled_for = NULL,
      checkpoint_verified_by = NULL,
      checkpoint_verified_at = NULL,
      checkpoint_redacted_brief = v_brief,
      mentor_brief_snapshot = v_brief,
      discovery_call_id = NULL,
      updated_at = now()
  WHERE id = p_sprint_id
  RETURNING * INTO v_sprint;

  INSERT INTO public.first_customer_sprint_checkpoint_events(
    sprint_id, actor_user_id, previous_status, next_status, metadata
  ) VALUES (
    p_sprint_id, auth.uid(), v_previous_status, 'requested',
    jsonb_build_object('mentorId', p_mentor_id, 'creditsDeducted', 0)
  );
  RETURN v_sprint;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_update_first_customer_sprint_checkpoint_v1(
  p_sprint_id uuid,
  p_status text,
  p_scheduled_for timestamptz DEFAULT NULL
)
RETURNS public.first_customer_sprints
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sprint public.first_customer_sprints%ROWTYPE;
  v_previous text;
BEGIN
  IF NOT public.has_role(auth.uid(), 'admin'::app_role) THEN
    RAISE EXCEPTION 'Admin access required' USING ERRCODE='42501';
  END IF;
  IF p_status NOT IN ('scheduled','completed','cancelled') THEN RAISE EXCEPTION 'Invalid checkpoint status'; END IF;

  SELECT * INTO v_sprint FROM public.first_customer_sprints WHERE id=p_sprint_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Sprint not found'; END IF;
  v_previous := v_sprint.checkpoint_status;
  IF v_previous NOT IN ('requested','scheduled') THEN
    RAISE EXCEPTION 'Checkpoint must be requested before an admin can update it';
  END IF;
  IF p_status = 'scheduled' AND p_scheduled_for IS NULL THEN RAISE EXCEPTION 'A scheduled time is required'; END IF;
  IF p_status = 'completed' AND v_previous <> 'scheduled' THEN RAISE EXCEPTION 'Schedule the checkpoint before verifying completion'; END IF;

  UPDATE public.first_customer_sprints
  SET checkpoint_status = p_status,
      checkpoint_scheduled_for = CASE
        WHEN p_status='scheduled' THEN p_scheduled_for
        WHEN p_status='cancelled' THEN NULL
        ELSE checkpoint_scheduled_for
      END,
      checkpoint_verified_by = CASE WHEN p_status='completed' THEN auth.uid() ELSE checkpoint_verified_by END,
      checkpoint_verified_at = CASE WHEN p_status='completed' THEN now() ELSE checkpoint_verified_at END,
      updated_at = now()
  WHERE id=p_sprint_id
  RETURNING * INTO v_sprint;

  INSERT INTO public.first_customer_sprint_checkpoint_events(
    sprint_id, actor_user_id, previous_status, next_status, scheduled_for,
    metadata
  ) VALUES (
    p_sprint_id, auth.uid(), v_previous, p_status, v_sprint.checkpoint_scheduled_for,
    jsonb_build_object('adminVerified', p_status='completed', 'creditsDeducted', 0)
  );
  RETURN v_sprint;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_first_customer_sprint_snapshot_v1(p_sprint_id uuid DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_founder uuid := auth.uid();
  v_sprint public.first_customer_sprints%ROWTYPE;
  v_enrolled boolean;
  v_attached integer := 0; v_sent integer := 0; v_replies integer := 0;
  v_conversations integer := 0; v_commitments integer := 0; v_payments integer := 0;
  v_can_complete boolean := false; v_step text := 'intake';
BEGIN
  IF v_founder IS NULL THEN RAISE EXCEPTION 'Authentication required' USING ERRCODE='42501'; END IF;
  v_enrolled := public.first_customer_sprint_is_enrolled_v1(v_founder);
  SELECT * INTO v_sprint FROM public.first_customer_sprints
    WHERE founder_id=v_founder AND (p_sprint_id IS NULL OR id=p_sprint_id)
    ORDER BY CASE WHEN status IN ('draft','active','paused') THEN 0 ELSE 1 END, created_at DESC LIMIT 1;
  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'version',1,'enrolled',v_enrolled,'sprint',NULL,'contacts','[]'::jsonb,'availableContacts','[]'::jsonb,
      'cycleDefaults',COALESCE((SELECT jsonb_build_object(
        'businessModel',business_model,'customerCount',customer_count,'weeklyCapacityHours',weekly_capacity_hours,'primaryGoal',primary_goal
      ) FROM public.founder_cycle_state WHERE user_id=v_founder),'{}'::jsonb)
    );
  END IF;

  SELECT count(*) INTO v_attached FROM public.first_customer_sprint_contacts WHERE sprint_id=v_sprint.id;
  SELECT
    count(*) FILTER (WHERE event_type='outreach_sent'),
    count(*) FILTER (WHERE event_type='reply_received'),
    count(*) FILTER (WHERE event_type='interview_completed'),
    count(*) FILTER (WHERE event_type='commitment_received'),
    count(*) FILTER (WHERE event_type='payment_received')
  INTO v_sent,v_replies,v_conversations,v_commitments,v_payments
  FROM public.customer_evidence_events
  WHERE user_id=v_founder AND metadata->>'sprintId'=v_sprint.id::text
    AND EXISTS (
      SELECT 1 FROM public.first_customer_sprint_contacts scoped
      WHERE scoped.sprint_id=v_sprint.id AND scoped.contact_id=customer_evidence_events.contact_id
    );

  v_can_complete := v_sprint.mentor_checkpoint_completed_at IS NOT NULL AND (
    v_conversations >= 3 OR v_commitments > 0 OR v_payments > 0
    OR (v_sent >= 10 AND v_sprint.final_decision IN ('pivot','pause') AND length(trim(COALESCE(v_sprint.final_notes,''))) >= 3)
  );
  v_step := CASE
    WHEN v_sprint.status='completed' THEN 'completed'
    WHEN now()>v_sprint.ends_at THEN 'awaiting_final_review'
    WHEN v_attached<10 THEN 'target_list'
    WHEN v_sprint.selected_message_variant IS NULL THEN 'message_preparation'
    WHEN v_sprint.mentor_checkpoint_completed_at IS NULL THEN 'mentor_checkpoint'
    WHEN v_sent<10 THEN 'execution'
    WHEN NOT v_can_complete THEN 'review'
    ELSE 'complete'
  END;

  RETURN jsonb_build_object(
    'version',1,'enrolled',v_enrolled,'generatedAt',now(),'sprint',to_jsonb(v_sprint),
    'contacts',COALESCE((SELECT jsonb_agg(to_jsonb(c) || jsonb_build_object('message_variant_key',sc.selected_message_variant) ORDER BY sc.created_at)
      FROM public.first_customer_sprint_contacts sc JOIN public.founder_customer_contacts c ON c.id=sc.contact_id WHERE sc.sprint_id=v_sprint.id),'[]'::jsonb),
    'availableContacts',COALESCE((SELECT jsonb_agg(to_jsonb(c) ORDER BY c.last_activity_at DESC)
      FROM public.founder_customer_contacts c WHERE c.user_id=v_founder
      AND NOT EXISTS (SELECT 1 FROM public.first_customer_sprint_contacts sc WHERE sc.sprint_id=v_sprint.id AND sc.contact_id=c.id)),'[]'::jsonb),
    'evidence',jsonb_build_object('attachedProspects',v_attached,'contactedProspects',v_sent,'replies',v_replies,'conversations',v_conversations,'commitments',v_commitments,'payments',v_payments),
    'targets',jsonb_build_object('prospects',20,'outreach',10,'conversations',3,'mentorCheckpoints',1),
    'linkedCall',NULL,
    'derivedStep',v_step,'awaitingFinalReview',(now()>v_sprint.ends_at AND v_sprint.status<>'completed'),'canComplete',v_can_complete,
    'cycleDefaults',COALESCE((SELECT jsonb_build_object(
      'businessModel',business_model,'customerCount',customer_count,'weeklyCapacityHours',weekly_capacity_hours,'primaryGoal',primary_goal
    ) FROM public.founder_cycle_state WHERE user_id=v_founder),'{}'::jsonb)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_first_customer_sprint_v1(
  p_sprint_id uuid,
  p_final_decision text,
  p_final_notes text DEFAULT NULL
)
RETURNS public.first_customer_sprints
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_sprint public.first_customer_sprints%ROWTYPE;
  v_sent integer; v_conversations integer; v_commitments integer; v_payments integer;
BEGIN
  SELECT * INTO v_sprint FROM public.first_customer_sprints
    WHERE id=p_sprint_id AND founder_id=auth.uid() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Sprint not found' USING ERRCODE='42501'; END IF;
  IF v_sprint.mentor_checkpoint_completed_at IS NULL THEN
    RAISE EXCEPTION 'The checkpoint needs admin verification and a founder recommendation before completion';
  END IF;
  IF p_final_decision NOT IN ('continue','narrow_segment','change_offer','change_message','change_channel','pivot','pause') THEN
    RAISE EXCEPTION 'Select a valid founder decision';
  END IF;
  SELECT
    count(*) FILTER (WHERE event_type='outreach_sent'),
    count(*) FILTER (WHERE event_type='interview_completed'),
    count(*) FILTER (WHERE event_type='commitment_received'),
    count(*) FILTER (WHERE event_type='payment_received')
  INTO v_sent,v_conversations,v_commitments,v_payments
  FROM public.customer_evidence_events
  WHERE user_id=auth.uid() AND metadata->>'sprintId'=p_sprint_id::text
    AND EXISTS (
      SELECT 1 FROM public.first_customer_sprint_contacts scoped
      WHERE scoped.sprint_id=p_sprint_id AND scoped.contact_id=customer_evidence_events.contact_id
    );
  IF NOT (v_conversations>=3 OR v_commitments>0 OR v_payments>0 OR
    (v_sent>=10 AND p_final_decision IN ('pivot','pause') AND length(trim(COALESCE(p_final_notes,'')))>=3)) THEN
    RAISE EXCEPTION 'Sprint completion evidence has not been met';
  END IF;
  UPDATE public.first_customer_sprints SET status='completed', final_decision=p_final_decision,
    final_notes=NULLIF(trim(COALESCE(p_final_notes,'')),''), completed_at=now(), updated_at=now()
  WHERE id=p_sprint_id RETURNING * INTO v_sprint;
  RETURN v_sprint;
END;
$$;

REVOKE ALL ON FUNCTION public.request_first_customer_sprint_checkpoint_v1(uuid,uuid,jsonb) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.admin_update_first_customer_sprint_checkpoint_v1(uuid,text,timestamptz) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.link_first_customer_sprint_call_v1(uuid,uuid,uuid,jsonb) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.request_first_customer_sprint_checkpoint_v1(uuid,uuid,jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_first_customer_sprint_checkpoint_v1(uuid,text,timestamptz) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_update_first_customer_sprint_checkpoint_v1(uuid,text,timestamptz) TO authenticated;

COMMENT ON COLUMN public.first_customer_sprints.discovery_call_id IS 'Nullable legacy field. The admin-coordinated pilot checkpoint never writes it.';
COMMENT ON COLUMN public.first_customer_sprints.checkpoint_redacted_brief IS 'Contact-free brief supplied by the founder when requesting an admin-coordinated checkpoint.';
