WITH accelerator_seed (
  slug, title, description, url, funding_amount, location, keywords, website_url,
  application_url, logo_url, is_featured, program_duration, program_format,
  focus_stage, focus_sectors, equity_taken, funding_offered, cohort_geography,
  application_deadline_info, notable_alumni
) AS (
  VALUES
    ('y-combinator','Y Combinator','Top-tier startup accelerator for founders moving from early traction to company-defining scale.','https://www.ycombinator.com',$$500,000$$,ARRAY['San Francisco','Remote'],ARRAY['B2B SaaS','AI','Fintech','Developer Tools'], 'https://www.ycombinator.com','https://www.ycombinator.com/apply','https://logo.clearbit.com/ycombinator.com',true,'3 months','Hybrid',ARRAY['pre-seed','seed'],ARRAY['B2B SaaS','AI','Fintech','Developer Tools','Healthcare'],'7% on standard SAFE plus additional SAFE capital','$125k for 7% plus an additional SAFE investment',ARRAY['Global'],'Seasonal batches; see application page for current deadlines.','["Airbnb","Stripe","Dropbox"]'::jsonb),
    ('techstars','Techstars','Global accelerator network combining hands-on mentorship, ecosystem access, and seed investment.','https://www.techstars.com','Up to $220,000',ARRAY['Global'],ARRAY['B2B SaaS','Fintech','Climate','Healthtech'], 'https://www.techstars.com','https://www.techstars.com/accelerators','https://logo.clearbit.com/techstars.com',true,'13 weeks','In-person',ARRAY['seed'],ARRAY['B2B SaaS','Fintech','Climate','Healthtech','Consumer'],'Program equity terms apply by accelerator and note structure','Up to $220,000 plus mentor and corporate network access',ARRAY['Global'],'Multiple annual cohorts; see program page for live deadlines.','["SendGrid","DigitalOcean","Chainalysis"]'::jsonb),
    ('founder-institute','Founder Institute','Pre-seed program built to help founders validate, launch, and fundraise with structured milestones.','https://fi.co','Varies by chapter',ARRAY['Global','Remote'],ARRAY['Pre-Seed','SaaS','AI','Marketplace'], 'https://fi.co','https://fi.co/apply','https://logo.clearbit.com/fi.co',false,'14 weeks','Hybrid',ARRAY['idea','pre-seed'],ARRAY['SaaS','AI','Marketplace','Creator Economy'],'Equity-based FAST agreement applies','Structured mentoring, global network, and fundraising readiness support',ARRAY['Global'],'Rolling and chapter-based deadlines; see local chapter page.','["Udemy","TravelCar","Real"]'::jsonb),
    ('entrepreneur-first','Entrepreneur First','Talent-first company-building program helping ambitious individuals find cofounders and start venture-backed companies.','https://www.joinef.com','Pre-seed investment available',ARRAY['London','Paris','Singapore','Bengaluru'],ARRAY['Deep Tech','AI','Biotech','B2B'], 'https://www.joinef.com','https://www.joinef.com/apply','https://logo.clearbit.com/joinef.com',true,'6 months','In-person',ARRAY['idea','pre-team','pre-seed'],ARRAY['AI','Deep Tech','Biotech','Enterprise'],'Program equity applies when investment is taken','Initial investment plus founder salary support in some markets',ARRAY['Europe','Asia'],'Multiple intakes per year; see application page for dates.','["Tractable","Magic Pony","AviadoBio"]'::jsonb),
    ('antler','Antler','Day-zero investor and residency program for founders building venture-scale startups from scratch.','https://www.antler.co','Pre-seed investment available',ARRAY['Global','Hybrid'],ARRAY['AI','Fintech','Climate','Healthtech'], 'https://www.antler.co','https://www.antler.co/apply','https://logo.clearbit.com/antler.co',true,'10 weeks','Hybrid',ARRAY['idea','pre-seed'],ARRAY['AI','Fintech','Climate','Healthtech','Enterprise'],'Equity varies by market and investment package','Residency plus pre-seed investment and follow-on access',ARRAY['Global'],'Rolling and city-based cohorts; see local program page.','["Airalo","Reebelo","Xailient"]'::jsonb),
    ('500-global-flagship-accelerator','500 Global Flagship Accelerator','Founder-focused growth and fundraising program from 500 Global for globally minded early-stage startups.','https://500.co/theglobalflagship/','$150,000',ARRAY['San Francisco','Global'],ARRAY['Fintech','Commerce','SaaS','Marketplace'], 'https://500.co','https://500.co/theglobalflagship/','https://logo.clearbit.com/500.co',true,'12 weeks','Hybrid',ARRAY['seed'],ARRAY['Fintech','Commerce','SaaS','Marketplace','Consumer'],'6% standard equity on flagship terms','$150,000 plus growth curriculum and investor access',ARRAY['Global'],'Seasonal batches; see application page for current dates.','["Canva","Bukalapak","Talkdesk"]'::jsonb),
    ('seedcamp','Seedcamp','European founder platform combining pre-seed to seed capital with intensive operator support.','https://seedcamp.com','Pre-seed and seed investment',ARRAY['London','Remote'],ARRAY['Fintech','SaaS','AI','Developer Tools'], 'https://seedcamp.com','https://seedcamp.com','https://logo.clearbit.com/seedcamp.com',false,'Ongoing founder platform','Hybrid',ARRAY['pre-seed','seed'],ARRAY['Fintech','SaaS','AI','Developer Tools','Healthtech'],'Equity on investment rounds','Seed funding plus founder support, hiring, and fundraising help',ARRAY['Europe'],'Rolling conversations; see site for current application path.','["Wise","UiPath","Revolut"]'::jsonb),
    ('alchemist-accelerator','Alchemist Accelerator','Enterprise startup accelerator built for technical teams selling to businesses and regulated markets.','https://www.alchemistaccelerator.com','Seed investment available',ARRAY['San Francisco','Remote'],ARRAY['Enterprise','Developer Tools','Fintech','Climate'], 'https://www.alchemistaccelerator.com','https://www.alchemistaccelerator.com','https://logo.clearbit.com/alchemistaccelerator.com',false,'6 months','Hybrid',ARRAY['seed'],ARRAY['Enterprise','Developer Tools','Fintech','Climate','Healthcare'],'Program equity terms apply','Seed capital, customer introductions, and enterprise mentor network',ARRAY['Global'],'Multiple cohorts; see accelerator page for current timing.','["LaunchDarkly","Rigetti","Mighty Buildings"]'::jsonb),
    ('startx','StartX','Founder-led nonprofit accelerator with a deep Stanford operator and alumni network.','https://www.startx.com','No standard cash investment',ARRAY['Palo Alto'],ARRAY['AI','Enterprise','Health','Consumer'], 'https://www.startx.com','https://www.startx.com','https://logo.clearbit.com/startx.com',false,'3 months','In-person',ARRAY['pre-seed','seed'],ARRAY['AI','Enterprise','Healthcare','Consumer','Climate'],'No equity, no fees','Mentorship, alumni network, and optional access to affiliated funds',ARRAY['United States'],'Seasonal batches; see program page for the latest deadline.','["Lime","Patreon","Kodiak"]'::jsonb),
    ('berkeley-skydeck','Berkeley SkyDeck','University-backed accelerator combining mentorship, office hours, and an optional investment vehicle.','https://skydeck.berkeley.edu','$200,000 fund option',ARRAY['Berkeley','Hybrid'],ARRAY['AI','Deep Tech','Climate','Healthtech'], 'https://skydeck.berkeley.edu','https://skydeck.berkeley.edu/apply/','https://logo.clearbit.com/skydeck.berkeley.edu',false,'6 months','Hybrid',ARRAY['pre-seed','seed'],ARRAY['AI','Deep Tech','Climate','Healthtech','Enterprise'],'Optional investment terms apply through SkyDeck Fund','Program support plus optional fund investment',ARRAY['Global'],'Seasonal batches; see application page for exact dates.','["Luma AI","Molekule","DeepScribe"]'::jsonb),
    ('angelpad','AngelPad','Small-batch accelerator for founders looking for intensive mentorship and fundraising preparation.','https://angelpad.com','Seed investment available',ARRAY['New York','San Francisco'],ARRAY['SaaS','Marketplace','Consumer','Developer Tools'], 'https://angelpad.com','https://angelpad.com','https://logo.clearbit.com/angelpad.com',false,'12 weeks','In-person',ARRAY['pre-seed','seed'],ARRAY['SaaS','Marketplace','Consumer','Developer Tools','Fintech'],'Program equity terms apply','Mentorship, alumni network, and fundraising prep',ARRAY['Global'],'Seasonal cohorts; see website for current application windows.','["Postmates","Pipedrive","Coverhound"]'::jsonb),
    ('dreamit-ventures','Dreamit Ventures','Go-to-market focused accelerator for startups selling into healthtech, securetech, and urban tech buyers.','https://www.dreamit.com','No standard investment',ARRAY['Philadelphia','Remote'],ARRAY['Healthtech','Security','Urban Tech','B2B'], 'https://www.dreamit.com','https://www.dreamit.com','https://logo.clearbit.com/dreamit.com',false,'14 weeks','Hybrid',ARRAY['seed','series-a'],ARRAY['Healthtech','Security','Urban Tech','B2B SaaS'],'No standard equity for the core program','Customer and investor introductions with sector-specific coaching',ARRAY['United States'],'Program-driven application windows; see site for latest dates.','["LevelUp","SeatGeek","Houseparty"]'::jsonb),
    ('era','ERA','New York accelerator pairing early-stage founders with a concentrated operator and investor community.','https://www.eranyc.com','$150,000',ARRAY['New York'],ARRAY['Fintech','B2B SaaS','Consumer','Marketplace'], 'https://www.eranyc.com','https://www.eranyc.com','https://logo.clearbit.com/eranyc.com',false,'4 months','In-person',ARRAY['pre-seed','seed'],ARRAY['Fintech','B2B SaaS','Consumer','Marketplace','Healthtech'],'Standard accelerator equity terms apply','$150,000 plus mentor network and NYC investor access',ARRAY['United States'],'Seasonal batches; see site for current deadlines.','["Katapult","TripleLift","Cleancult"]'::jsonb),
    ('hax','HAX','SOSV-backed accelerator for hard tech, robotics, and connected hardware companies.','https://hax.co','$250,000+',ARRAY['Newark','Shenzhen','Remote'],ARRAY['Robotics','Climate','Deep Tech','Hardware'], 'https://hax.co','https://hax.co','https://logo.clearbit.com/hax.co',true,'6 months','Hybrid',ARRAY['pre-seed','seed'],ARRAY['Robotics','Climate','Deep Tech','Hardware','Industrial Tech'],'Equity varies by investment package','Capital plus prototyping, manufacturing, and supplier support',ARRAY['Global'],'Rolling and cohort-based applications; see program page.','["Formlabs","Opentrons","Seeed Studio"]'::jsonb),
    ('indiebio','IndieBio','SOSV-backed biotech accelerator for founders commercializing breakthroughs in health, food, and climate.','https://indiebio.co','Up to $525,000',ARRAY['San Francisco','New York'],ARRAY['Biotech','Climate','Food Tech','Health'], 'https://indiebio.co','https://indiebio.co','https://logo.clearbit.com/indiebio.co',true,'4 months','In-person',ARRAY['pre-seed','seed'],ARRAY['Biotech','Climate','Food Tech','Health','Synthetic Biology'],'Equity applies through SOSV investment terms','Capital plus lab access, scientific mentorship, and follow-on support',ARRAY['Global'],'Seasonal cohorts; see site for live deadlines.','["Upside Foods","Memphis Meats","Biomilq"]'::jsonb),
    ('masschallenge','MassChallenge','Zero-equity accelerator supporting startups with expert mentors, customers, and pilot opportunities.','https://masschallenge.org','Non-dilutive support',ARRAY['Boston','Houston','Rhode Island','Remote'],ARRAY['Climate','Health','Fintech','Enterprise'], 'https://masschallenge.org','https://masschallenge.org','https://logo.clearbit.com/masschallenge.org',false,'4 months','Hybrid',ARRAY['seed','series-a'],ARRAY['Climate','Health','Fintech','Enterprise','Consumer'],'No equity','Customer pilots, mentorship, and ecosystem access',ARRAY['Global'],'Annual application cycles; see current cohort page.','["Ginkgo Bioworks","Grubhub","Flywire"]'::jsonb),
    ('plug-and-play','Plug and Play','Corporate innovation accelerator with strong pilot, customer, and optional investment pathways.','https://www.plugandplaytechcenter.com','Program-dependent',ARRAY['Sunnyvale','Global'],ARRAY['Fintech','Insurtech','Enterprise','Mobility'], 'https://www.plugandplaytechcenter.com','https://www.plugandplaytechcenter.com','https://logo.clearbit.com/plugandplaytechcenter.com',false,'Program-specific','Hybrid',ARRAY['seed','series-a'],ARRAY['Fintech','Insurtech','Enterprise','Mobility','Retail'],'No standard equity; optional investment path','Corporate introductions, pilots, and optional investment',ARRAY['Global'],'Multiple annual programs by vertical and city; see site.','["PayPal","Dropbox","LendingClub"]'::jsonb),
    ('startupbootcamp','Startupbootcamp','Global accelerator network with corporate partnerships and industry-specific programs.','https://www.startupbootcamp.org','Program-dependent',ARRAY['Europe','Middle East','Asia'],ARRAY['Fintech','Climate','Health','Enterprise'], 'https://www.startupbootcamp.org','https://www.startupbootcamp.org','https://logo.clearbit.com/startupbootcamp.org',false,'3 months','Hybrid',ARRAY['seed'],ARRAY['Fintech','Climate','Health','Enterprise','Food Tech'],'Program equity terms vary by accelerator','Mentorship, partner perks, and investor demo day support',ARRAY['Global'],'Program-based deadlines; see accelerator page for current intakes.','["Relayr","ParkBee","Qlayers"]'::jsonb),
    ('creative-destruction-lab','Creative Destruction Lab','Objective-based program for science and technology founders solving hard commercial problems.','https://creativedestructionlab.com','No standard investment',ARRAY['Global'],ARRAY['AI','Climate','Quantum','Health'], 'https://creativedestructionlab.com','https://creativedestructionlab.com','https://logo.clearbit.com/creativedestructionlab.com',false,'9 months','Hybrid',ARRAY['seed','series-a'],ARRAY['AI','Climate','Quantum','Health','Space'],'No standard equity for the program','Mentor network, milestones, and venture-scale commercialization support',ARRAY['Global'],'Annual application windows by stream; see site.','["Atomwise","Xanadu","Kepler Communications"]'::jsonb),
    ('tinyseed','TinySeed','Remote accelerator and funding program for ambitious B2B SaaS bootstrappers.','https://tinyseed.com','$120,000 to $250,000',ARRAY['Remote'],ARRAY['B2B SaaS','Developer Tools','Productivity'], 'https://tinyseed.com','https://tinyseed.com/apply/','https://logo.clearbit.com/tinyseed.com',false,'1 year','Remote',ARRAY['pre-seed','seed'],ARRAY['B2B SaaS','Developer Tools','Productivity','Vertical SaaS'],'Equity-based seed investment terms apply','Remote accelerator, founder community, and seed capital',ARRAY['Global'],'Seasonal applications; see program page for live dates.','["Castos","Reclaim.ai","Tuple"]'::jsonb),
    ('muckerlab','MuckerLab','Hands-on Los Angeles accelerator for early-stage teams seeking deep operator involvement.','https://www.mucker.com/muckerlab/','Seed investment available',ARRAY['Los Angeles'],ARRAY['B2B SaaS','Consumer','Marketplaces','Fintech'], 'https://www.mucker.com/muckerlab/','https://www.mucker.com/muckerlab/','https://logo.clearbit.com/mucker.com',false,'12 weeks','In-person',ARRAY['pre-seed','seed'],ARRAY['B2B SaaS','Consumer','Marketplaces','Fintech','Healthtech'],'Program equity applies with investment','Seed capital plus concentrated mentoring and LA ecosystem access',ARRAY['United States'],'Multiple intakes; see site for current timing.','["Honey","ServiceTitan","Rula"]'::jsonb),
    ('launch-accelerator','LAUNCH Accelerator','Jason Calacanis-led accelerator focused on helping founders sharpen traction and fundraising execution.','https://launchaccelerator.co','Program-dependent',ARRAY['Remote','San Francisco'],ARRAY['SaaS','AI','Fintech','Developer Tools'], 'https://launchaccelerator.co','https://launchaccelerator.co','https://logo.clearbit.com/launchaccelerator.co',false,'10 weeks','Hybrid',ARRAY['pre-seed','seed'],ARRAY['SaaS','AI','Fintech','Developer Tools','Consumer'],'Program equity terms vary','Mentorship, fundraising coaching, and investor introductions',ARRAY['Global'],'Cohort-based applications; see site for current dates.','["LaunchDarkly","Superhuman","Airtable"]'::jsonb),
    ('founders-factory','Founders Factory','Venture studio and accelerator platform combining company-building support with capital and corporate partners.','https://foundersfactory.com','Program-dependent',ARRAY['London','Johannesburg','Milan','Singapore'],ARRAY['Fintech','Health','Climate','Consumer'], 'https://foundersfactory.com','https://foundersfactory.com','https://logo.clearbit.com/foundersfactory.com',false,'6 months','Hybrid',ARRAY['pre-seed','seed'],ARRAY['Fintech','Health','Climate','Consumer','Enterprise'],'Equity varies by studio or accelerator track','Company-building support, partner access, and capital pathways',ARRAY['Europe','Africa','Asia'],'Rolling and partner-led intakes; see site for open programs.','["Zego","Airtasker","Jitty"]'::jsonb),
    ('startmate','Startmate','Australia and New Zealand accelerator known for tight mentorship loops and a strong founder network.','https://www.startmate.com','Up to A$120,000',ARRAY['Sydney','Melbourne','Auckland','Remote'],ARRAY['B2B SaaS','Fintech','Climate','Health'], 'https://www.startmate.com','https://www.startmate.com/accelerator','https://logo.clearbit.com/startmate.com',false,'12 weeks','Hybrid',ARRAY['pre-seed','seed'],ARRAY['B2B SaaS','Fintech','Climate','Health','Developer Tools'],'Standard accelerator equity terms apply','Capital plus mentor community and ANZ investor network',ARRAY['Australia','New Zealand','Global'],'Seasonal cohorts; see program page for current dates.','["Linktree","Up","Employment Hero"]'::jsonb),
    ('seedstars','Seedstars','Emerging-market startup platform running accelerator and venture support programs across multiple regions.','https://www.seedstars.com','Program-dependent',ARRAY['Global'],ARRAY['Fintech','Climate','AgriTech','Health'], 'https://www.seedstars.com','https://www.seedstars.com','https://logo.clearbit.com/seedstars.com',false,'Program-specific','Hybrid',ARRAY['pre-seed','seed'],ARRAY['Fintech','Climate','AgriTech','Health','Education'],'Varies by market and program','Mentorship, market access, and investor exposure',ARRAY['Africa','Latin America','MENA','Asia'],'Regional and challenge-based deadlines; see site.','["Kobo360","Yodawy","PayGo"]'::jsonb),
    ('start-up-chile','Start-Up Chile','Public accelerator providing equity-free support, visas, and community for globally minded startups building from Chile.','https://startupchile.org','Equity-free grant support',ARRAY['Santiago'],ARRAY['SaaS','Fintech','Climate','Social Impact'], 'https://startupchile.org','https://startupchile.org','https://logo.clearbit.com/startupchile.org',false,'4 to 8 months','Hybrid',ARRAY['pre-seed','seed'],ARRAY['SaaS','Fintech','Climate','Social Impact','Consumer'],'No equity','Equity-free public support, coworking, and local ecosystem access',ARRAY['Global'],'Batch-based applications; see call page for current dates.','["The Not Company","Betterfly","Poliglota"]'::jsonb)
)
INSERT INTO public.funding_opportunities (
  slug, title, description, url, type, funding_amount, location, keywords, website_url,
  application_url, logo_url, is_featured, is_active, program_duration, program_format,
  focus_stage, focus_sectors, equity_taken, funding_offered, cohort_geography,
  application_deadline_info, notable_alumni
)
SELECT
  slug, title, description, url, 'accelerator', funding_amount, location, keywords, website_url,
  application_url, logo_url, is_featured, true, program_duration, program_format,
  focus_stage, focus_sectors, equity_taken, funding_offered, cohort_geography,
  application_deadline_info, notable_alumni
FROM accelerator_seed
ON CONFLICT (slug) DO UPDATE
SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  url = EXCLUDED.url,
  type = EXCLUDED.type,
  funding_amount = EXCLUDED.funding_amount,
  location = EXCLUDED.location,
  keywords = EXCLUDED.keywords,
  website_url = EXCLUDED.website_url,
  application_url = EXCLUDED.application_url,
  logo_url = EXCLUDED.logo_url,
  is_featured = EXCLUDED.is_featured,
  is_active = EXCLUDED.is_active,
  program_duration = EXCLUDED.program_duration,
  program_format = EXCLUDED.program_format,
  focus_stage = EXCLUDED.focus_stage,
  focus_sectors = EXCLUDED.focus_sectors,
  equity_taken = EXCLUDED.equity_taken,
  funding_offered = EXCLUDED.funding_offered,
  cohort_geography = EXCLUDED.cohort_geography,
  application_deadline_info = EXCLUDED.application_deadline_info,
  notable_alumni = EXCLUDED.notable_alumni;
