-- Expand Insighta VC Search to a founder-focused 50-firm directory.

WITH vc_seed (
  slug, name, firm_name, firm_website, logo_url, investment_stages, industries,
  typical_check_size_min, typical_check_size_max, geographic_focus, locations,
  remote_friendly, investment_thesis, portfolio_companies, contact_preference,
  application_url, requires_warm_intro, is_featured
) AS (
  VALUES
    ('500-startups','500 Startups','500 Startups','https://500.co','https://logo.clearbit.com/500.co',ARRAY['pre-seed','seed'],ARRAY['Fintech','SaaS','Consumer','Marketplace'],150000,500000,ARRAY['North America','Latin America','Europe','MENA','Southeast Asia'],ARRAY['San Francisco','Global'],true,'Global early-stage firm backing fast-growing startups with a strong bias toward distribution, experimentation, and founder hustle.','[{"name":"Canva","industry":"Design SaaS"},{"name":"Talkdesk","industry":"Enterprise SaaS"},{"name":"Credit Karma","industry":"Fintech"}]'::jsonb,'application','https://500.co',false,true),
    ('accel','Accel','Accel','https://www.accel.com','https://logo.clearbit.com/accel.com',ARRAY['seed','series-a','series-b'],ARRAY['Enterprise','SaaS','Fintech','Consumer','Developer Tools'],500000,5000000,ARRAY['United States','Europe','India'],ARRAY['Palo Alto','London','Bengaluru'],false,'Multi-stage venture firm known for backing category leaders early and supporting founders through global scale.','[{"name":"Slack","industry":"Enterprise SaaS"},{"name":"Atlassian","industry":"Developer Tools"},{"name":"Facebook","industry":"Consumer Internet"}]'::jsonb,'warm-intro-only','https://www.accel.com',true,true),
    ('andreessen-horowitz','Andreessen Horowitz','Andreessen Horowitz','https://a16z.com','https://logo.clearbit.com/a16z.com',ARRAY['seed','series-a','series-b'],ARRAY['AI','Enterprise','Fintech','Bio','Crypto'],500000,5000000,ARRAY['United States','Europe'],ARRAY['Menlo Park','San Francisco','New York'],false,'Technology-focused venture firm investing behind ambitious founders across software, AI, fintech, crypto, and frontier markets.','[{"name":"GitHub","industry":"Developer Tools"},{"name":"Coinbase","industry":"Crypto"},{"name":"Databricks","industry":"AI Infrastructure"}]'::jsonb,'warm-intro-only','https://a16z.com',true,true),
    ('atomico','Atomico','Atomico','https://www.atomico.com','https://logo.clearbit.com/atomico.com',ARRAY['seed','series-a','series-b'],ARRAY['Enterprise','Consumer','Fintech','Climate','AI'],500000,5000000,ARRAY['Europe','Global'],ARRAY['London'],true,'European venture firm backing mission-driven founders with global ambition from seed through growth.','[{"name":"Stripe","industry":"Fintech"},{"name":"MessageBird","industry":"Communications"},{"name":"Lilium","industry":"Climate"}]'::jsonb,'warm-intro-only','https://www.atomico.com',true,false),
    ('benchmark','Benchmark','Benchmark','https://www.benchmark.com','https://logo.clearbit.com/benchmark.com',ARRAY['seed','series-a'],ARRAY['Marketplace','Consumer','Enterprise','Fintech'],1000000,5000000,ARRAY['United States'],ARRAY['San Francisco'],false,'Concentrated early-stage partnership that backs product-driven founders building category-defining companies.','[{"name":"Uber","industry":"Marketplace"},{"name":"Snap","industry":"Consumer Internet"},{"name":"Asana","industry":"Enterprise SaaS"}]'::jsonb,'warm-intro-only','https://www.benchmark.com',true,true),
    ('bessemer-venture-partners','Bessemer Venture Partners','Bessemer Venture Partners','https://www.bvp.com','https://logo.clearbit.com/bvp.com',ARRAY['seed','series-a','series-b'],ARRAY['Cloud','Enterprise','Fintech','Healthcare','Consumer'],500000,5000000,ARRAY['United States','Europe','India','Israel'],ARRAY['San Francisco','New York','London','Bengaluru'],true,'Global venture firm with deep operator networks across cloud, fintech, healthcare, and internet software.','[{"name":"Shopify","industry":"Commerce"},{"name":"Twilio","industry":"Communications"},{"name":"LinkedIn","industry":"Professional Network"}]'::jsonb,'warm-intro-only','https://www.bvp.com',true,false),
    ('cherry-ventures','Cherry Ventures','Cherry Ventures','https://www.cherry.vc','https://logo.clearbit.com/cherry.vc',ARRAY['pre-seed','seed'],ARRAY['SaaS','Fintech','Consumer','Climate','Healthtech'],200000,1000000,ARRAY['Europe'],ARRAY['Berlin','London','Stockholm'],true,'Seed-stage European firm focused on founder-first support for product-led startups across software and consumer tech.','[{"name":"Flix","industry":"Travel"},{"name":"Moss","industry":"Fintech"},{"name":"Forto","industry":"Logistics"}]'::jsonb,'application','https://www.cherry.vc',false,false),
    ('day-one-ventures','Day One Ventures','Day One Ventures','https://www.dayoneventures.com','https://logo.clearbit.com/dayoneventures.com',ARRAY['pre-seed','seed'],ARRAY['AI','SaaS','Fintech','Developer Tools','Consumer'],100000,500000,ARRAY['United States','Europe'],ARRAY['San Francisco','Remote'],true,'Early-stage firm pairing capital with communications support for founders building breakout technology companies.','[{"name":"Superhuman","industry":"Productivity"},{"name":"Truebill","industry":"Fintech"},{"name":"Remote","industry":"HR Tech"}]'::jsonb,'email','https://www.dayoneventures.com',false,false),
    ('f-prime-capital','F-Prime Capital','F-Prime Capital','https://www.fprimecapital.com','https://logo.clearbit.com/fprimecapital.com',ARRAY['seed','series-a','series-b'],ARRAY['Healthcare','Biotech','Enterprise','Fintech'],1000000,6000000,ARRAY['United States','Europe'],ARRAY['Boston','Cambridge','London'],false,'Venture platform with deep conviction in healthcare, biotech, fintech, and enterprise software.','[{"name":"Toast","industry":"Restaurant Tech"},{"name":"Flywire","industry":"Fintech"},{"name":"Iora Health","industry":"Healthcare"}]'::jsonb,'warm-intro-only','https://www.fprimecapital.com',true,false),
    ('first-round-capital','First Round Capital','First Round Capital','https://firstround.com','https://logo.clearbit.com/firstround.com',ARRAY['pre-seed','seed'],ARRAY['SaaS','Consumer','Marketplace','Fintech','Healthcare'],250000,1000000,ARRAY['United States'],ARRAY['San Francisco','New York','Philadelphia'],false,'Specialist early-stage fund partnering with founders at company formation and first institutional rounds.','[{"name":"Roblox","industry":"Gaming"},{"name":"Notion","industry":"Productivity"},{"name":"Square","industry":"Fintech"}]'::jsonb,'warm-intro-only','https://firstround.com',true,true),
    ('founders-fund','Founders Fund','Founders Fund','https://foundersfund.com','https://logo.clearbit.com/foundersfund.com',ARRAY['seed','series-a','series-b'],ARRAY['Deep Tech','AI','Defense','Bio','Space'],500000,5000000,ARRAY['United States','Europe'],ARRAY['San Francisco'],false,'Firm backing technically ambitious founders tackling difficult problems across science, infrastructure, and frontier technology.','[{"name":"SpaceX","industry":"Space"},{"name":"Palantir","industry":"Defense Software"},{"name":"Stripe","industry":"Fintech"}]'::jsonb,'warm-intro-only','https://foundersfund.com',true,false),
    ('general-catalyst','General Catalyst','General Catalyst','https://www.generalcatalyst.com','https://logo.clearbit.com/generalcatalyst.com',ARRAY['seed','series-a','series-b'],ARRAY['AI','Enterprise','Fintech','Healthcare','Climate'],500000,5000000,ARRAY['United States','Europe','India'],ARRAY['Cambridge','San Francisco','London','Bengaluru'],true,'Global venture firm investing behind enduring companies in software, healthcare, fintech, and industrial transformation.','[{"name":"Canva","industry":"Design SaaS"},{"name":"Stripe","industry":"Fintech"},{"name":"Snap","industry":"Consumer Internet"}]'::jsonb,'warm-intro-only','https://www.generalcatalyst.com',true,true),
    ('greylock-partners','Greylock','Greylock Partners','https://greylock.com','https://logo.clearbit.com/greylock.com',ARRAY['seed','series-a'],ARRAY['Enterprise','AI','Security','Consumer','Developer Tools'],500000,3000000,ARRAY['United States'],ARRAY['Menlo Park'],false,'Founder-focused seed and Series A firm with strong operating leverage across enterprise, security, and AI infrastructure.','[{"name":"LinkedIn","industry":"Professional Network"},{"name":"Abnormal Security","industry":"Security"},{"name":"Discord","industry":"Consumer"}]'::jsonb,'warm-intro-only','https://greylock.com',true,true),
    ('hustle-fund','Hustle Fund','Hustle Fund','https://www.hustlefund.vc','https://logo.clearbit.com/hustlefund.vc',ARRAY['pre-seed','seed'],ARRAY['SaaS','Consumer','Fintech','AI','E-commerce'],25000,500000,ARRAY['United States','Southeast Asia','Canada'],ARRAY['San Francisco','Singapore','Remote'],true,'Fast-moving pre-seed fund writing early checks for founders with velocity, execution, and strong distribution instincts.','[{"name":"Webflow","industry":"No-code"},{"name":"Boom Supersonic","industry":"Aerospace"},{"name":"Plantible","industry":"Climate"}]'::jsonb,'application','https://www.hustlefund.vc',false,false),
    ('index-ventures','Index Ventures','Index Ventures','https://www.indexventures.com','https://logo.clearbit.com/indexventures.com',ARRAY['seed','series-a','series-b'],ARRAY['SaaS','Fintech','Marketplace','Gaming','Infrastructure'],500000,5000000,ARRAY['United States','Europe'],ARRAY['San Francisco','London','Geneva'],true,'Transatlantic venture firm backing founders from first check through breakout global growth.','[{"name":"Figma","industry":"Design SaaS"},{"name":"Datadog","industry":"Observability"},{"name":"Etsy","industry":"Marketplace"}]'::jsonb,'warm-intro-only','https://www.indexventures.com',true,true),
    ('indievc','Indie.vc','Indie.vc','https://www.indie.vc','https://logo.clearbit.com/indie.vc',ARRAY['pre-seed','seed'],ARRAY['SaaS','Commerce','Consumer','Developer Tools'],100000,500000,ARRAY['United States'],ARRAY['San Francisco','Remote'],true,'Alternative venture model for founders who care about durable growth, ownership, and optionality over hypergrowth.','[{"name":"Bento","industry":"HR Tech"},{"name":"Tuple","industry":"Developer Tools"},{"name":"SavvyCal","industry":"Productivity"}]'::jsonb,'application','https://www.indie.vc',false,false),
    ('insight-partners','Insight Partners','Insight Partners','https://www.insightpartners.com','https://logo.clearbit.com/insightpartners.com',ARRAY['series-a','series-b'],ARRAY['Enterprise','SaaS','Cybersecurity','DevOps','Fintech'],2000000,10000000,ARRAY['United States','Europe','Israel'],ARRAY['New York','Tel Aviv','London'],true,'Scale-oriented software investor known for helping B2B companies build repeatable growth systems and executive teams.','[{"name":"Wiz","industry":"Cybersecurity"},{"name":"Monday.com","industry":"Work Management"},{"name":"Shopify","industry":"Commerce"}]'::jsonb,'warm-intro-only','https://www.insightpartners.com',true,false),
    ('khosla-ventures','Khosla Ventures','Khosla Ventures','https://www.khoslaventures.com','https://logo.clearbit.com/khoslaventures.com',ARRAY['seed','series-a','series-b'],ARRAY['AI','Climate','Healthcare','Deep Tech','Enterprise'],500000,5000000,ARRAY['United States'],ARRAY['Menlo Park'],false,'Early-stage technology investor focused on outsized scientific and market breakthroughs with global upside.','[{"name":"Stripe","industry":"Fintech"},{"name":"DoorDash","industry":"Delivery"},{"name":"Impossible Foods","industry":"Climate"}]'::jsonb,'warm-intro-only','https://www.khoslaventures.com',true,false),
    ('lightspeed-venture-partners','Lightspeed','Lightspeed Venture Partners','https://lsvp.com','https://logo.clearbit.com/lsvp.com',ARRAY['seed','series-a','series-b'],ARRAY['Enterprise','Consumer','Fintech','Climate','AI'],500000,5000000,ARRAY['United States','Europe','India','Southeast Asia'],ARRAY['Menlo Park','San Francisco','London','Bengaluru'],true,'Global multi-stage venture platform with strong coverage across software, consumer, and frontier technology.','[{"name":"Snap","industry":"Consumer Internet"},{"name":"Epic Games","industry":"Gaming"},{"name":"Mistral AI","industry":"AI"}]'::jsonb,'warm-intro-only','https://lsvp.com',true,true),
    ('localglobe','LocalGlobe','LocalGlobe','https://www.localglobe.vc','https://logo.clearbit.com/localglobe.vc',ARRAY['pre-seed','seed'],ARRAY['SaaS','AI','Fintech','Climate','Healthtech'],200000,1000000,ARRAY['United Kingdom','Europe'],ARRAY['London'],true,'London-based seed platform helping technical founders move from first conviction to repeatable company-building.','[{"name":"Wise","industry":"Fintech"},{"name":"TravelPerk","industry":"Travel SaaS"},{"name":"Zoopla","industry":"Marketplace"}]'::jsonb,'application','https://www.localglobe.vc',false,false),
    ('nea','NEA','NEA','https://www.nea.com','https://logo.clearbit.com/nea.com',ARRAY['seed','series-a','series-b'],ARRAY['Enterprise','Healthcare','Consumer','Fintech'],1000000,10000000,ARRAY['United States','India','China'],ARRAY['Menlo Park','New York','Chevy Chase','Bengaluru'],true,'Large multi-stage venture platform backing founders building durable software, healthcare, and consumer businesses.','[{"name":"Robinhood","industry":"Fintech"},{"name":"Coursera","industry":"Edtech"},{"name":"Cloudflare","industry":"Infrastructure"}]'::jsonb,'warm-intro-only','https://www.nea.com',true,false),
    ('precursor-ventures','Precursor Ventures','Precursor Ventures','https://www.precursorvc.com','https://logo.clearbit.com/precursorvc.com',ARRAY['pre-seed'],ARRAY['SaaS','Consumer','Fintech','Marketplace','Future of Work'],25000,250000,ARRAY['United States'],ARRAY['San Francisco'],true,'Pre-seed specialist investing in people at the beginning of company formation before consensus exists.','[{"name":"The Athletic","industry":"Media"},{"name":"Carrot Fertility","industry":"Healthcare"},{"name":"Modern Health","industry":"Mental Health"}]'::jsonb,'email','https://www.precursorvc.com',false,false),
    ('sequoia-capital','Sequoia Capital','Sequoia Capital','https://www.sequoiacap.com','https://logo.clearbit.com/sequoiacap.com',ARRAY['seed','series-a','series-b'],ARRAY['Enterprise','Consumer','Fintech','Healthcare','AI'],500000,10000000,ARRAY['United States','Europe','India','Southeast Asia'],ARRAY['Menlo Park','London'],true,'Iconic venture firm partnering with founders from company formation through category leadership and global expansion.','[{"name":"Stripe","industry":"Fintech"},{"name":"Airbnb","industry":"Travel"},{"name":"Snowflake","industry":"Data Infrastructure"}]'::jsonb,'warm-intro-only','https://www.sequoiacap.com',true,true),
    ('spark-capital','Spark Capital','Spark Capital','https://www.sparkcapital.com','https://logo.clearbit.com/sparkcapital.com',ARRAY['seed','series-a'],ARRAY['Consumer','Media','SaaS','Fintech','Marketplace'],500000,3000000,ARRAY['United States'],ARRAY['Boston','San Francisco','New York'],false,'Early-stage firm comfortable backing unconventional products, consumer experiences, and software platforms.','[{"name":"Twitter","industry":"Social"},{"name":"Discord","industry":"Community"},{"name":"Plaid","industry":"Fintech"}]'::jsonb,'warm-intro-only','https://www.sparkcapital.com',true,false),
    ('tinyseed','TinySeed','TinySeed','https://tinyseed.com','https://logo.clearbit.com/tinyseed.com',ARRAY['pre-seed','seed'],ARRAY['B2B SaaS','Developer Tools','Productivity','Vertical SaaS'],120000,250000,ARRAY['Global'],ARRAY['Remote'],true,'Remote-first investment program for bootstrappers and B2B SaaS founders who want capital without a blitzscaling mandate.','[{"name":"Castos","industry":"Podcast SaaS"},{"name":"Reclaim.ai","industry":"Productivity"},{"name":"Tuple","industry":"Developer Tools"}]'::jsonb,'application','https://tinyseed.com/apply/',false,false)
)
INSERT INTO public.investors (
  slug, name, firm_name, firm_website, logo_url, investor_type, investment_stages,
  industries, typical_check_size_min, typical_check_size_max, geographic_focus,
  locations, remote_friendly, investment_thesis, portfolio_companies,
  recent_investments_count, total_portfolio_count, contact_preference,
  application_url, requires_warm_intro, is_featured, is_active, data_source, last_updated
)
SELECT
  slug, name, firm_name, firm_website, logo_url, 'vc', investment_stages, industries,
  typical_check_size_min, typical_check_size_max, geographic_focus, locations,
  remote_friendly, investment_thesis, portfolio_companies, 0,
  jsonb_array_length(portfolio_companies), contact_preference, application_url,
  requires_warm_intro, is_featured, true, 'manual', now()
FROM vc_seed
ON CONFLICT (slug) DO UPDATE
SET
  name = EXCLUDED.name,
  firm_name = EXCLUDED.firm_name,
  firm_website = EXCLUDED.firm_website,
  logo_url = EXCLUDED.logo_url,
  investor_type = EXCLUDED.investor_type,
  investment_stages = EXCLUDED.investment_stages,
  industries = EXCLUDED.industries,
  typical_check_size_min = EXCLUDED.typical_check_size_min,
  typical_check_size_max = EXCLUDED.typical_check_size_max,
  geographic_focus = EXCLUDED.geographic_focus,
  locations = EXCLUDED.locations,
  remote_friendly = EXCLUDED.remote_friendly,
  investment_thesis = EXCLUDED.investment_thesis,
  portfolio_companies = EXCLUDED.portfolio_companies,
  total_portfolio_count = EXCLUDED.total_portfolio_count,
  contact_preference = EXCLUDED.contact_preference,
  application_url = EXCLUDED.application_url,
  requires_warm_intro = EXCLUDED.requires_warm_intro,
  is_featured = EXCLUDED.is_featured,
  is_active = EXCLUDED.is_active,
  data_source = EXCLUDED.data_source,
  last_updated = now();
