WITH accelerator_seed (
  slug, title, description, url, funding_amount, location, keywords, website_url,
  application_url, logo_url, is_featured, program_duration, program_format,
  focus_stage, focus_sectors, equity_taken, funding_offered, cohort_geography,
  application_deadline_info, notable_alumni
) AS (
  VALUES
    ('norrsken-accelerator','Norrsken Accelerator','Impact-oriented accelerator for climate, health, and fintech founders building solutions with global relevance.','https://www.norrsken.org/accelerator','Investment available',ARRAY['Stockholm','Remote'],ARRAY['Climate','Health','Fintech','Impact'], 'https://www.norrsken.org/accelerator','https://www.norrsken.org/accelerator','https://logo.clearbit.com/norrsken.org',false,'3 months','Hybrid',ARRAY['pre-seed','seed'],ARRAY['Climate','Health','Fintech','Impact','SaaS'],'Program equity terms apply','Capital, impact network, and fundraising support',ARRAY['Europe','Global'],'Cohort-based applications; see accelerator page for latest dates.','["Doconomy","Matsmart","Kive"]'::jsonb),
    ('hexa','Hexa','Paris-based startup studio and accelerator working closely with founders from idea to launch.','https://www.hexa.com','Pre-seed capital available',ARRAY['Paris'],ARRAY['B2B SaaS','Fintech','Climate','Future of Work'], 'https://www.hexa.com','https://www.hexa.com','https://logo.clearbit.com/hexa.com',false,'6 months','In-person',ARRAY['idea','pre-seed'],ARRAY['B2B SaaS','Fintech','Climate','Future of Work'],'Studio equity terms apply','Venture studio support, recruiting, and pre-seed capital',ARRAY['Europe'],'Rolling studio conversations; see site for current intake.','["Aircall","Spendesk","Front"]'::jsonb),
    ('station-f-founders-program','Station F Founders Program','Large startup campus program giving founders workspace, ecosystem access, and partner perks in Paris.','https://stationf.co/program/founders-program','No standard investment',ARRAY['Paris'],ARRAY['SaaS','Consumer','Fintech','AI'], 'https://stationf.co/program/founders-program','https://stationf.co/program/founders-program','https://logo.clearbit.com/stationf.co',false,'1 year','In-person',ARRAY['pre-seed','seed'],ARRAY['SaaS','Consumer','Fintech','AI','Marketplace'],'No equity for the campus program','Workspace, ecosystem access, and startup services',ARRAY['Europe','Global'],'Rolling and batch-based admissions; see program page.','["FairMoney","Homa","Lifen"]'::jsonb),
    ('google-for-startups-accelerator','Google for Startups Accelerator','Sector-specific accelerator programs with Google mentors, product experts, and cloud support.','https://startup.google.com/programs/accelerator/','Non-dilutive support',ARRAY['Global','Hybrid'],ARRAY['AI','Climate','Health','Fintech'], 'https://startup.google.com/programs/accelerator/','https://startup.google.com/programs/accelerator/','https://logo.clearbit.com/startup.google.com',false,'10 to 12 weeks','Hybrid',ARRAY['seed','series-a'],ARRAY['AI','Climate','Health','Fintech','Cloud'],'No equity','Mentorship, product support, and cloud resources',ARRAY['Global'],'Program-specific windows by region and theme; see site.','["The News Lens","Cropin","Rec Room"]'::jsonb),
    ('aws-generative-ai-accelerator','AWS Generative AI Accelerator','Cohort program for startups building with foundation models and generative AI infrastructure.','https://aws.amazon.com/startups/accelerators/generative-ai/','Cloud credits and expert support',ARRAY['Global','Hybrid'],ARRAY['Generative AI','Infrastructure','B2B SaaS','Developer Tools'], 'https://aws.amazon.com/startups/accelerators/generative-ai/','https://aws.amazon.com/startups/accelerators/generative-ai/','https://logo.clearbit.com/aws.amazon.com',false,'8 weeks','Hybrid',ARRAY['seed','series-a'],ARRAY['Generative AI','Infrastructure','B2B SaaS','Developer Tools'],'No equity for the accelerator program','AWS credits, technical support, and mentor access',ARRAY['Global'],'Annual or program-specific windows; see AWS page for current dates.','["Selected annually by cohort","See program page","See cohort page"]'::jsonb),
    ('mit-delta-v','MIT delta v','Summer accelerator for student-led startups preparing for customer discovery and fundraising.','https://entrepreneurship.mit.edu/accelerator/delta-v/','Non-dilutive stipend support',ARRAY['Cambridge'],ARRAY['Student Founders','Deep Tech','SaaS','AI'], 'https://entrepreneurship.mit.edu/accelerator/delta-v/','https://entrepreneurship.mit.edu/accelerator/delta-v/','https://logo.clearbit.com/entrepreneurship.mit.edu',false,'3 months','In-person',ARRAY['pre-seed'],ARRAY['Deep Tech','SaaS','AI','Climate','Health'],'No equity','Summer stipend, mentorship, and venture-building curriculum',ARRAY['United States'],'Annual summer program; see site for current deadline.','["Formlabs","Sana Health","Whoop"]'::jsonb),
    ('1871-accelerator','1871 Accelerator','Chicago startup platform offering structured founder programs, mentors, and partner access.','https://1871.com','Program-dependent',ARRAY['Chicago'],ARRAY['B2B SaaS','Consumer','Fintech','Health'], 'https://1871.com','https://1871.com','https://logo.clearbit.com/1871.com',false,'Program-specific','Hybrid',ARRAY['pre-seed','seed'],ARRAY['B2B SaaS','Consumer','Fintech','Health','Civic Tech'],'No standard equity','Founder education, workspace, and corporate ecosystem access',ARRAY['United States'],'Program-based deadlines; see site for open applications.','["SpotHero","Tovala","Cameo"]'::jsonb),
    ('capital-factory','Capital Factory','Texas accelerator and venture network connecting founders with mentors, customers, and investors.','https://capitalfactory.com','Program-dependent',ARRAY['Austin','Dallas','Houston','San Antonio'],ARRAY['Enterprise','Defense','Space','Fintech'], 'https://capitalfactory.com','https://capitalfactory.com','https://logo.clearbit.com/capitalfactory.com',false,'Program-specific','Hybrid',ARRAY['seed','series-a'],ARRAY['Enterprise','Defense','Space','Fintech','Healthtech'],'Investment and terms vary by program','Mentorship, coworking, and customer access in Texas ecosystems',ARRAY['United States'],'Rolling and program-specific intakes; see site.','["Aceable","Apptronik","SailPoint"]'::jsonb),
    ('catalyst-fund','Catalyst Fund','Specialist accelerator and venture platform for fintech startups improving resilience in emerging markets.','https://catalystfund.vc','Investment available',ARRAY['Global','Remote'],ARRAY['Fintech','Climate Resilience','Insurtech','Embedded Finance'], 'https://catalystfund.vc','https://catalystfund.vc','https://logo.clearbit.com/catalystfund.vc',false,'6 months','Remote',ARRAY['pre-seed','seed'],ARRAY['Fintech','Climate Resilience','Insurtech','Embedded Finance'],'Equity applies when investment is taken','Venture support plus catalytic capital and investor access',ARRAY['Africa','Asia','Latin America'],'Cohort-based applications; see site for live timeline.','["Pezesha","Pula","Turaco"]'::jsonb),
    ('carbon13','Carbon13','Climate venture builder and accelerator for founders building ventures to reduce carbon emissions at scale.','https://carbonthirteen.com','Investment available',ARRAY['Cambridge','Berlin','Remote'],ARRAY['Climate','Industrial Tech','Energy','Built Environment'], 'https://carbonthirteen.com','https://carbonthirteen.com','https://logo.clearbit.com/carbonthirteen.com',false,'20 weeks','Hybrid',ARRAY['idea','pre-seed'],ARRAY['Climate','Industrial Tech','Energy','Built Environment'],'Venture builder equity terms apply','Carbon venture building support, customer discovery, and capital pathways',ARRAY['Europe','Global'],'Cohort-based deadlines; see site for latest dates.','["Materials Nexus","Literal Labs","Myrkle"]'::jsonb),
    ('fledge','Fledge','Impact-focused accelerator for founders building mission-driven companies in food, climate, and inclusive finance.','https://fledge.co','Seed investment available',ARRAY['Seattle','Remote'],ARRAY['Climate','AgriTech','Impact','Fintech'], 'https://fledge.co','https://fledge.co','https://logo.clearbit.com/fledge.co',false,'10 weeks','Hybrid',ARRAY['pre-seed','seed'],ARRAY['Climate','AgriTech','Impact','Fintech','Health'],'Program equity terms apply','Seed capital, mentorship, and impact investor network',ARRAY['Global'],'Rolling and cohort-based; see site for current dates.','["Goodr","Kuli Kuli","Safi Organics"]'::jsonb),
    ('boomtown-accelerators','Boomtown Accelerators','Mentor-driven accelerator for founders building scalable tech startups beyond coastal hubs.','https://boomtownaccelerator.com','Investment available',ARRAY['Boulder'],ARRAY['SaaS','Marketplace','AI','Healthtech'], 'https://boomtownaccelerator.com','https://boomtownaccelerator.com','https://logo.clearbit.com/boomtownaccelerator.com',false,'12 weeks','Hybrid',ARRAY['pre-seed','seed'],ARRAY['SaaS','Marketplace','AI','Healthtech','Climate'],'Program equity terms apply','Capital, mentor network, and founder support',ARRAY['United States'],'Seasonal intakes; see site for current application cycle.','["Rachio","Occipital","Mile High Labs"]'::jsonb),
    ('gener8tor','gener8tor','National accelerator network running sector-specific programs, venture funds, and skills accelerators.','https://www.gener8tor.com','Program-dependent',ARRAY['United States'],ARRAY['SaaS','Healthtech','Fintech','Manufacturing'], 'https://www.gener8tor.com','https://www.gener8tor.com','https://logo.clearbit.com/gener8tor.com',false,'12 weeks','Hybrid',ARRAY['pre-seed','seed'],ARRAY['SaaS','Healthtech','Fintech','Manufacturing','Climate'],'Investment varies by accelerator','Mentorship, local ecosystem support, and investor introductions',ARRAY['United States'],'Program-specific deadlines; see accelerator pages for each cohort.','["EatStreet","Abodo","Propeller Health"]'::jsonb),
    ('parallel18','Parallel18','Puerto Rico-based accelerator offering equity-free support for startups expanding into U.S. and LatAm markets.','https://parallel18.com','Up to $40,000 grant',ARRAY['San Juan'],ARRAY['Fintech','SaaS','Consumer','Impact'], 'https://parallel18.com','https://parallel18.com','https://logo.clearbit.com/parallel18.com',false,'20 weeks','Hybrid',ARRAY['pre-seed','seed'],ARRAY['Fintech','SaaS','Consumer','Impact','Climate'],'No equity','Grant capital, soft landing, and market access support',ARRAY['Latin America','United States','Global'],'Batch-based applications; see site for current deadline.','["Aumenta","Stuk","Airex"]'::jsonb),
    ('founderfuel','FounderFuel','Montreal accelerator known for intensive coaching, investor access, and a strong alumni network.','https://founderfuel.com','Seed investment available',ARRAY['Montreal'],ARRAY['AI','SaaS','Deep Tech','Marketplace'], 'https://founderfuel.com','https://founderfuel.com','https://logo.clearbit.com/founderfuel.com',false,'13 weeks','In-person',ARRAY['pre-seed','seed'],ARRAY['AI','SaaS','Deep Tech','Marketplace','Climate'],'Program equity terms apply','Capital, mentor access, and fundraising support',ARRAY['Canada','United States','Global'],'Seasonal applications; see site for current dates.','["Busbud","Flinks","Nolk"]'::jsonb),
    ('ignite','Ignite','UK accelerator and investor platform helping founders progress from idea and MVP toward venture readiness.','https://ignitestartups.com','Investment available',ARRAY['Newcastle','Remote'],ARRAY['B2B SaaS','Deep Tech','AI','Climate'], 'https://ignitestartups.com','https://ignitestartups.com','https://logo.clearbit.com/ignitestartups.com',false,'3 months','Hybrid',ARRAY['idea','pre-seed','seed'],ARRAY['B2B SaaS','Deep Tech','AI','Climate'],'Investment and equity vary by program','Mentoring, venture readiness, and investor introductions',ARRAY['United Kingdom','Europe'],'Program-based deadlines; see site for open applications.','["GeoPura","Kani","Wordnerds"]'::jsonb),
    ('zinc','Zinc','Mission-driven venture builder helping founders launch companies around societal challenges.','https://www.zinc.vc','Investment available',ARRAY['London'],ARRAY['Health','Climate','Education','Future of Work'], 'https://www.zinc.vc','https://www.zinc.vc','https://logo.clearbit.com/zinc.vc',false,'6 months','In-person',ARRAY['idea','pre-seed'],ARRAY['Health','Climate','Education','Future of Work','Public Services'],'Studio equity terms apply','Venture building support, stipend, and follow-on capital path',ARRAY['Europe'],'Seasonal venture builder calls; see site for current dates.','["Amino Labs","Acurable","Kestrix"]'::jsonb),
    ('deep-science-ventures','Deep Science Ventures','Deep tech venture creator for founders building companies in biotech, climate, agriculture, and compute.','https://deepscienceventures.com','Capital available',ARRAY['London','Remote'],ARRAY['Biotech','Climate','Agriculture','Compute'], 'https://deepscienceventures.com','https://deepscienceventures.com','https://logo.clearbit.com/deepscienceventures.com',false,'Venture creation cycle','Hybrid',ARRAY['idea','pre-seed'],ARRAY['Biotech','Climate','Agriculture','Compute'],'Venture builder equity terms apply','Company creation support, talent matching, and capital access',ARRAY['Global'],'Rolling venture creation intake; see site for current openings.','["Vivan Therapeutics","PuriFire","Mytos"]'::jsonb),
    ('brinc','Brinc','Global accelerator platform with programs across climate, food, web3, hardware, and healthcare.','https://www.brinc.io','Program-dependent',ARRAY['Global'],ARRAY['Climate','Food Tech','Hardware','Health'], 'https://www.brinc.io','https://www.brinc.io','https://logo.clearbit.com/brinc.io',false,'Program-specific','Hybrid',ARRAY['pre-seed','seed'],ARRAY['Climate','Food Tech','Hardware','Health','Web3'],'Varies by program','Mentorship, market access, and capital pathways',ARRAY['Global'],'Program-specific deadlines; see site for current cohorts.','["Lamb Labs","Amai Proteins","SUN Mobility"]'::jsonb),
    ('apx','APX','Berlin-based early-stage accelerator and investor supporting ambitious European founders from the first institutional round.','https://apx.vc','€50,000 plus optional follow-on',ARRAY['Berlin'],ARRAY['B2B SaaS','Fintech','Climate','AI'], 'https://apx.vc','https://apx.vc','https://logo.clearbit.com/apx.vc',false,'3 months','Hybrid',ARRAY['pre-seed','seed'],ARRAY['B2B SaaS','Fintech','Climate','AI','Developer Tools'],'Initial equity investment with optional SAFE follow-on','Initial capital, mentor support, and European investor access',ARRAY['Europe'],'Rolling and batch-based applications; see site for current schedule.','["Autone","Rematiq","Avelios Medical"]'::jsonb),
    ('wayra','Wayra','Telefonica-backed accelerator and open innovation platform connecting startups with enterprise customers.','https://wayra.com','Program-dependent',ARRAY['Europe','Latin America'],ARRAY['Telecom','Cybersecurity','AI','Fintech'], 'https://wayra.com','https://wayra.com','https://logo.clearbit.com/wayra.com',false,'Program-specific','Hybrid',ARRAY['seed','series-a'],ARRAY['Telecom','Cybersecurity','AI','Fintech','Enterprise'],'Investment varies by market','Enterprise pilots, distribution, and optional investment',ARRAY['Europe','Latin America'],'Country and vertical programs run on separate timelines; see site.','["Perplexity in pilot ecosystem","Cabify","Unmanned Life"]'::jsonb),
    ('food-x','Food-X','Food innovation accelerator helping startups commercialize healthier and more sustainable food systems.','https://food-x.com','Program-dependent',ARRAY['New York','Remote'],ARRAY['Food Tech','Climate','Supply Chain','Consumer'], 'https://food-x.com','https://food-x.com','https://logo.clearbit.com/food-x.com',false,'14 weeks','Hybrid',ARRAY['pre-seed','seed'],ARRAY['Food Tech','Climate','Supply Chain','Consumer'],'Program equity terms vary','Industry mentorship, pilot access, and food-system partner network',ARRAY['Global'],'Program-based applications; see site for live deadlines.','["Barnana","Apeel partner ecosystem","Misfits Market ecosystem"]'::jsonb),
    ('the-venture-city','The Venture City','Growth accelerator and investment platform focused on helping product-led companies scale efficiently.','https://www.theventure.city','Investment available',ARRAY['Miami','Madrid','Sao Paulo','Remote'],ARRAY['SaaS','Fintech','Marketplaces','Consumer'], 'https://www.theventure.city','https://www.theventure.city','https://logo.clearbit.com/theventure.city',false,'6 months','Hybrid',ARRAY['seed','series-a'],ARRAY['SaaS','Fintech','Marketplaces','Consumer','B2B'],'Equity applies when investment is taken','Capital, growth science support, and international network access',ARRAY['North America','Europe','Latin America'],'Multiple annual intakes; see site for current timing.','["ClassPass","Mural","Jobandtalent ecosystem"]'::jsonb),
    ('foundersboost','FoundersBoost','Pre-seed accelerator for very early founders who want structured mentorship and investor readiness support.','https://foundersboost.com','No standard cash investment',ARRAY['Global','Remote'],ARRAY['Pre-Seed','SaaS','AI','Marketplace'], 'https://foundersboost.com','https://foundersboost.com','https://logo.clearbit.com/foundersboost.com',false,'6 weeks','Hybrid',ARRAY['idea','pre-seed'],ARRAY['SaaS','AI','Marketplace','Fintech','Health'],'No standard equity for many cohorts','Mentorship, demo day, and investor readiness support',ARRAY['Global'],'Rolling and city-based batches; see site for latest schedule.','["Alinea","Talli","Top key alumni vary by city"]'::jsonb),
    ('google-for-startups-black-founders-fund','Google for Startups Black Founders Fund','Non-dilutive capital and support program for Black founders building venture-scale companies.','https://startup.google.com/programs/black-founders-fund/','Non-dilutive cash and credits',ARRAY['Global'],ARRAY['AI','SaaS','Fintech','Consumer'], 'https://startup.google.com/programs/black-founders-fund/','https://startup.google.com/programs/black-founders-fund/','https://logo.clearbit.com/startup.google.com',false,'Program-specific','Remote',ARRAY['seed','series-a'],ARRAY['AI','SaaS','Fintech','Consumer'],'No equity','Non-dilutive capital, credits, and founder support',ARRAY['Africa','Europe','United States','Brazil'],'Program-specific deadlines; see site for current regions.','["Selected by region annually","See current cohort","See program page"]'::jsonb),
    ('orange-fab','Orange Fab','Corporate accelerator helping startups pilot with Orange and partners across telecom, AI, and enterprise.','https://orangefab.com','Program-dependent',ARRAY['Global'],ARRAY['Telecom','AI','Enterprise','Cybersecurity'], 'https://orangefab.com','https://orangefab.com','https://logo.clearbit.com/orangefab.com',false,'Program-specific','Hybrid',ARRAY['seed','series-a'],ARRAY['Telecom','AI','Enterprise','Cybersecurity','Climate'],'No standard equity; partner-specific investment options','Corporate pilots, distribution, and strategic support',ARRAY['Europe','Africa','Middle East','United States'],'Multiple challenge and partner windows; see site.','["Actility","Intersec","Craft AI ecosystem"]'::jsonb)
)
INSERT INTO public.funding_opportunities (
  slug, title, description, url, type, funding_amount, location, keywords, website_url,
  application_url, logo_url, is_featured, is_active, program_duration, program_format,
  focus_stage, focus_sectors, equity_taken, funding_offered, cohort_geography,
  application_deadline_info, notable_alumni
)
SELECT
  slug, title, description, url, 'accelerator', funding_amount, location, keywords, website_url,
  application_url, logo_url, is_featured, true, program_duration, program_format,
  focus_stage, focus_sectors, equity_taken, funding_offered, cohort_geography,
  application_deadline_info, notable_alumni
FROM accelerator_seed
ON CONFLICT (slug) DO UPDATE
SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  url = EXCLUDED.url,
  type = EXCLUDED.type,
  funding_amount = EXCLUDED.funding_amount,
  location = EXCLUDED.location,
  keywords = EXCLUDED.keywords,
  website_url = EXCLUDED.website_url,
  application_url = EXCLUDED.application_url,
  logo_url = EXCLUDED.logo_url,
  is_featured = EXCLUDED.is_featured,
  is_active = EXCLUDED.is_active,
  program_duration = EXCLUDED.program_duration,
  program_format = EXCLUDED.program_format,
  focus_stage = EXCLUDED.focus_stage,
  focus_sectors = EXCLUDED.focus_sectors,
  equity_taken = EXCLUDED.equity_taken,
  funding_offered = EXCLUDED.funding_offered,
  cohort_geography = EXCLUDED.cohort_geography,
  application_deadline_info = EXCLUDED.application_deadline_info,
  notable_alumni = EXCLUDED.notable_alumni;
