// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import {
  clearSupabaseAuthStorage,
  createSupabaseAuthStorage,
  getSupabaseAuthStorageKey,
} from '@/integrations/supabase/sessionStorage';
import { supabaseBrowserConfig } from './env';
import type { Database } from './types';

const { url: SUPABASE_URL, publishableKey: SUPABASE_PUBLISHABLE_KEY } = supabaseBrowserConfig;

function isRefreshTokenRequest(input: RequestInfo | URL): boolean {
  const url =
    typeof input === 'string'
      ? input
      : input instanceof Request
      ? input.url
      : input.toString();

  return url.includes('/auth/v1/token') && url.includes('grant_type=refresh_token');
}

async function clearInvalidRefreshTokenResponse(input: RequestInfo | URL, response: Response) {
  if (!isRefreshTokenRequest(input) || response.status !== 400) return;

  try {
    const body = await response.clone().text();
    if (/invalid refresh token|refresh token not found/i.test(body)) {
      clearSupabaseAuthStorage(SUPABASE_URL);
    }
  } catch {
    // Keep the original auth response intact. Cleanup is best effort.
  }
}

const supabaseFetch: typeof fetch = async (input, init) => {
  const response = await fetch(input, init);
  void clearInvalidRefreshTokenResponse(input, response);
  return response;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: supabaseFetch,
  },
  auth: {
    storage: createSupabaseAuthStorage(SUPABASE_URL),
    storageKey: getSupabaseAuthStorageKey(SUPABASE_URL) ?? undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});
