// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import {
  clearSupabaseAuthStorage,
  createSupabaseAuthStorage,
  getSupabaseAuthStorageKey,
} from '@/integrations/supabase/sessionStorage';
import type { Database } from './types';


// Prefer environment variables so keys are not committed to source.
// In development create a `.env` with VITE_SUPABASE_URL and VITE_SUPABASE_KEY (do NOT commit it).
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL ?? '') as string;
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_KEY ?? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '') as string;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Warn in dev/test to avoid confusing runtime errors. Do not throw to keep DX smooth.
  // Ensure you set VITE_SUPABASE_URL and VITE_SUPABASE_KEY in your environment for dev and production.
  // Example (local .env, do NOT commit):
  // VITE_SUPABASE_URL=https://your-project.supabase.co
  // VITE_SUPABASE_KEY=public-anon-key
  console.warn('Missing Supabase env vars: VITE_SUPABASE_URL or VITE_SUPABASE_KEY. Falling back to empty strings.');
}

function isRefreshTokenRequest(input: RequestInfo | URL): boolean {
  const url =
    typeof input === 'string'
      ? input
      : input instanceof Request
      ? input.url
      : input.toString();

  return url.includes('/auth/v1/token') && url.includes('grant_type=refresh_token');
}

async function clearInvalidRefreshTokenResponse(input: RequestInfo | URL, response: Response) {
  if (!isRefreshTokenRequest(input) || response.status !== 400) return;

  try {
    const body = await response.clone().text();
    if (/invalid refresh token|refresh token not found/i.test(body)) {
      clearSupabaseAuthStorage(SUPABASE_URL);
    }
  } catch {
    // Keep the original auth response intact. Cleanup is best effort.
  }
}

const supabaseFetch: typeof fetch = async (input, init) => {
  const response = await fetch(input, init);
  void clearInvalidRefreshTokenResponse(input, response);
  return response;
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: supabaseFetch,
  },
  auth: {
    storage: createSupabaseAuthStorage(SUPABASE_URL),
    storageKey: getSupabaseAuthStorageKey(SUPABASE_URL) ?? undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});
